### ISSUE TITLE
Calcul des durées de congés "ouvrés/ouvrables".

### ISSUE THREAD

**Issue by X-Ryl669** [libertempo/web#14]
En gros, notre entreprise utilise la variante jours ouvrés/jours ouvrables. Nous travaillons effectivement 5 jours par semaine (du lundi au vendredi) mais le samedi est un jour ouvrable. Nous avons 2.5 jours de congés par mois pour un temps plein (ce qui fait 30 jours par an).

La loi stipule que tout vendredi posé entraine un samedi posé pour les 5 premiers vendredi de l'année en congés (dans ce cas, nous avons bien 5 semaines de congés payés par an, vu qu'une semaine fait 6 jours).

J'ai donc renseigné que le samedi était ouvré dans le logiciel et ça marche bien sauf pour 2 choses que je détaille ci-dessous:

1) Si un utilisateur pose ses congés du 3 au 21 août 2015 (cas complexe choisi exprès), le nombre de jours pris devrait être: (3/8=>8/8 + 10/8=>15/8 + 17/8=>22/8 - 15/8 car férié = 17 jours). Le logiciel calcule 16 jours, car il enlève bien le jour férié, mais il ne rajoute pas automatiquement le samedi final manquant

2) Il n'y a pas moyen de limiter à 5 samedi par an (exemple: un utilisateur qui pose tous ses mercredi, devrait en avoir 30 jours effectifs, par contre, s'il pose tous ses vendredi, il devrait en avoir 25 jours effectifs)

C'est quand on voit comment c'est simple en France que l'on comprend pourquoi on adore nos administrat(eur/ions), snif...

Je peux modifier le code de fonction_calcul pour ce cas, mais il faut que vous me disiez ce que je dois faire pour ajouter proprement ce système dans la config et dans la base. Idéalement, il faudrait pouvoir compter le nombre de vendredi posés par période, mais cela risque d'être fastidieux, aussi, peut être peut-on stocker le compte dans la BDD à chaque fois que l'on voit un vendredi posé.

**Comment by wouldsmina** [comment]
ok, pas simple ce truc!
L'important, c'est d'ajouter un champ à la table config pour permettre d'activer ou désactiver cette futur fonction, il faudra alors passer en version 1.7.1...
Pour les 5 vendredis par an, serait-il possible de le calculer à la volée? Parce que s'il faut ajouter un champ dans la BDD, le développement d'un plugin serait plus adapté.
Bon courage.

Pour infos, je dois encore apporter quelques modifications au niveau des droits HR  (la 1.7 sera alors considérée stable), puis je passerai au développement de la 1.7.1. 
Donc, pour la 1.7.1 :
- supprimer le champ smtp de la BDD
- ajouter un champ pour l'import d'une clé pour l'authentification CAS
- ajouter/affiner les emails...
- et maintenant, gérer les "samedis" selon le droit français
- ...

**Comment by X-Ryl669** [comment]
J'essaye de m'y mettre la semaine prochaine.
Je propose donc la chose suivante:
1) Ajout d'une configuration "mode 5 jours ouvrés sur 6 jours ouvrables" dans le formulaire de configuration (et de tout ce que cela implique)
2) Ajout d'une fonction "compteVendredi" dans le fichier de calculs, qui iterera les congés pris par la personne concernée dans les périodes de congés envisagées (mai à mai par ex), pour compter les vendredi évidemment
3) Modification du code de calcul du nombre de jours pour ajouter un jour de plus si compteVendredi() retourne <= 5 et que le dernier jour de congé posé est un vendredi.

Pour info, j'en profiterais pour ajouter le champ "Grand responsable" dont j'ai parlé dans l'autre rapport d'erreur/feature request.

**Comment by lacausse** [comment]
Bonjour,
Est ce que cette fonctionnalité a été ajouté à la 1.8.1 ?
Merci

**Comment by X-Ryl669** [comment]
Non, je ne pense pas, je n'ai pas réussi à l'implémenter par manque de temps. C'est assez compliqué en fait, vu le nombre de cas à gérer pour chaque demi-journée (en RTT, déjà avec un congé posé dans la période, congé forcé, jour férié, etc..). En gros, il faudrait faire une fonction sql qui retourne tous les vendredi complets posés dans la période précédente, et mettre en cache le résultat, pour éviter de refaire cette requête à chaque demi journée de la demande (sinon c'est l'horreur en terme de nombre de requêtes). Le problème survient lorsque le congé demandé contient le fameux 5ème vendredi (ou un vendredi férié). Il faut alors modifier en cours de route sa méthode de calcul (car à partir du 5eme vendredi, les vendredis compte pour un et plus pour 2). Ceci entraînant cela, la fonction qui calcule le nombre de jour de congés devrait être coupée en deux (celle qui prend en compte les "vendredis comptent double" et celle qui ne les prend pas en compte), et appelée par une nouvelle fonction qui change à la volée en fonction du cas. 

Bref, c'est pas simple, et n'étant pas juriste, j'ai aussi des doutes sur l'interprétation des textes (notamment sur la notion de vendredi férié, doit on compter le samedi?, et pour un samedi férié ? et si le 5eme vendredi tombe un vendredi férié, doit on compter le 6ème vendredi comme un "compte double" ou pas, etc...)

Comme d'habitude en France, on aime les choses pas très simple...

**Comment by Prytoegrian** [comment]
@X-Ryl669 : tu n'as pas d'autres manières de faire que de stocker ce comptage quelque part. Ceci afin de : 
* Le mettre en lumière là où il a été pris (dans l'apparence et dans le code, pour reconstruire des états)
* Réaliser un comptage simple lors de la prise d'une nouvelle période

Je pense qu'avec ce qu'il y a actuellement dans l'appli (+ ce qui va va arriver dans la 1.9), tu as tout ce dont tu as besoin pour mettre en place cette règle métier. Au besoin, tu peux toujours rajouter un champ / une table.

Cependant, j'éviterais les fonctions sql, trop imprévisibles. Ce sont des fonctions fantômes dans l'appli et ça oblige à avoir tout un pan de code pour s'assurer qu'elles sont biens là au moment où on en a besoin. Et pis c'est pas testable.

Par contre, je ne peux pas m'empêcher de trouver très intéressant : 

> en RTT, déjà avec un congé posé dans la période, congé forcé, jour férié, etc..

C'est vrai qu'on a pas de moyen **extrêmement simple** de savoir si un employé est en congés à un instant T. Ça pourrait être très utile.

**Comment by lacausse** [comment]
Une fonctionnalité simple dans un premier temps, serait de voir combien de samedi on était posé sur une période, dans la tableau récapitulatif par exemple.
Cela permet d'être sur que tout le monde à bien posé ses 5 samedis avant la fin de la période.

**Comment by X-Ryl669** [comment]
Ce n'est pas obligatoire de poser ses 5 samedis (heureusement, sinon toutes les entreprises utiliseraient le mode 2 CP par mois, car c'est mille fois plus simple à gérer). Donc j'ai pas la motivation pour cela (d'autant plus qu'il y a toujours les cas spéciaux des samedis fériés, que la majorité des RH ne renseignent pas, des employés à mi-temps (donc, ce n'est pas le samedi, mais le Xdi qu'il faudrait afficher)...

@Prytoegrian: Vu le nombre de cas (et d'exceptions) à gérer, ce n'est pas possible de faire simple. Quand je parle de fonctions SQL, c'est un très simple pseudo "select all friday from user_conges where XXX", je vois pas comment m'en passer. D'autant plus que quand j'ai commencé à implémenter, je me suis rendu compte de la complexité d'avoir le résultat juste (sachant que je ne connais pas toutes les lois et méthodes de calcul dans le cas des exceptions). J'ai laissé tomber, nous payons un comptable, qui paye un logiciel Sage pour cela. Si l'un d'entre vous se sent de décortiquer la loi pour savoir les règles à appliquer **dans tous les cas**, alors oui, ça vaudra la peine de s'y repencher.

**Comment by wouldsmina** [comment]
Je suis d'accord avec @X-Ryl669,  c'est pas si évident à coder cette subtilité! Peut etre qu'avec les changement opéré sur la 1.9, ce sera plus simple a mettre en oeuvre. Je me pencherai sur la question après 1.9 stable...

**Comment by Prytoegrian** [comment]
Ok je vois. Le nom « fonctions / procédures SQL » a un sens précis dans ce langage, c'est pour ça que je me suis fait abusé. Par contre, je ne suis pas de votre avis pour ce qui est de la méthode. Actuellement cette règle n'est pas gérée, donc même une règle grosse maille pourrait rendre un grand service. On pourra toujours affiner de manière incrémentielle.

**Comment by lacausse** [comment]
Je comprends que c'est pas facile à coder. Même pour un RH, c'est une véritable prise de tête pour comprendre ce qui peut être fait ou pas.
Dans notre cas, nous sommes en jour ouvrable soit 30 jours et on doit poser 5 Samedis sur la période. C'est pour cela qu'à minima avoir un compteur de Samedi serait parfait.

**Comment by obinoby** [comment]
Bonjour,
Je viens ajouter une petite précision.
Ce concept chelou s'applique aussi aux temps partiels. Dans mon cas, je ne travaille pas le mercredi. Je suis donc à 80% mais je gagne autant de jours de congés que ceux qui sont à 100%.
Par contre, un mardi posé en CP provoque automatiquement un mercredi décompté en CP.

Si cette fonction vient à être développée, il ne faut pas la limiter au samedi chômé mais aussi aux jours chômés dans le cas d'un temps partiel.

Bon courage avec tout ça.
Merci,

**Comment by Prytoegrian** [comment]
Hello,

Je peux pas vraiment creuser la question actuellement, mais je ne pense pas qu'il s'agisse de la même cause, même si au final le résultat est identique. 

Ce dont parlait OP est relatif au fait que le jeu ouvrables / ouvrés fait manquer des jours en fin d'année si tu ne rajoute pas 5 samedi. 

Par contre, ce que tu subis toi est le fait que tu ne puisses pas revenir de congés un jour où tu ne travailles pas.

**Comment by X-Ryl669** [comment]
@Prytoegrian Il a raison, c'est la même problématique, entre jours ouvrables et jours ouvrés, dans la définition du mode de décompte de la loi. Le mercredi, pour lui, est un jour ouvrable mais non ouvré. Cependant, s'il pose 2 jours (lun mar) alors la loi est claire, le mercredi est décompté comme un jour ouvré de son solde (c'est à dire 3 jours). À ne pas confondre avec le mode 5 jours par semaine pour un 80% (où, s'il pose 4 jours dont le vendredi, c'est 5 qui sont comptés).

**Comment by Prytoegrian** [comment]
En effet, je ne l'avais pas perçu comme ça. Toi tu ne bosses pas mais l'entreprise est ouverte donc c'est un jour ouvrable, ça se tient.

**Comment by Toka69** [comment]
Idem que ci-dessus, si un congé est posé la veille d'un jour de temps partiel alors deux jours de congés doivent être déduits du solde.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
