### ISSUE TITLE
Gestion des jours chaumés par groupe ou utilisateur

### ISSUE THREAD

**Issue by MorphiX00** [libertempo/web#146]
Bonjour,

Est-il possible de gérer les jours chaumé par utilisateur et par groupe ?

Je m'explique, nous avons des utilisateurs qui travail en alsace/moselle ou le vendredi saint ainsi que le 26 décembre est férié.
Nous avons également des utilisateurs travaillant a l'étranger ou les jours férié sont différents.

Est-il possible de gérer cette situation (avec un calendrier différent par utilisateurs ou groupe) ?

**Comment by wouldsmina** [comment]
Bonjour,
Non, ce n'est pas possible. Mais ce peut être une idée a creuser...

Une autre solution serait de créer des fermetures (par groupe) sur les jours fériés...

**Comment by mrlsk** [comment]
+1 c'est une fonction qui serait appréciée dans ma boite, ( le cas des utilisateurs qui travaillent à l'étranger et où jours fériés sont différents)

Au passage, un grand merci pour ce fork ;)

**Comment by FFdude** [comment]
Dans le même ordre d'idée, il serait intéressant de pouvoir gérer la durée de la semaine par groupe.
Dans ma boîte, un groupe défini d'employés travaillent du lundi au samedi.
Tous les autres travaillant du lundi au vendredi.

Je n'ai pas encore trouvé la manière d'utiliser Libertempo dans ce sens.
Je joints mes remerciements à ceux de mrlsk. Merci et bravo pour ce fork !

**Comment by wouldsmina** [comment]
nous avons un peu échanger au sujet des jours fériés qui diffère d'un groupe/employé à l'autre. Une idée en est sortie :
On créé un type de congés férié gérable uniquement par le RH. Il doit pouvoir poser un jour férié pour tout le monde ou pour un groupe (pour un employé?).
Voila, on a pas encore réfléchi à l'allure que cela aurait, mais ça pourrait ressembler au module d'ajout de jour de congés...

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
