### ISSUE TITLE
Pouvoir échanger les jours d'absence par demi-journée

### ISSUE THREAD

**Issue by LRCorwin** [libertempo/web#153]
Bonjour,

_ceci n'est pas vraiment un bug, plus un feature-request._

lors de la présentation de l'outil à un nouveau groupe d'utilisateurs, l'un d'entre eux m'a fait une remarque intéressante : 
dans l'onglet "échange jour absence", les deux mini-calendriers présentent les périodes de RTT hebdomadaires en jour plein sans tenir compte des demi-journées.
Cette personne est "off" tous les vendredi après-midi : dans les mini-calendriers, tous les vendredis sont en jaune, et au milieu, par défaut, c'est le bouton radio journée entière qui a le focus.
S'il valide le déplacement de son vendredi PM au jeudi PM, les deux journées deviennent "en jaune" dans le mini-calendrier comme s'il était off les deux jours en entier.
Le calendrier de groupe est bon, lui.

La question donc : 
serait-il possible d'inclure dans la réflexion d'une prochaine version la refonte de cette fonctionnalité pour d'une part que la gestion des demi-journées soient apparentes, et d'autre part qu'il y ait un test sur le régime RTT  de l'utilisateur pour positionner correctement le focus du bouton radio ?

merci !

**Comment by wouldsmina** [comment]
Les pavés vont être remplacé par datepicker.  Je ne crois pas que ce dernier permettra d'afficher par demi journée...

**Comment by LRCorwin** [comment]
en effet, j'ai regardé DatePicker, et il ne semble travailler qu'à journée entière.
Peut-être, à l'avenir, serait-il possible (souhaitable ?) de se pencher sur ce découpage en 1/2 journée...
merci

**Comment by Prytoegrian** [comment]
C'est dans les cartons. On ne peut décemment pas revenir sur le widget Datepicker puisqu'il est propagé partout et qu'on est en train de pousser son copain Timepicker, ce serait très mauvais pour l'image (et je parle même pas de le recoder)

Compte sur nous pour faire un formulaire le plus ergonomique possible.

**Comment by LRCorwin** [comment]
Je comprends : pas de souci.
Je verrai avec la prochaine version quel sera le ressenti des utilisateurs.
Merci

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
