### ISSUE TITLE
Imposer un délai minimum entre la demande et le début de congés payés

### ISSUE THREAD

**Issue by Shadok** [libertempo/web#160]
Afin d'éviter les demandes de congés payés le soir à 19h pour le lendemain, j'aimerais pouvoir spécifier un délai minimal (en jours) entre la demande et le début des congés payés.

**Comment by Shadok** [comment]
Cf réponse de wouldsmina sur irc :
<@wouldsmina> essaye de faire ça dans fonctions_conges.php:344 dans la fonction verif_saisie_new_demande

**Comment by Shadok** [comment]
J'ai fait ça dans fonctions_conges.php, fonction verif_saisie_new_demande, ligne 366 :
```php
    // On vérifie que la demande n'est pas dans le passé et est effectuée au moins 48h avant le début des congés (attention, on ne sait pas si il s'agit de cp ou congés exceptionnels)
    $dStart     = new DateTime( date( 'Y-m-d' ) );
    $dEnd       = new DateTime( $new_debut );
    $dDiff      = $dStart->diff( $dEnd );
    $daysDiff   = (int)$dDiff->format("%r%a");
    if( $daysDiff < 2 )
    {
        echo '<br>Les demandes de cong&eacute;s doivent &ecirc;tre effectu&eacute;es au minimum 48h &agrave; l\'avance !<br>';
        $verif = false;
    }
```

Il manque effectivement le passage du type de congés en paramètre pour ne bloquer que les congés payés, mais en attendant, ça suffira.

**Comment by Shadok** [comment]
Et, autre problème, ça bloque même si la demande est faite par un responsable, ce qui ne devrait pas être le cas.

**Comment by wouldsmina** [comment]
Ok. Tout compte fait, créer une fonction et fais y appel dans utilisateur/Fonctions.php juste avant/après l'appel de la fonction de verif (je suis sur mon phone, peut pas te donner la ligne exact.

**Comment by Shadok** [comment]
Voilà :)

**Comment by Shadok** [comment]
Reste à mettre le texte dans le fichier de langue et à pouvoir paramétrer la durée dans la configuration.

**Comment by Prytoegrian** [comment]
[Suite de la conversation IRC] Ce pour quoi je demandais s'il existait dans la loi une info dans le genre, c'était pour avoir un appui légal et explicable aux utilisateurs. Dans le cas contraire, il faut un paramétrage pour : 
* Permettre à ceux qui ne désire pas de limite de ne pas subir cette imposition,
* Permettre à ceux qui ont d'autres manières de poser d'affiner le nombre de jours,
* Éviter de mettre un nombre magique dans le code.

Ça mis de côté, histoire de ne pas perdre l'utilisateur avec des erreurs serveur qu'il n'avait pas eu côté client, il serait pas mal de manipuler davantage l'objet DatePicker pour n'avoir que les « date courante + X jours ». Je pense que le code de LT doit être le reflet des pratiques de la boîte où elle se trouve, une telle restriction ne sera donc pas incompréhensible.

Par contre, je suis pas d'accord avec toi @wouldsmina, `verif_saisie_new_demande()` est la fonction de vérification, elle devrait centraliser toutes les vérifications et de ce fait être autonome pour se demander 

« Est-ce-que je suis dans les clous de dates, compte tenu du fait que  : 
* je suis une CP (+ RTT)
* je suis demandé par un utilisateur normal (je comprends pas celle là par contre) ?
»

**Comment by wouldsmina** [comment]
> Par contre, je suis pas d'accord avec toi @wouldsmina, verif_saisie_new_demande() est la fonction de vérification, elle devrait centraliser toutes les vérifications et de ce fait être autonome pour se demander 

ouaip, c'était pas une bonne idée!

**Comment by Prytoegrian** [comment]
À bien y réfléchir, c'est davantage un problème de management que de gestion de congés. Bien sûr, LT pourrait faire *plus* que ce la loi demande - et c'est la valeur ajoutée qu'on aura sur nos concurrents - mais actuellement on ne fait déjà pas ce que la loi demande. À titre personnel, je préfère mettre la priorité sur ce dernier point.

**Comment by Shadok** [comment]
Cela ne me pose pas de problème de laisser de côté cette idée pour le moment :)

**Comment by prytoegrian** [comment]
Je pense que tu as fait le bon choix : c'est une règle que *vous* souhaitez voir implémenter pour aller au delà de la loi et adapter le logiciel à vos usages et tu l'as donc mis dans ta version du soft. De notre côté, on essaie de coller aux lois donc on n'implémentera pas cette règle, mais c'est normal que tu cherches à optimiser ta version.

L'objectif de notre migration de code est de vous permettre de faire ça, que LT soit un socle commun et que le logiciel principal soit suffisamment bien fichu pour accepter les ajustements de ce genre. Sache donc que ce sujet avance, bout après bout.

Merci à toi en tout cas.
