### ISSUE TITLE
Affichage d'un compteur au 31/05

### ISSUE THREAD

**Issue by igual** [libertempo/web#171]
Re-bonjour,

Une question. Notre entreprise à un mode d'organisation que je pense classique, à savoir que les congés annuel vont du 01/06/2015 au 31/05/2016, une personne a 25 jours à prendre entre ces deux date.
Il nous manque le moyen d'afficher le compteur sur la période. Aujourd'hui quelqu'un qui pose les congés pour Aout 2016 voit son compteur de "l'année" N (2015-2016) se réduire alors que ces jours sont à décompter pour "l'année" N+1 (2016-2017) 
Il y a-t-il une solution d'organisation ?

Merci,

**Comment by wouldsmina** [comment]
Bonjour,

non, ce n'est actuellement pas possible...

A+

**Comment by Prytoegrian** [comment]
Hello, 

bien que ça ne soit pas possible pour le moment (parce que libertempo ne le fait pas actuellement et parce que nous avons déjà un gros travail en cours), on va se garder la fonctionnalité sous le coude, c'est une très bonne idée. 

Petite base de travail, il va cependant nous falloir creuser tous les cas : http://travail-emploi.gouv.fr/droit-du-travail/temps-de-travail-et-conges/conges-et-absences/article/les-conges-payes

Même s'il y a des cas divers, il y a fort à parier que tous fonctionnent sur une base d'exercice d'année en année.

À y réfléchir comme ça, la méthode simple (je crois que tu l'avais évoqué @wouldsmina, désolé si c'était exactement ce que tu voulais dire) serait de choisir une date de changement d'exercice. Tout congés posés et validés pour après cette date créé automatiquement un nouvel exercice et décrémente le compteur sur ce dernier.
Lorsque l'on arrive sur la date de bascule, on permet à l'utilisateur qui en a le droit (bien que ce soit super intéressant de manière automatisé) de « changer d'exercice » autrement dit : 
* cloturer N
* ouvrir N+1
* migrer les reports autorisés
* modifier les compteurs selon (compteurPersoAnnuel - crédit consommé)

Je n'ai pas encore réfléchi aux impacts d'un changement de date de bascule d'exercice à l'arrache.

Cela pourrait faire le job, drôlement bien d'ailleurs. Ça pourrait être un premier pas intéressant vers davantage de métier dans LT.

@wouldsmina @igual un avis, une critique ?


La manière **encore plus simple** serait d'empêcher les dépôts pour une date ultérieure à la date de fin d'exercice, mais j'aime pas trop l'idée.

**Comment by zessx** [comment]
Je pense que ce changement peut être automatisé. Une fois la date de changement d'exercice définie (par défaut le 1er juin), tout jour de congé peut être affecté au bon exercice. Le compteur N reste correct, et au jour du changement d'exercice, il suffit alors de transférer les jours restants N dans le solde N+1.   
Rien dans les textes de lois du lien précédent ne semble contredire ce système. Au contraire, le fonctionnement par exercice semble obligatoire.

Sinon, l'interdiction des dépôts sur l'exercice N+1 est à proscrire. Dans une structure avec suffisamment de salariés, personne n'attend que mai soit révolu pour poser ses congés.

**Comment by Prytoegrian** [comment]
Tout à fait d'accord, on peut partir sur la loi pour le mode « par défaut ». Mais seulement pour celui-ci, parce que si on part du principe que tout est figé et exactement comme les textes de lois, on s'empêche de voir la diversité des accords de branches, conventions collectives, etc.


> tout jour de congé peut être affecté au bon exercice

Oui, mais dans le code source les exercices n'ont pas d'existence propre, donc on ne peut pas associer les jours à quelque chose qui n'existe pas, d'où mon idée de création à la volée, même si ton idée est meilleure sur le long terme.

J'ai bon espoir qu'un jour on puisse faire un truc tiré à quatre épingles pour les exercices.

Des idées sur la manière dont ça pourrait s'afficher dans l'appli ?

**Comment by zessx** [comment]
Je pense que la notion d'exercice doit effectivement exister dans le code, mais n'a pas de besoin réel en terme d'affichage.  
Dans une utilisation 'normale', seuls deux exercices sont utilisés à un instant T : N et N+1. C'est ce même fonctionnement qu'on retrouve sur les bulletins de paye : 
- Jours acquis (solde de l'exercice N)
- Jours en cours d'acquisition (solde de l'exercice N+1)

Si je prends l'affichage du calendrier, c'est à cet endroit que l'information me paraît la plus importante. Actuellement, on a le solde en bout de ligne, plus les jours posés dans le mois courant entre parenthèse. Cette dernière information est superflue, et j'aurai plutôt vu un affichage du type `SOLDE N (SOLDE N+1)`. Quelques exemples : 
- solde au 15 avril : `+4 (+20)` : il reste 4 jours restants sur l'exercice courant, et le solde N+1 est complet (il ne manque que les 5 jours de avril/mai)
- solde au 17 avril : `-1 (+20)` : 5 jours ont été posés sur l'exercice courant, le solde N est donc négatif, mais le solde N+1 n'a pas été entamé pour autant
- solde au 1 mai : `-1 (+22,5)` : les 2,5 jours d'avril sont ajouté au solde N+1
- solde au 11 mai : `-1 (+12,5)` : 10 jours ont été posés en août, donc sur le solde N+1
- solde au 1 juin : `+14 (+0)` : changement d'exercice, le solde N-1 est transféré, qu'il soit débiteur ou créditeur. 12,5 (ancien solde N+1) + 2,5 (pour le mois de mai) - 1 (solde débiteur) = 14.

**Comment by igual** [comment]
Merci pour vos échanges, je suis tout à fait d'accord avec ce dernier commentaire.
L'autre page ou le solde serait pertinent c'est la page "Nouvelle absence" en mode utilisateur.
Le solde N+1 n'a pas à mon sens une importance capitale (il est rare de poser tous ses congés de l'année prochaine !).

**Comment by Prytoegrian** [comment]
Nous devons aussi tenir compte du fait que les RTT ont comme période de référence l'année civile (je ne sais pas s'il y a des possibilité de changer ça dans les conventions collectives).

Bien que ce soit deux notions séparées, CP et RTT, je nous vois mal séparer les deux idées et faire un exercice pour l'un et pas pour l'autre.

---

À votre avis, doit-on formaliser l'affichage d'un exercice dans l'appli avec : 
* Création d'une liste / formulaire pour bien visualiser ce qui s'applique
* Pour tous les utilisateurs soumis à cet exercice, les règles de cet exercice s'appliquent (report reliquat, solde débiteur autorisé, limite de report etc)
* On ne peut pas poser de congés (au sens large) en dehors de la date de début et la date de fin (charge à un responsable de créer un « exercice suivant », à n'importe quel moment. Ou de demander les itérations automatiques)
* la clôture d'un exercice le clos pour tous les utilisateurs qui y sont soumis, effectue les règles que l'on a dicté plus haut et passe au suivant



Si n'y a pas de **réelles** choses à paramétrer dans un exercice autre qu'une date de début et de fin, ça pourrait être perçu comme lourd et peu intuitif. Cependant que je pense qu'ainsi, on peut paramétrer finement ce qu'*est* un exercice au sens des CP (ou RTT) pour l'appli, et par là même, ce qui doit s'appliquer à chaque instant. Et on permet aussi d'avoir plusieurs exercices applicables en parallèle.


Qu'en pensez-vous ?

**Comment by zessx** [comment]
J'aime assez l'idée de plusieurs exercices ayant des règles différentes. Je pense par exemple à une entreprise ou les RTT sont mis en place : l'exercice N ne peut pas les prendre en compte, mais on pourra modifier à l'avance l'exercice N+1.

Cela doit rester simple, mais un passage obligatoire pour que l'administrateur prenne conscience de ce paramétrage par exercice. À l'installation par exemple, ne pas avoir d'exercice, et rediriger l'admin sur un formulaire de création d'exercice (exemple non exhaustif) : 
- Date de début
- Date de fin
- Groupes/Utilisateurs concernés
- Utilisation des RTT
- Automatiser la création des exercices suivants

On évite un peu le côté "lourd", tout en montrant à l'admin qu'il pourra fixer des règles différentes sur les prochains exercices, ou laisser le système se débrouiller seul.

**Comment by Prytoegrian** [comment]
Je voyais les choses davantage éclatées. Les CP sont différentes des RTT, jusque dans leur période de référence, aussi je mettrais un exercice pour les CP et un exercice pour les RTT. On pourrait avoir un paramétrage « *Gestion des RTT* » qui permettrait d'avoir accès aux exercices et aux règles particulières des RTT.

De telle sorte que les choses de ton exemple pourront se dérouler comme suit : 
* *Juillet N* : l'entreprise commence à utiliser libertempo, on peut créer un exercice pour les CP sur la période (Juin N - Mai N+1), les utilisateurs peuvent prendre des CP et tout va bien dans le meilleur des mondes. Quand tout à coup : 

* *Septembre N* : l'entreprise met en place les RTT. On active alors la « Gestion des RTT dans l'entreprise » et on crée un exercice sur la période (Janvier N+1 - Décembre N+1). Aucun cumul mensuel de RTT n'existe pour le moment et toute prise de RTT hors de la période définie par l'exercice est empêchée.

* *Janvier N+1* : les utilisateurs peuvent désormais prendre des CP ainsi que des RTT tranquillement. Les règles de cumul pour chacun de ces deux éléments s'appuient sur ce qui est défini par l'exercice et tout le monde est content.

Ceci dit je suis assez d'accord sur le mécanisme d'accompagnement lors de l'installation, on a un gros travail à faire là dessus pour que tout devienne *évident*.

**Comment by Shadok** [comment]
http://basededonnees.indicator.fr/solde_de_conges___suppression/conges_payes_et_jours_de_rtt_non_pris___que_faire__/FRACPEAR_EU110705/2/related

Pour les RTT, ils sont censés être perdus si ils ne sont pas pris à N, mais certaines sociétés sont plus laxistes (la mienne par exemple), et on peut prendre les congés sur N/N-1 et même N-2, ainsi que les rtt en N-1 et N.

**Comment by Shadok** [comment]
De plus, si tu fais un compteur par année N, il faudra donc permettre la demande de prise de congés en anticipé si tu n'as pas assez  (ou plus) de congés sur N-1.

**Comment by Shadok** [comment]
Mais je ne pense pas que ce soit à LT de gérer ça mais plutôt au RH.
Au changement d'exercice, à lui de mettre les compteurs des utilisateurs selon le solde acquis en N-1, qu'ils peuvent donc dépenser en N.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
