### ISSUE TITLE
Amélioration: table plus lisible pour les responsables

### ISSUE THREAD

**Issue by benjoo** [libertempo/web#202]
Bonjour,

Comme on me l'a fait remarqué lorsque je préparais Libertempo pour le service où je suis, la table de la page principale des responsables n'est pas très lisible/claire...

![t1](https://cloud.githubusercontent.com/assets/19833499/15957504/dcf0686e-2eef-11e6-87a7-2fc9db3faab6.png)

C'est pourquoi je vous propose cette "amélioration" pour que ce soit plus lisible:

![t2](https://cloud.githubusercontent.com/assets/19833499/15957560/347127f4-2ef0-11e6-9f21-746434c9d386.png)

Il faut juste encore regarder pour l'affichage lors des congés exceptionnelles mais pour le moment, je trouve ça bien^^

Voilà, dîtes moi si ça vous intéresse !

**Comment by Prytoegrian** [comment]
Ça fait très "tableau Excel". Le fond du problème si j'ai bien saisi c'est la surcharge d'informations c'est ça ?

**Comment by wouldsmina** [comment]
En reprenant mes notes, je constate que nous avons prévu de revoir le contenu de la page d'accueil. @Prytoegrian est ce que cela entre en conflit avec nos projets?

**Comment by Prytoegrian** [comment]
Si tu penses à la page d'accueil commune, non. Mais pour répondre parfaitement à cette question il faudrait savoir quelle fonction rempli cette page. Quoiqu'il en soit, ça ne résoud pas le problème initial, il se pose peut-être à d'autres endroits ^^

**Comment by benjoo** [comment]
Le problème est une surcharge d'information avec pour chaque congés, deux colonnes dont on répète aussi le nom, et c'est peu clair je trouve.
Avec ma version, on explicite une seule fois le nom du congé et en dessous ses deux cases pour le solde et par an, ce qui est, je trouve, beaucoup plus lisible^^
On pourrait même inversé AN et SOLDE pour commencer avec le solde quoi. Enfin voilà ;)

**Comment by Prytoegrian** [comment]
Je vois. Finalement, j'aime assez la démarche, dans le sens où ça répond à un besoin. Par contre, si l'on cherche à mettre les autres conges/absence ça ne rentre pas dans le moule. Pire, ça ne résoud pas le problème de départ. 
Donc, pour poursuivre l'idée que tu avais toi même amorcée, pourquoi ne pas avoir le format suivant :

| identité | quotité | CP | rtt | congés autres |
| Foo bar | 99%| x / y | p/q | n|

Avec bien évidemment solde / an. Désolé si ça rend pas bien, je suis sur mobile.

**Comment by Prytoegrian** [comment]
Ping

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
