### ISSUE TITLE
All : refonte du système de droit admin

### ISSUE THREAD

**Issue by prytoegrian** [libertempo/web#205]
L'administrateur est un utilisateur particulier qui est en dehors de toute considération métier. Voici donc ce que je propose :

L'installation se fait en CLI, on s'affranchit ainsi de plein de problèmes Web, et la config du mot de passe est immédiat (ça me gratte méchamment ça). 
Si l'installation / l'upgrade se fait en cli, on peut virer les vendors du projet, c'est le cli qui fera les mise à jour / mise à niveau via composer. Le projet sera ainsi plus léger. 

Actuellement, l'administrateur est un utilisateur fantôme au sens du métier : il est utilisateur mais pouvait prendre des congés (plus possible depuis les plannings), ce qui est stupide. Ils n'étaient pas validable de surcroît. 
Comme évoqué plus haut, on pourrait distinguer le "configurateur" et "l'admin" s'il y a toujours un besoin sur ce point. 

En conséquence, l'une des premières actions de l'installation est la création d'un utilisateur, genre le RH.

Donc cet utilisateur cli ne fait que installer / configurer et n'a pas le droit de se connecter à l'application, le droit d'administration est un droit comme les autres et il est le seul à pouvoir le donner à quelqu'un. 

Cf. #198

**Comment by wouldsmina** [comment]
ok, j'ai juste une question, c'est quoi cli? :sweat_smile:

**Comment by Prytoegrian** [comment]
[je te présente CLI](https://fr.wikipedia.org/wiki/Interface_en_ligne_de_commande) :palm_tree:

**Comment by wouldsmina** [comment]
c'est bien ce que je pensais, mais je vais avoir besoin de plus d'infos du coup...

**Comment by Prytoegrian** [comment]
Résumé de conversations IRC : 
Si cette solution est séduisante et règle nombre de problèmes, il faudra prendre garde aux installations de l'appli sur des serveurs Windows. En effet, l'environnement différent pourrait poser quelques soucis comme la gestion du système ou de l'exécutabilité.

Un solution rapide comme ça et sans aucune vérification de pertinence pourrait être de déporter l'exécution au sein même de l'environnement php : 
```sh
php monScript --mesOptions
```

**Comment by Prytoegrian** [comment]
### Étude
Vu que nous allons commencer les devs sur la question prochainement, voici le compte-rendu de ma dernière étude : 
LT est un logiciel intrinsèquement métier, donc tous les utilisateurs qui doivent se connecter doivent entrer dans le flux de travail métier « congés ». Ce n'est pas le cas de l'admin. D'ailleurs le terme même d'admin (ie. accès à tout, voit tout, fait tout, corrige des actions) me paraît inadapté dans notre cas.
Nous avons pourtant dit plus haut que compte tenu du fait que nous n'avions pas la main sur l'infra, nous devons assurer la maintenance administrativo-technique du logiciel via le web.
Aussi, ce que je propose, c'est de muter le rôle « administrateur » en « configurateur » (terme à préciser, je suis nul pour trouver des noms). Ses responsabilités seraient : 
- configuration technique de l'instance (général, mail, ...)
- accéder aux logs
- réaliser les sauvegardes / restauration
- faire les mises à jour
- les choses auxquelles je n'ai pas pensé

Le reste des actions d'administration métiers reviennent au RH (création employés, groupes, types d'absence).

Si j'ai bien compris ce qui est fait dans la pratique, les RH déportent la responsabilité « admin » à un technicien, plus qualifié sur ce sujet. De ce fait, en précisant le point précédent, je propose de faire disparaître le rôle d'admin en le transformant en un droit, activable sur un employé (par défaut sur le RH). Cela à l'avantage de ne plus voir l'admin comme un rôle et de permettre à une personne plus qualifié de s'occuper de cette thématique, sans pour autant exprimer une hiérarchie stricte.

## Plan de bataille
Nous devons assurer une migration douce mais visible pour que les utilisateurs soient le moins dérangés possible. Je pense que nous devrions suivre le processus suivant : 
1. Dupliquer les responsabilités admin vers le RH
2. Mettre une option « droit de configuration » (stockée mais inutile) dans le profil employé
3. Désactivation du rôle admin : l'admin ne peut plus se connecter et utilisation du droit
3.a. Installation d'instance : le premier utilisateur est désormais « RH », avec les droits de configuration
3.b. Mise à jour d'instance : si le droit est activé nul part, il est activé chez le RH
4. Suppression du rôle admin

J'espère n'avoir rien oublié.

NB : il faudra mettre une règle métier dans la modification d'employé où un minimum de 1 configurateur est obligatoire.

## Technique
Je ne suis pas sûr de l'avoir mis quelque part. Il n'y a pas de hiérarchie au sens propre, les types d'employé sont des rôles : être « RH » ne signifie pas avoir les droits du « responsable ». De ce fait, la représentation technique du système de droit en bitwise est pertinente, en plus d'être très efficace : 
- 001 : un employé responsable
- 010 : un employé RH **mais pas** responsable
- ...

Le droit admin peut s'intégrer dedans : 100 : employé avec droit de configuration, mais c'est tout.

Si nous partons dans cette refonte, nous devons avoir conscience de vouloir partir dans la voie du bitwise (pour le web comme pour l'API).


Mes excuses pour le pavé. :dancer:

**Comment by wouldsmina** [comment]
> le premier utilisateur est désormais « RH », avec les droits de configuration

Comment cela ce comportera avec une authentification externe?

**Comment by Prytoegrian** [comment]
Aïe, j'oublie toujours ça. Ça va obliger à s'appuyer sur les co externes pendant l'installation. Je vais y réfléchir plus longuement

**Comment by LRCorwin** [comment]
Un rôle "superviseur" me parait évocateur et assez généralisé.
Je suis ok avec la disparition de la terminologie "administrateur".
Par contre, oui, attention à la connexion externe (ldap &co).

**Comment by Prytoegrian** [comment]
« Superviseur » en remplacement de l'admin ? Quand je l'entends, je pense à quelqu'un qui chapeaute, ce qui lui donne automatiquement une responsabilité. Je sais pas si c'est vraiment cette information qu'on doit transmettre

**Comment by prytoegrian** [comment]
#717 #542 #695
