### ISSUE TITLE
Processus de validation : notifier le RH de toutes les absences

### ISSUE THREAD

**Issue by prytoegrian** [libertempo/web#226]
Le RH\* a besoin d'être informé de toutes les absences qui sont effectivement validées, qu'il ai été dans la boucle de validation ou non. À cette fin, un petit paramétrage général « Oui / Non » peut faire le job.

Nous parlons bien de notifications, autrement dit cela signifie pour le moment les mails simples ; à terme nous mettrons aussi les notifications internes. Le développement doit donc représenter ce fait.

:warning: Une chose à vérifier pendant le dev et les tests, c'est qu'il ne faut pas renvoyer un mail au RH s'il a déjà été informé par le processus habituel.

\* _il peut y avoir autant de RH que nécessaire dans l'appli_

**Comment by wouldsmina** [comment]
>  À cette fin, un petit paramétrage général « Oui / Non » peut faire le job.

Donc si il y a plusieurs RH, ils recevront tous les notifications?

**Comment by Prytoegrian** [comment]
Oui, c'est pour cette raison que ça me paraît pertinent de poser la condition dans le paramétrage, afin que l'option s'intitule : « *Notifier le RH des absences validées* ». Si comme je le pense, un RH équivaut à un autre, il n'y a pas de raison qu'un soit informé et pas l'autre, de la même manière que tous pourront utiliser #40.

**Comment by Stephane60** [comment]
Bonjour, je souhaiterais que la RH recoive également les emails de validation et annulation de congés.
Pourriez vous me dire si cela est possible svp et si oui comment ?
Merci !

**Comment by wouldsmina** [comment]
re,

tu va devoir mettre les mains dans le ~~cambouis~~ code! Tu dois donc : 
- Ajouter les modèles de mails dans la BDD, table conges_mail
- adapter le code de la fonction [alerte_mail()](alerte_mail) et [constuct_and_send_mail()](https://github.com/Libertempo/Libertempo-web/blob/1.9/fonctions_conges.php#L609) pour prendre en compte respectivement le(s) RH et les nouveaux modèles.
- faire appel à la fonction alerte_email() pour le(s) RH, la ou il y est déjà appelé pour l'employé ou le responsable, par exemple [ici](https://github.com/Libertempo/Libertempo-web/blob/1.9/utilisateur/Fonctions.php#L91)

a+

**Comment by Stephane60** [comment]
Merci !

Malheureusement je suis incapable de coder.

Si une âme sensible pouvait m’aider à ce sujet ce serait sympa.

 

Merci !

 

 

 

 

De : wouldsmina [mailto:notifications@github.com] 
Envoyé : jeudi 29 juin 2017 17:31
À : Libertempo/Libertempo-web
Cc : Stephane60; Comment
Objet : Re: [Libertempo/Libertempo-web] Processus de validation : notifier le RH de toutes les absences (#226)

 

re,

tu va devoir mettre les mains dans le cambouis code! Tu dois donc :

*	Ajouter les modèles de mails dans la BDD, table conges_mail
*	adapter le code de la fonction alerte_mail() et constuct_and_send_mail() pour prendre en compte respectivement le(s) RH et les nouveaux modèles.
*	faire appel à la fonction alerte_email() pour le(s) RH, la ou il y est déjà appelé pour l'employé ou le responsable, par exemple ici

a+

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
