### ISSUE TITLE
Configuration des congés : ne pas modifier / supprimer les types de base du logiciel

### ISSUE THREAD

**Issue by prytoegrian** [libertempo/web#232]
Le fait que l'utilisateur final aie la main sur les types de congés était historiquement important compte tenu du fait qu'il fallait que l'application soit souple pour coller aux besoins précis. L'implication principale de ce fait était une absence de sens métier pour tous les types de congés, puisqu'ils peuvent être manipulés par l'utilisateur.

Nous allons devoir changer ça.
En effet, si nous voulons que le logiciel aie une vraie plus value sur les tenants et aboutissants de congés, il est nécessaire de réaliser une distinction, et pour cela il faut fixer les types pour lesquels nous avons apporté un sens métier.
En conséquence, et bien que nous ne sommes pas encore prêt d'apporter du métier dans les congés, je propose d'empêcher toute modification / suppression sur les types suivants minimum : 
- Congés Payés
- RTT

Je ne connais pas les autres donc je ne prononce pas, mais je vous laisse réagir et ajouter d'autres types.

La conséquence directe, c'est que l'utilisateur va désormais choisir l'un des types à sa disposition et en ajouter au besoin, mais :
1. Tout type ajouté manuellement n'aura aucun sens métier
2. Tout type ajouté manuellement pourra être surchargé si nous ajoutons un nouveau type avec du métier

Il est donc dans son intérêt de nous mettre dans la boucle.

**Comment by wouldsmina** [comment]
Pour bien faire, il est important de mettre à plat les règles métier (que nous pourrions appliquer dans LT) sur les types de congés.

Je commence par le plus répandu, les congés payé dans le privé (il faut s'accrocher) :


Calcul du solde : 
- acquisition de 2,5 jours par mois, soit 30 jours/an. 
- le calcul ne doit pas prendre en compte les jours d'absences : arrêt maladie, grève, congé parental, congé de garde d'enfant, congé de solidarité familiale. 
- L'employeur est en droit de calculer les jours de congés en jours ouvrés, à condition que ce mode de calcul garantisse au salarié des droits à congés au moins égaux à ceux résultant du calcul en jours ouvrables.


Congés fractionnés (à défaut d'accord ou de convention) :  
- si le salarié prend 6 jours minimum de congés en dehors du 1er mai au 31 octobre, 2 jours ouvrables supplémentaires sont accordés. 1 jour de repos supplémentaire s'il prend entre 3 et 5 jours de congés en dehors de cette même période.
- Le fractionnement de la 5e semaine de congés n'ouvre pas droit aux jours de repos supplémentaires.


Exercice : il est définit du 1er juin de l'année précédente au 31 mai de l'année en cours, mais cela peut varié selon la convention collective de l'entité.


Période de congés : 
- Le salarié ne peut pas poser plus de 24 jours ouvrables de congés consécutifs. L'employeur peut accorder une dérogation à un employé en cas de contrainte géographique ou de la présence au sein du foyer d'un enfant ou d'un adulte handicapé, ou d'une personne âgée en perte d'autonomie.
- Les dates et l'ordre des départs sont communiqués à chaque salarié et affichés au moins 1 mois à l'avance, dans les locaux normalement accessibles aux salariés. 
- L'employeur ne peut pas changer les dates de congés du salarié moins d'un mois avant le départ, sauf cas exceptionnel ou délai différent fixé par l'accord d'entrepris, convention...


**Jours ouvrés** : Jour effectivement travaillé dans une entreprise ou une administration. Le plus souvent, on compte 5 jours ouvrés par semaine (par exemple, du lundi au vendredi ou du mardi au samedi).
**Jours ouvrables** : Correspond à tous les jours de la semaine, à l'exception du jour de repos hebdomadaire (généralement le dimanche) et des jours fériés habituellement non travaillés dans l'entreprise.

Informations tirées de [service-public.fr](https://www.service-public.fr/particuliers/vosdroits/F2258).
J'ai occulté les règles non applicable à LT (congés supplémentaires pour les - de 21 ans, pour ceux qui ont des enfants, ...).
Enfin, je ne suis pas sur de bien comprendre la section "Peut-on fractionner les congés ?". Si quelqu'un est capable de comprendre de quoi il s'agit...

**Comment by Prytoegrian** [comment]
En effet, c'est le but poursuivi, mais je ne pense pas que le code actuel permette d'accueillir toutes ces subtilités, c'est pour cette raison que je voulais m'arrêter à l'étape de la restriction, le métier arrivant dans second temps (public comme privé d'ailleurs)
