### ISSUE TITLE
Gestion par responsable

### ISSUE THREAD

**Issue by sbdUPJV** [libertempo/web#234]
[Amélioration] 
Serait-il possible que les responsables puissent gérer l'ajout des nouveaux membres de leur service dans leur(s) groupe, ainsi que demi-journées non travaillées et les soldes ?
Avec php-congés j'avais modifié la vue responsable pour faire cela du fait de nos nombreux utilisateurs (issus d'un annuaire LDAP) mais pas de manière propre (pouvant prendre en compte les mises à jour de l'appli et éviter la redondance de code).

**Comment by Prytoegrian** [comment]
Salut,

peux-tu préciser le besoin, veux-tu qu'un employé existant dans l'appli puisse être déplacé par un responsable dans l'un des groupes qui sont à sa charge ? Ou doit-il le créer au passage ?


> ainsi que demi-journées non travaillées et les soldes

Je ne comprends pas cette partie, je vais te demander plus de détails.

**Comment by sbdUPJV** [comment]
Le 12/10/2016 à 09:59, Prytoegrian a écrit :
>
> Salut,
>
> peux-tu préciser le besoin, veux-tu qu'un employé existant dans 
> l'appli puisse être déplacé par un responsable dans l'un des groupes 
> qui sont à sa charge ? Ou doit-il le créer au passage ?
>

Bonjour,

en fait nous somme une université avec pas mal de services, les employés 
peuvent-être membres d'un ou plusieurs services (et certains en changent 
régulièrement). Dans ce cas ils ont un responsable par service.

L'idée est que pour un employé présent dans le LDAP un responsable 
puisse l'affecter à son groupe et gérer ses soldes de congés. Cela 
pourrait être une option pour l'application vu que ce n'est pas un cas 
généralisé dans toutes les entreprises ni les établissements.


>     ainsi que demi-journées non travaillées et les soldes
>
Les ARTT sont modifiables par ces mêmes responsables, ce sont eux qui en 
donnent l'autorisation donc nous sommes partis de la logique que c'est à 
eux de le faire, principalement parce que l'équipe qui gère globalement 
l'appli est une seule personne (pas à plein temps).
Le solde de congés annuel et total est à définir si la fiche n'existe 
pas encore dans l'appli (et peut-être différent selon la quotité les 
ARTT), et s'il y a eu une erreur rencontrée. Nous avons souvent des 
erreurs de décompte avec php-congés qu'il faut rectifier.

merci,

Stéphane

**Comment by Prytoegrian** [comment]
Ok, il y a plusieurs choses intéressantes là.

[*Dans tout ce qui va suivre, je pars du principe que vous avez un workflow de validation à un niveau : il n'y a que ton responsable qui valide tes congés, il n'y a pas de RH au dessus de lui qui fait de validation finale. Je te laisse me corriger si c'est pas le cas.*]

Si je résume bien, vous avez un admin qui n'a pas l'opportunité de s'occuper H24 des mouvements des employés (affectation à un groupe, modification des soldes et des plannings, etc) ; vous voudriez donc déporter une partie de ces responsabilités vers le responsable de groupe pour faire les mouvements tranquillement.

Selon moi, ce n'est pas au responsable de faire ça, mais tu vas pouvoir retomber sur tes pattes malgré tout.
Comme je le propose dans #205, l'administrateur n'a aucun rôle métier, il ne devrait donc pas s'occuper des affectations de groupes, modifications de plannings, etc. Ça, c'est au RH de le faire. Nous aimerions clarifier les rôles au sein de l'appli pour que le RH soit le vrai admin métier pour la version prochaine, mais je ne garantis rien.

Donc en creusant l'idée, dès lors que nous aurons remis à plat les rôles, il te suffira de changer les rôles de tous tes responsables de groupes de « Responsable » à « RH » pour qu'ils aient à la fois le pouvoir décisionnel de validation et les mouvements des employés.

Donc, dans le concept, c'est un peu particulier parce qu'il y a beaucoup de RH, mais si ça vous sied ça peut le faire.

Tu sembles dire que tu avais fait des modif de l'appli pour coller à tes besoins ; si tu veux accélérer la publication du dev, tu sais ce qu'il te reste à faire :stuck_out_tongue: 

---
Et, rien à voir, mais je note 

>  les employés peuvent-être membres d'un ou plusieurs services

tu peux m'en dire plus ? Nous avons lancé l'étude de la refonte des groupes dans ce ticket #219 et nous partions dans l'idée qu'un employé ne puisse avoir qu'un seul groupe. Nous dire comment vous procédez et à quoi cela vous sert pourrait orienter le dev dans un sens ou l'autre. Si le contenu de ta réponse est conséquente, je te laisse l'écrire dans #219, ça permettra à tout le monde d'avoir toutes les infos.

**Comment by sbdUPJV** [comment]
Le 13/10/2016 à 13:19, Prytoegrian a écrit :
>
> Ok, il y a plusieurs choses intéressantes là.
>
> [/Dans tout ce qui va suivre, je pars du principe que vous avez un 
> workflow de validation à un niveau : il n'y a que ton responsable qui 
> valide tes congés, il n'y a pas de RH au dessus de lui qui fait de 
> validation finale. Je te laisse me corriger si c'est pas le cas./]
>
exact
>
> Si je résume bien, vous avez un admin qui n'a pas l'opportunité de 
> s'occuper H24 des mouvements des employés (affectation à un groupe, 
> modification des soldes et des plannings, etc) ; vous voudriez donc 
> déporter une partie de ces responsabilités vers le responsable de 
> groupe pour faire les mouvements tranquillement.
>
c'est bien ça
>
> Selon moi, ce n'est pas au responsable de faire ça, mais tu vas 
> pouvoir retomber sur tes pattes malgré tout.
> Comme je le propose dans #205 
> <https://github.com/wouldsmina/Libertempo/issues/205>, 
> l'administrateur n'a aucun rôle métier, il ne devrait donc pas 
> s'occuper des affectations de groupes, modifications de plannings, 
> etc. Ça, c'est au RH de le faire. Nous aimerions clarifier les rôles 
> au sein de l'appli pour que le RH soit le vrai admin métier pour la 
> version prochaine, mais je ne garantis rien.
>
> Donc en creusant l'idée, dès lors que nous aurons remis à plat les 
> rôles, il te suffira de changer les rôles de tous tes responsables de 
> groupes de « Responsable » à « RH » pour qu'ils aient à la fois le 
> pouvoir décisionnel de validation et les mouvements des employés.
>
> Donc, dans le concept, c'est un peu particulier parce qu'il y a 
> beaucoup de RH, mais si ça vous sied ça peut le faire.
>
J'en discuterai avec nos RH.
>
> Tu sembles dire que tu avais fait des modif de l'appli pour coller à 
> tes besoins ; si tu veux accélérer la publication du dev, tu sais ce 
> qu'il te reste à faire 😛
>
ça viendra ;-), j'ai de quoi m'occuper en dev mais j'envisageais de 
contribuer. Il faudra me dire comment cela se passe.
>
> ------------------------------------------------------------------------
>
> Et, rien à voir, mais je note
>
>     les employés peuvent-être membres d'un ou plusieurs services
>
> tu peux m'en dire plus ? Nous avons lancé l'étude de la refonte des 
> groupes dans ce ticket #219 
> <https://github.com/wouldsmina/Libertempo/issues/219> et nous partions 
> dans l'idée qu'un employé ne puisse avoir qu'un seul groupe. Nous dire 
> comment vous procédez et à quoi cela vous sert pourrait orienter le 
> dev dans un sens ou l'autre. Si le contenu de ta réponse est 
> conséquente, je te laisse l'écrire dans #219 
> <https://github.com/wouldsmina/Libertempo/issues/219>, ça permettra à 
> tout le monde d'avoir toutes les infos.
>
ok, je vais rédiger ça

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
