### ISSUE TITLE
Template par groupe

### ISSUE THREAD

**Issue by stillcut** [libertempo/web#241]
[Amelioration]
Bonjour,
Nous sommes une communauté de communes et les règles RH différent selon le rattachement d'un slarié à la communauté ou une commune A ou B
Serait il possible d'assigner à un service un modèle comportant X congés et Y RTT ?
Ceci représenterait un gain de temps non négligeable.

**Comment by Prytoegrian** [comment]
Salut,

il y a plusieurs choses dans ta demande et je ne sais pas les dicerner.

Veux-tu que : 
* un employé puisse avoir de multiples règles métiers dans son profil,
* un groupe puisse porter en son sein des règles métiers particulières (nombres congés, mécanismes décompte, etc) commune à tous les employés qui y sont intégrés,
* … ?

As-tu la possibilité de donner un cas ? Je veux bien aussi savoir si le RH est commun si tu veux bien.

**Comment by stillcut** [comment]
Bonjour Prytoegrian,

Je souhaiterais qu'un groupe un groupe puisse porter en son sein des règles métiers particulières (nombres congés, mécanismes décompte, etc) commune à tous les employés qui y sont intégrés.

Notre service RH gère plusieurs entités, elle est donc commune à la communauté de communes et aux mairies.
Les règles RH différents selon l’appartenance au la ComCom ou aux Mairies.
Ex : 
Si rattaché à la structure A - 1607 heures annuelles -> 5 semaine de CP
Si rattaché à la structure N - 1787 heures annuelles -> 5 semaines de CP et X jours de RTT.
L'idée serait de récupérer automatiquement le nombre de jours de CP et de RTT lors de l'assignation d'un utilisateur à un groupe.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
