### ISSUE TITLE
En double validation savoir l'identité du demandeur

### ISSUE THREAD

**Issue by lordystyle** [libertempo/web#248]
## Hello, lors de la double validation le chef de groupe (ici Henri MELLAT) valide les congés de TOTO, et un mail est envoyé au deuxième validateur de ce type : 

Henri MELLAT a validé (première validation) un congés pour vous dans l'application de gestion des congés.
Il doit maintenant être accepté en deuxième validation.

Type : congés payés 
Raison : 

Date de début : 22 / 09 / 2016 (am)
## Date de fin : 23 / 09 / 2016 (pm)

Du coup le deuxième validateur ne sait pas que ces congés sont pour TOTO... le sender_name=mail de l'expéditeur donc du premier chef de groupe...

En se connectant à libertempo le deuxième validateur verra ses demandes mais si il en a plusieurs ça risque de coincer non ?

**Comment by wouldsmina** [comment]
Salut,
nous comptons revoir le système de notification dans son ensemble. En attendant, je vais prendre en compte ta demande pour la gestion des heures...

**Comment by lordystyle** [comment]
Merci,
Ma demande sur la gestion des heures ? les demi journée sur IE?

**Comment by wouldsmina** [comment]
je me suis mal exprimé! Je vais faire en sorte que les notifications pour une demande d'heure contiennent toutes les informations, en particulier ta demande : identité du demandeur lors d'une seconde validation...

**Comment by lordystyle** [comment]
ok ^^ Merci beaucoup

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
