### ISSUE TITLE
Solde de congés à date

### ISSUE THREAD

**Issue by bopware** [libertempo/web#254]
Bonjour,

Est-il possible de connaître le solde des congés d'une personne à une date ?
Si des congés ont été posés et validés et qu’ils concernent une date ultérieure, ils ne doivent pas être décomptés du solde.

Merci de votre retour.

**Comment by Prytoegrian** [comment]
Hello,

à ma connaissance, il n'existe pas de telle fonctionnalité. Que cherches-tu à faire / voir ?

**Comment by bopware** [comment]
Voici un exemple : 
En début d'année, un salarié a un solde de congés payés à 25.
Ce dernier pose 2 congés : 5 jours en janvier et 2 jours en février.
Lorsque le RH fait une édition papier, il est indiqué tous les congés pris, c'est à dire que dans notre cas, pour ce salarié, il lui reste 18 jours.

Serait-il possible de faire une édition papier de date à date ?
Dans notre cas, on voudrait éditer les congés pris en janvier ; on aurait donc un solde à 20 et les CP pris en février ne seraient pas pris en compte.

**Comment by wouldsmina** [comment]
Hello,
éditer la liste des congés sur un mois particulier pas de problème, par contre avoir le solde à une date donnée, c'est pas gagné! Nous n'avons pas d'historique du solde.

En quoi cette information t'es utile?

**Comment by bopware** [comment]
En comptabilité, tous les mois, on fait une provision pour congés, donc on a besoin de connaître le solde au 30 ou 31 de chaque mois de congés réellement restant à prendre.
S’il y en a qui ont été pour une date ultérieure, il faudrait qu’ils ne soient pas déduits, cela fausse la provision à la date.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
