### ISSUE TITLE
Sensibilité du login à la casse

### ISSUE THREAD

**Issue by stillcut** [libertempo/web#259]
[Amelioration] 

La saisie de l'identifiant est sensible à la casse.
Dans notre LDAP Active Directory, certains SamAcountName sont en minuscules quand d'autre sont en majuscules.
De ce fait, il est compliqué de communiquer de facon efficace auprès des utlisateurs sur la facon de se connecter.

Serait-il possible que la saisie de l'identifiant ne soit pas sensible à la casse ?

**Comment by Prytoegrian** [comment]
Techniquement, ce n'est pas un problème. Par contre, l'existant est un peu plus tendancieux, je ne sais pas ce qu'il en est des autres systèmes d'accès, si c'est très fréquent d'avoir un casse sensible ou non. Si c'est le cas, on ne pourra pas mettre ça en place. 
Le problème, c'est que je ne sais pas comment étudier la question :-/

Pour évaluer toutes les possibilités, de votre côté à vous, c'est possible d'harmoniser ?

**Comment by Philippe-M** [comment]
Peut être qu'un paramètre pour laisser le choix à l'admin serait plus simple à gérer au lieu d'essayer de faire un cas général ?

**Comment by Prytoegrian** [comment]
![http://www.mememaker.net/static/images/memes/4695119.jpg](http://www.mememaker.net/static/images/memes/4695119.jpg)

Je trouve qu'il y a déjà beaucoup de paramètres, mais c'est un goût personnel .-/

**Comment by Philippe-M** [comment]
C'est ce qui fait la richesse et la capacité d'un programme à s'adapter à un environnement existant et non cet environnement à s'adapter à un programme arrivant.

**Comment by stillcut** [comment]
GLPI n'est pas sensible à la casse pour l'identifiant.

**Comment by Prytoegrian** [comment]
@Philippe-M Sur le papier je suis d'accord avec toi. Mais, sans toutefois le raccrocher au sujet du ticket, tu ne peux pas mettre autant de paramétrages que de clients. La somme de code augmentant, le nombre de bug en fait de même. 
Mais même si on ne tient pas compte de bugs, à chaque fois que tu rajoutes un paramétrage, tu ajoutes une nouvelle branche à l'arbre des états de ton appli. Tout le sujet est de trouver le bon équilibre entre l'intérêt métier pour un maximum de tes utilisateurs et la garantie de la prévisibilité.

**Comment by stillcut** [comment]
En attendant une possible implémentation voici deux lignes de commandes utiles.

Lister les membres d'une OU par samAccountName
`Get-ADUser -Filter {(Name -like "*")} -SearchBase "OU=***,DC=***,,DC=***" | Ft SamAccountName`

Transformer les samAccountname d'une OU en minuscules
`Get-ADUser -Filter {(Name -like "*")} -SearchBase "OU=***,DC=***,DC=***" | foreach {Set-ADUser $_.samaccountname -Replace @{samaccountname=$_.samaccountname.ToLower()}}`

**Comment by Prytoegrian** [comment]
Cf. #195

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
