### ISSUE TITLE
Export vers Excel

### ISSUE THREAD

**Issue by kaioh31** [libertempo/web#261]
Bonjour,

J'ai récemment mis en place Libertempo au sein de ma structure et il m'apporte entière satisfaction à une fonctionnalité près : l'export vers Excel.

Avez-vous prévu dans les versions à venir la possibilité de faire un export des absences saisies vers excel (ou .csv).

Le but serait : 
- De choisir les utilisateurs (tous, groupes, ...) à exporter
- De choisir la période concernée par l'export.

Je vous remercie par avance. Je reste à votre disposition si vous aviez des questions.

Très cordialement.

**Comment by Prytoegrian** [comment]
Hello,

non, nous n'avons actuellement pas prévu cette fonctionnalité pour la prochaine version (on ne peut pas voir plus loin). Quel besoin as-tu vis à vis d'un export csv ?

**Comment by wouldsmina** [comment]
Salut,
Quel usage tu aurais d'un export Excel? un pdf ne te conviendrait pas? ou csv (comme proposé par @Prytoegrian)?
As tu vu les éditions déjà existantes? Que te faudrait il de plus?

**Comment by kaioh31** [comment]
Mon besoin est de manipuler des données sur une période définie. Par exemple dans mon service j'ai des prestataires et c'est important pour moi de pouvoir faire des états à date, pouvoir les manipuler, les comparer aux états des années précédentes, faire des statistiques, ...

Le plus simple serait d'avoir une extraction type csv jour à jour. Exemple pour quelqu'un qui pose 3,5 jours de congés payés :
`utilisateur;cp;2016-11-14;1`
`utilisateur;cp;2016-11-15;1`
`utilisateur;cp;2016-11-16;1`
`utilisateur;cp;2016-11-17;.5`

Ce n'est qu'un exemple, peut-être que ça pourrait être enrichi avec d'autres informations comme par exemple le type de demi-journée.

L'important ça serait de pouvoir sélectionner les ressources concernées (tous, groupes, unitairement) ainsi que la plage souhaitée (date_début, date_fin).

**Comment by Prytoegrian** [comment]
Ta fonctionnalité me fait penser à #254. Par contre, je suis dubitatif sur son application. Je n'ai aucun problème en soi avec les exports, par contre nous tombons sous le coup du [RGPD](http://www.lesechos.fr/idees-debats/cercle/cercle-158904-rgpd-le-prochain-grand-defi-de-la-protection-des-donnees-2014295.php) et j'ai de grosses craintes quant à notre responsabilité en tant que fournisseur de données.

Trois questions : 
1 / Tes fournisseurs et votre structure êtes au courant du RGPD ?
2 / Si oui, quelles réponses pensez-vous y apporter ?
3 / Tes prestataires auraient-ils besoin d'un export fréquent, et de quelles données ?
4 / Bon 4 en fait, de quelles stats parle-t-on ?

**Comment by kaioh31** [comment]
J'ai entendu parlé du RGPD mais ma problématique n'est pas liée. Je n'ai pas étudié cette future loi dans le détail mais je ne vois pas en quoi l'export rentre en conflit avec.

Les principales notions sont :
>
- le droit à l’effacement des données;
- le consentement clair et explicite de la personne concernée quant à l’utilisation de ses données personnelles;
- le droit de transférer ses données vers un autre fournisseur de services;
- le droit d’être informé en cas de piratage des données;
- la garantie que les politiques relatives à la vie privée soient expliquées dans un langage clair et compréhensible; et
- une mise en œuvre plus stricte et des amendes allant jusqu’à 4% du chiffre d’affaires mondial total d’une entreprise, dans le but de décourager la violation des règles.
> 

Dans mon cas je souhaite juste manipuler des données sur des absences. Je ne compte pas fournir l'export à mes prestataires, c'est pour un besoin interne. Si je veux (par exemple), savoir le nombre de jour d'absences pour un presta entre le 01/01/2016 et le 30/06/2016, Libertempo ne m'en donne pas la possibilité.

Cet export me servira aussi pour mes budgets annuels ou pour faire des points sur jours de présence prévus / jours de présence réalisés.

Une autre application : je veux calculer la moyenne de jour passer en maladie de mon équipe et faire un historique année par année. Si ça diminue ou reste stable tout va bien, si c'est en hausse ça peut vouloir dire qu'il y a un problème interne au service (condition de travail qui se dégradent par ex.).

**Comment by Prytoegrian** [comment]
Il n'y a pas de conflit, mais le fournisseur de données a une responsabilité, que ce soit sur la conservation des données au sein du logiciel (donc ça impose de faire des purges basées sur le temps), comme sur la sortie des données (donc via des exports). C'est simplement ça que je dis, et c'est pour cette raison que je voulais connaître précisément ton besoin. C'est important pour nous, pour répondre aux requêtes en tenant compte des contraintes.

En terme de mise en œuvre, tel que je me représente les choses avec les info que tu viens de me donner, il ne serait pas possible de faire un export jour à jour comme tu l'as présenté : 

```
utilisateur;cp;2016-11-14;1
utilisateur;cp;2016-11-15;1
utilisateur;cp;2016-11-16;1
utilisateur;cp;2016-11-17;.5
```

mais plutôt : 

```
utilisateur;cp;2016-11-14;2016-11-18;2.5
```

car ça impliquerait d'éclater toutes les notions de périodes (et de les stocker) pour arriver à une vue granulaire comme tu le souhaites ; c'est casser beaucoup trop de choses sur notre cœur de métier.
Nous pourrions de plus faire un export associé à une vue, pour que tu puisses faire des exports les plus précis possibles, mais cette vue n'existe pas encore, donc ça signifie de faire un nouveau module, ce qui pourrait être une très bonne chose mais ça mérite une étude.


Donc l'idée est bonne, ça peut apporter une vraie valeur ajoutée au logiciel, mais nous n'avons pas les ressources actuellement pour se mettre dedans. Nous avons passé la 1.9 sur une seule fonctionnalité, que nous n'avons pas encore fini, et nous ne pouvons pas reproduire ça car ça handicape les autres développements.

**Comment by kaioh31** [comment]
OK je comprends mieux pour la partie RGPD.

Ton type d'export me conviendrait bien mais arriverais tu à gérer les congés à cheval sur la début ou la fin de l'export ?

Ex : tu demandes un export du 23/11/2016 au 02/12/2016 et une personne a pris des congés du 21/11/2016 au 25/11/2016. L'export ne devrait prendre en compte que 3 jours des congés posés.

Sinon je comprends que tout ne peut pas être fait tout de suite, au pire si j'ai le besoin je ferai du requetage en directement sur la base.

Merci !

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
