### ISSUE TITLE
Jours de fractionnement ?

### ISSUE THREAD

**Issue by augras** [libertempo/web#269]
Bonjour,
Il semble que les jours de fractionnement ne soient pas gérés par libertempo : il s'agit d'un bonus qui va de 1 à 2 jours suivant le nombre de jours pris en dehors de la période du 1er mai au 1er octobre. Avec 5 jours on a une journée supplémentaire et avec 6 2 journées supplémentaires.
Est-ce prévu d'intégrer cette fonctionnalité ?
Merci,
Philippe

**Comment by Prytoegrian** [comment]
Hello, 

As tu une doc sur le sujet que l'on pourra bachoter ?

**Comment by augras** [comment]
Je te cherche le texte officiel.
philippe

23 novembre 2016 19:26 "Prytoegrian"  a écrit:
	Hello, 

	As tu une doc sur le sujet que l'on pourra bachoter ?

**Comment by augras** [comment]
Alors c'est bien entendu plus compliqué qu'il n'y parait car c'est différent entre le secteur privé et la fonction publique, et différent entre les 3 fonctions publiques !
Secteur privé : https://www.service-public.fr/particuliers/vosdroits/F2258 (https://www.service-public.fr/particuliers/vosdroits/F2258)(durée du congé et onglet congés fractionnés)
Fonctions publiques : https://www.service-public.fr/particuliers/vosdroits/F488 (https://www.service-public.fr/particuliers/vosdroits/F488) (Nombre de jours de congés annuels puis paragraphe jours de congés supplémentaires).
Bonnes lectures et bon courage,
Philippe
23 novembre 2016 19:26 "Prytoegrian"  a écrit:
	Hello, 

	As tu une doc sur le sujet que l'on pourra bachoter ?

**Comment by augras** [comment]
Bonsoir,
En discutant avec la responsable rh cet après-midi elle m'a dit de faire attention quant au calcul des jours de fractionnement car dans la fonction publique les congés sont gérés sur l'année civile : il faut donc prendre en compte du 1er janvier au 30 avril les jours effectivement pris, et pour la période du 1er novembre au 31 décembre on compte par contre les jours de congés non encore pris.
Il faut laisser le temps aux agents de prendre les congés fractionnés qui sont donc généralement crédités début novembre et comme les congés non encore pris deviendront des congés pris on anticipe.
Voilà pour la précision qui a plein de sens.
Philippe

**Comment by Prytoegrian** [comment]
Ok, ça s'étudie, que ce soit pour le public comme pour le privé. Je manque de bagage pour savoir s'il est souhaitable / possible de le mettre en place dans LT, @wouldsmina qu'en dis-tu ?

Dans tous les cas, l'équipe de dev est occupée à fignoler la 1.9 et ne peut pas se mettre dans le sujet actuellement. Je l'ai mis en « Help wanted », si une bonne âme veut se mettre sur le sujet d'une étude technique...

**Comment by augras** [comment]
Bonjour,
Personnellement je pense que c'est une fonctionnalité qui a son intérêt car ces jours sont largement utilisés, au moins dans la fonction publique, et que si on peut éviter de faire les calculs à la main et d'ajouter les jours manuellement également c'est un gain de temps vraiment important. Et Libertempo couvre un champ supplémentaire qui a un intérêt non négligeable. 
Sur la possibilité de le réaliser je laisse les personnes compétentes répondre.
Je ne suis pas développeur et n'est pas beaucoup d'aptitudes dans ce domaine : je bricole un peu.... de là à faire une étude technique.... qu'entends tu par étude technique ?
Philippe

**Comment by wouldsmina** [comment]
Hello,
Je ne connaissais pas ce système de fractionnement! je pense qu'il faut qu'on l’intègre à LT...
Merci @augras

**Comment by wouldsmina** [comment]
On va avoir besoin de plus d'informations à ce sujet. Je me demande, par exemple, comment cela fonctionne avec les [1607 heures/an](https://www.service-public.fr/particuliers/vosdroits/F471)??

**Comment by augras** [comment]
Bonjour,
Super : merci.
Philippe

28 novembre 2016 08:51 "wouldsmina"  a écrit: 
	Hello,
Je ne connaissais pas ce système de fractionnement! je pense qu'il faut qu'on l’intègre à LT...
Merci @augras (https://github.com/augras)

**Comment by augras** [comment]
Et bien du coup les 1607h ne peuvent être tenues ! Des dérogations sont prévues à ces 1607h : ces jours en font manifestement partie. 

	Ici, comme vu avec la responsable RH, c'est appliqué "bêtement" en comptant les jours pris du 1er janvier au 31 mars, et subtilité expliquée précédemment, les jours restants à prendre au 1er novembre.

Philippe

28 novembre 2016 09:20 "wouldsmina"  a écrit: 
	On va avoir besoin de plus d'informations à ce sujet. Je me demande, par exemple, comment cela fonctionne avec les 1607 heures/an (https://www.service-public.fr/particuliers/vosdroits/F471)??

**Comment by augras** [comment]
Bonjour,
En quoi je peux aider pour que l'on avance sur ces jours de fractionnements ?
Philippe

**Comment by wouldsmina** [comment]
ce qu'il nous manque c'est du temps :)
on est pas mal occupé par la prochaine version qui ne devrait pas tarder à sortir en beta.
Mais si tu veux, tu peux essayer de définir le fonctionnement de cette fonctionnalité dans LT (on t'orientera si besoin) et si tu maîtrise PHP pourquoi pas le développer et proposer une PR (dans ce cas, inspire toi de se qui est fait dans la branche topic/heure).
a+

**Comment by augras** [comment]
Aucune volonté de ma part de presser l'équipe : je comprends parfaitement que tout le monde à une vie !
L'idée est de me rendre utile et tant qu'à faire sur quelque chose que j'ai demandé.
Par contre je bricole php et ne suis pas capable de développer la fonction.
Mais réfléchir ça je peux !
Philippe

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
