### ISSUE TITLE
CET

### ISSUE THREAD

**Issue by augras** [libertempo/web#270]
Bonjour,
J'ai activé le plugins CET. A partir de là les utilisateurs ont la possibilité de demander le versement de jours sur leur CET : par contre rien n'apparaît dans les demandes en cours.
Du côté du valideur les demandes apparaissent bien mais pas de possibilité de faire quoi que se soit, valider/refuser.... : il y a un dysfonctionnement ou s'est prévu comme ça ?
Merci,
Philippe

**Comment by wouldsmina** [comment]
Le plugin n'est pas fonctionnel. Il est prévu qu'on retire ce système de plugin (un jour) et d'intégrer la gestion des CET dans LT directement.

**Comment by augras** [comment]
Ah, je comprends mieux. 

	On va gérer en attendant avec une catégorie de congés supplémentaire appelée "CET" qui sera alimentée à la main en fonction des demandes.
Philippe

28 novembre 2016 08:53 "wouldsmina"  a écrit: 
	Le plugin n'est pas fonctionnel. Il est prévu qu'on retire ce système de plugin (un jour) et d'intégrer la gestion des CET dans LT directement.
