### ISSUE TITLE
Relecture des commentaires sur échange jours d'absence

### ISSUE THREAD

**Issue by LRCorwin** [libertempo/web#272]
Bonjour à tous,

à priori, je ne sais pas s'il s'agit d'un bug ou d'une absence de fonctionnalité.
Je pose donc la question, à tout hasard.

Un utilisateur m'a démontré que lors de changement de jour d'absence, les commentaires qu'il pose ne sont ensuite plus visible nulle part.
Je vois bien ses comm' en BdD, aussi m'attendais-je à le retrouver au survol de la souris dans le calendrier.
Mais visiblement, non.

Manquerait-il quelque chose quelque part ?

Merci

**Comment by wouldsmina** [comment]
Salut,

Je confirme le bug. Les échanges de jours d'absence doivent, de toute façon, être revu afin d’intégrer un workflow de validation. Ce ticket sera parfait pour en discuter...

Merci

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur la mailing list.

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
