### ISSUE TITLE
Possibilité de rallonger les arrêts maladie

### ISSUE THREAD

**Issue by Shadok** [libertempo/web#275]
Je me demande si il ne serait pas utile de pouvoir modifier une demande d'arrêt maladie une fois posée et validée.
Car l'arrêt peut être prolongé ou raccourci, donc cela peut-être utile de n'avoir qu'une seule demande pour simplifier la compréhension et conserver une correspondance avec l'arrêt maladie réel.

**Comment by Prytoegrian** [comment]
Pour ce qui est de la prolongation d'arrêt maladie, il s'agit d'un nouvel acte au sens même de la sécurité sociale, ça me choquerait pas de suivre ce mouvement. 
Pour la réduction, je ne sais pas si ça existe, tu as de la donnée ? 

Ça me gêne de modifier une demande validée, je trouve le contrat de prise de congé entre l'employeur et l'employé rompu ainsi. Pour le code, on ouvre une brêche.

**Comment by Shadok** [comment]
https://www.service-public.fr/particuliers/vosdroits/F12743
On peut donc bien réduire un arrêt.

**Comment by Shadok** [comment]
Si on peut annuler une demande validée, cela permettrait d'en déposer une nouvelle, sans toucher à une demande existante.

**Comment by Prytoegrian** [comment]
Ceci, on pourrait le voir comme une extension, avec un commentaire formaté basé sur le commentaire de la demande étendue, et où la date de début serait déjà remplie. Mais je me demande si l'idée est suffisamment applicable / utile pour le mettre sur les autres types et ainsi factoriser les besoins.

**Comment by Shadok** [comment]
Pas vraiment, l'arrêt maladie est un cas particulier.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
