### ISSUE TITLE
Fonctionnalité - informer les utilisateurs des modifications effectuées par les Responsables.

### ISSUE THREAD

**Issue by FrantzPa** [libertempo/web#291]
Bonjour,
je voulais savoir si il existait une possibilité pour que chaque utiliseur recoive une notification lorsque le Responsable modifie ses information (ajout de congés)...
merci par avance.

**Comment by wouldsmina** [comment]
Bonjour,
J'avais un doute, mais non ce n'est pas possible. Si tu veux qu'on étudie ta proposition merci de bien définir ton besoin...
a+

**Comment by FrantzPa** [comment]
bonjour, merci pour la réponse.
le besoin demandée est le suivant. j'espère que cela sera claire.:-)
Le responsable ou le RH procède à un ajout de congés (global, groupe ou utilisateurs) .
après validation, chaque utilisateur concerné par l'ajout reçoit une notification par mail l'informant qu'un ajout à été effectué.
pourquoi cette demande ? dans notre service, il arrive que les ajouts suite aux heures supplémentaires effectuées ne soient pas bons et les utilisateurs s'en appercoivent que bien trop tard.
bonne journée.
F.

**Comment by Prytoegrian** [comment]
Je viens d'avoir l'idée comme ça, c'est un truc qui serait typiquement éligible au dashboard. En effet, sur la page d'accueil de l'utilisateur où on verrait tous les événements, on pourrait aussi avoir ça. De plus, la page d'une sortie (cp, rtt, maladie, …) pourrait afficher tous les événements arrivés sur elle : 
- création
- modification
- validation
- …

La cerise sur le gateau pourrait être une notif par mail, mais c'est pas obligatoire.

**Comment by FrantzPa** [comment]
Bonjour,
cela me parait très bien :-).
cela correspond tout à fait.
bonne fin de journée.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
