### ISSUE TITLE
[congés exceptionnels] Saisie par le RH et/ou le responsable

### ISSUE THREAD

**Issue by augras** [libertempo/web#293]
Bonjour,
Libertempo est maintenant en fonction et nous ajustons au fur et à mesure des cas de figure.
Nous avons défini des congés (congés annuels, rtt, CET), des absences (formation, mission) et des congés exceptionnels.
Pour les congés ça fonctionne comme prévu.
Pour les absences j'ai bien vu dans la doc qu'un mail d'info était envoyé au responsable et qu'il n'y avais pas de validation : pas de soucis avec ça.
C'est pour les congés exceptionnels que je n'ai rien trouvé et avant de tomber sur un os je préfère savoir comment ça fonctionne dans ce dernier cas.
Ces congés exceptionnels étant particuliers, enfant malade/maladie/congé de maternité/congé de paternité/autorisation... il faudrait dans l'idéal que le responsable soit informé mais que se soit le rh qui valide en définitif avec avis du responsable, et même carrément renseigne dans le cas d'un congé maladie par exemple.
Peut-être que je n'ai pas correctement paramétré mais le rh peut saisir un congé, une absence mais pas de congés exceptionnel : c'est un bug ou j'ai oublié un paramètre ?
Merci pour les infos,
Philippe

**Comment by wouldsmina** [comment]
Salut,

Je viens de jeter un œil rapidement sur la démo, en effet il n'est pas possible de saisir des congés exceptionnels à la place d'un employé. 

ce n'est ni un bug ni un oubli de paramètre, c'est simplement que ce n'est pas prévu (pour le moment).

a+

**Comment by augras** [comment]
Merci pour la réponse rapide.
Oups ! ça c'est plutôt gênant : par définition une personne en congés maladie n'est pas là et ne peut pas saisir son congé. Il n'y a que la maladie dans ce cas à priori et on peut peut-être le passer du côté des absenses : il n'y a pas besoin de validation, c'est l'arrêt de travail qui valide ! Mais pour les enfants malade on n'est généralement pas là non plus et pas automatique.
Qui valide les congés exceptionnels ? Le responsable, un profil RH ?
Philippe

**Comment by wouldsmina** [comment]
oui, ce serait bien utile...
>Qui valide les congés exceptionnels ? Le responsable, un profil RH ?

le responsable et le RH peuvent tout les 2 valider.

**Comment by augras** [comment]
Bon, si les deux peuvent valider on devrait s'en sortir !
Merci,
Philippe

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
