### ISSUE TITLE
Gestion des heures supp

### ISSUE THREAD

**Issue by aradrim49** [libertempo/web#375]
Bonjour,

La gestion des heures de récup est un un sujet important dans notre entreprise. Nous avons une activité très saisonnière. Nous pouvons cumuler énormément d'heures au printemps pour des récupérations à l'automne et l'hiver. 
La nouvelle version de Libertempo permet de gérer ces heures et c'est un merveille :). Mais dans notre fonctionnement, nous avons un problème. Serait il possible que les heures de récup soit uniquement saisissables par un responsable et/ou rh ? 
En effet, le personnel a bien accès à l'informatique mais nous ne pouvons pas nous permettre que chaque personne vienne déposer ses heures supplémentaires dans Libertempo après une journée de travaille. Si cela pouvait être fait uniquement pour le responsable ça serait juste parfait dans notre cas.  

A très vite.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
