### ISSUE TITLE
Sous-Groupe

### ISSUE THREAD

**Issue by lolito34** [libertempo/web#376]
Bonjour,

Après avoir cherché un peu, il ne me semble pas avoir trouver de demandes équivalentes. J'ai vu pas al de sujets traitant des groupes mais pas dans le sens que ...., je m'explique

Nous aurions besoin de pouvoir créer des sous-groupes pour coller au mieux à notre organisation.Je m'explique :

Le besoin se fait surtout sur l'affichage du calendrier ou il faudrait que chaque membre puisse avoir une vue sur le groupe et/ou sur les autres sous-groupes. Si un membre d'un sous-groupe peut voir l'ensemble du groupe, il ne peut cependant pas voir les membres des autres groupes (sauf pour le rôle HR et administrateur). Ce serait d'autant plus intéressant pour les responsables d'avoir une vue plus synthétique que de voir l'ensemble du groupe.

Après, dans l'état actuel de l'application, on peut se débrouiller (et c'est déjà très bien) mais si on pouvait avoir ce genre d'affichage, ça serait top. J'ai conscience aussi qu'en mettant une demande comme celle-là cela peut faire un peu 'lettre au père noël' mais peut-être que cela peut servir au final.

D'avance merci (et encore bravo pour votre travail)

**Comment by Prytoegrian** [comment]
Je t'avoue que même en me laissant quelques jours pour digérer le besoin, je saisis toujours pas le but et les implications. @wouldsmina ?

**Comment by wouldsmina** [comment]
si je comprend bien, tu souhaites permettre aux employés d'un groupe de consulter d'autres groupes (les sous-groupes). Mais je ne comprends, malgré tout, pas le besoin. un exemple plus concret nous permettrait peut être de mieux comprendre...

**Comment by lolito34** [comment]
Ok je vais tenter de donner un exemple concret pour mieux me faire comprendre :
Actuellement sur mon lieu de travail (une université), nous sommes répartis dans différents services qui eux-mêmes sont divisés en composantes.

Exemple : Mon service :
	- composante 1
	- composante 2
	- composante 3
	- etc....

L'idée serait que chaque composante soit dans un sous-groupe séparé mais visible des autres sous-groupes. Chaque composante a son responsable qui eux-même ont comme responsable le responsable du services,

Chaque responsable a besoin d'avoir une vue d'ensemble sur sa composante. En gros, Il faudrait qu'ils puissent voir l'ensemble du service dans le calendrier mais aussi d'avoir une vue sur sa composante en particulier,

Comme nous restons un seul et même services, l'ensemble des employés d'un service doit pouvoir voir les absences des autres employés du même service quelque soit sa composante.
Par contre, un employé ne doit  pas voir le calendrier d'un autre service.

Jusqu'à présent, nous n'utilisions Libertempo que pour notre service et nous avions répartis les composantes dans des groupes distincts, ce qui nous convenait parfaitement. Sauf que nous aimerions étendre la solution à d'autres services qui fonctionnent de la même manière que nous (service/composantes).

Je teste avec la version actuelle le fait de répartir chaque service dans un groupe et d'attribuer un responsable pour chaque employés. Cela fonctionne assez bien mais cela serait mieux d'avoir une vue plus fine au niveau du calendrier.

J'espère avoir été un peu plus clair ce coup-ci :)

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons *réellement* envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
