### ISSUE TITLE
Calendrier, conservation de la période lors d'une nouvelle recherche par groupe

### ISSUE THREAD

**Issue by tneullas** [libertempo/web#378]
C'est plus une amélioration qu'un bug.

* Prérequis : Aller sur le calendrier en tant que responsable, reculer de 2 mois par exemple
* Action de déclenchement : Faire une recherche sur un groupe en particulier
* Résultat attendu : On s'attend à ce que ça filtre tous les membres qui ne sont pas de se groupe et de rester sur cette période d'il y a 2 mois
* Résultat constaté : La recherche est bien lancé sur le groupe sélectionné mais la période n'est pas prise en compte
* Piste pour correction : c'est probablement lié à l'url qui est défini dès le début et ne prend pas en compte la période.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
