### ISSUE TITLE
Prise de congés pour une date passée malgré l'option "interdit_saisie_periode_date_passee"

### ISSUE THREAD

**Issue by tneullas** [libertempo/web#383]
[Bug] Interdiction de prendre des congés pour une date passée facilement outrepassable

### Système et application

* Version de l'application : 1.9
    
### Reproduction du bug

* Prérequis : En tant qu'admin cocher "interdit_saisie_periode_date_passee" à TRUE dans la configuration
* Action de déclenchement : Essayer de prendre un congés à une date passée
* Résultat attendu : On s'attends à ce que ça affiche un message d'erreur
* Résultat constaté : Ca fonctionne
Il faut noter que le calendrier ne permet pas d'avoir accès aux dates passées.
Cependant on peut quand même remplir le champ de date avec des dates passées sans problème.

On s'attends à ce qu'un message soit affiché après un test JS et aussi un test en PHP lors de la validation.

**Comment by Prytoegrian** [comment]
Tu ne sembles pas le préciser, c'est valable pour tous les utilisateurs ?

**Comment by tneullas** [comment]
Bonne question, après tests :
* chez l'utilisateur normal le calendrier ne propose pas les dates passées mais on peut quand même remplir la date à la main
* chez le responsable, le calendrier n'est même pas affiché et on peut rentrer des dates à la main
* chez le rh, le calendrier s'affiche et propose les dates passées, on peut aussi les remplir à la main
