### ISSUE TITLE
User token n'est plus valide avec les jeux de données sql

### ISSUE THREAD

**Issue by tneullas** [libertempo/web#408]
Je pense que depuis #370 il y a un ou deux nouveaux champs à user.
Il faudrait mettre à jour le fichier jeu_de_test.sql pour tenir compte de ce changement car lorsque j'essaye d'inserer le jeu de test j'ai une erreur SQL sur la table conges_user.

**Comment by wouldsmina** [comment]
tout a fait, j'ai constaté ça hier en testant #382... ;)

**Comment by Prytoegrian** [comment]
Je propose un script de mise à jour des schemas / données de `jeu_de_test.sql`, que nous utiliserons à un instant clé du processus de livraison et qui s'appuierai sur les patchs habituels. Nous devons avoir une action pérenne, ce problème est appelé à revenir sinon.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
