### ISSUE TITLE
Exporter en pdf  l'historique des congés de tous les collaborateurs

### ISSUE THREAD

**Issue by legwoju** [libertempo/web#415]
Bonjour,

Pouvez vous ajouter la possibilité à un manager/responsable RH d'extraire les congés de tous les collaborateurs en pdf pour un mois donné.
Le but est de pouvoir faire signer le solde de congés/rtt à la fin de chaque mois.

Actuellement, il est nécessaire d'aller sur chaque collaborateur, cliquer sur Edition Papier puis Editer un pdf.

Merci d'avance
Julien

**Comment by teger** [comment]
Bonjour,

Un peu dans la même idée mais faire un rapport mensuel des congés pris pour chaque utilisateur dans le mois sélectionné. Ce fichier pourra etre fourni à la comptabilité pour mettre à jour le solde des congés.


Merci d'avance,

**Comment by LRCorwin** [comment]
Bonjour,

j'adhère à ces demandes (l'une ou l'autre solution me conviendra, mais un a priori plus positif sur la demande de @legwoju ).

merci

**Comment by Lolaru84** [comment]
Bonjour,

Idem, ou avec un choix de date à date, si possible avoir le choix de l'état des demandes (validées/échues ou validées/en cours ; non validées) export en csv serait aussi un plus.

**Comment by Prytoegrian** [comment]
Doublon #40. Pour autant, je vais fermer l'autre, celui-ci a plus d'échange.

**Comment by Lolaru84** [comment]
Avec la mise en production de LT au sein de notre organisation, cette fonctionnalité va devenir "cruciale", en effet les RH ont le devoir de réaliser un bilan social chaque année et pour ce faire, ils opnt besoin d'avoir ce type de rapport. Le but de cette remarque étant de voir si d'autres rebondissent sur la question du bilan social.

Merci de votre travail.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
