### ISSUE TITLE
LDAP + Utilisateur LOCAL (pour export congés globaux automatique)

### ISSUE THREAD

**Issue by Lulu09320** [libertempo/web#421]
Bonjour, 

Je vous soumet ma problématique, n'ayant pas trouvé de solution à la problématique que l'on vient de me confier. J'explique :

L'entreprise souhaiterais que l'agent en charge de l'accueil / standard téléphonique de l'entreprise ait une vision des congés de l'intégralité du personnel (afin de savoir à l'avance si une personne est présente ou non lors d'un appel téléphonique par exemple).

Libertempo est actuellement en production dans notre entreprise, et il est relié au LDAP pour la gestion des utilisateurs. L'intégralité des utilisateurs s'authentifient donc au travers de cet LDAP. 

Notre idée était de faire un compte générique LOCAL sur Libertempo permettant de faire cela. Seulement, on ne peut visiblement pas mixer de comptes LDAP / Locaux.
A savoir, nous n'avons pas l'accord ni la main pour créer un compte LDAP générique (décision "politique"), dans la mesure ou le personnel d'accueil change fréquement (intérim, remplacements, ...). cette solution n'est donc pas envisageable.

Une fonctionnalité telle qu'un envoie automatique par mail d'un récapitulatif global des congés posés par l'ensemble des agents pourrait solutionner notre problème. Ou alors la possibilité de faire un compte utilisateur hors LDAP spécifique à ce fonctionnement.

Je suis preneur de toutes autres pistes pour arriver à mes fins.

En vous remerciant,

**Comment by wouldsmina** [comment]
Bonjour,
En d'autre terme, tu souhaiterais permettre à un utilisateur de tout voir (en lecture seule). Cela reviendrait a créer un nouveau profil (employés/responsable/RH/consultation?), mais je pense qu'on le fera pas...
Est ce qu'un export au format ics pourrait convenir?

**Comment by Lulu09320** [comment]
Bonjour,
Merci à toi de prendre un peu de ton temps pour répondre à ma requête,
Effectivement, l'idée est que cet agent d'accueil ait un accès consultation en lecture seule uniquement. La personne en charge de l'accueil ne doit pas avoir de compte sur le LDAP (choix politique... les intérimaires n'ont pas de compte LDAP...). D'où l'idée du compte local au serveur dédié à la consultation.
Un export ICS peut faire l'affaire... A voir comment il est possible d'automatiser l'export de celui-ci.

Merci

**Comment by wouldsmina** [comment]
l'export ics, dans l'état actuel, permet d'avoir, à travers une url, une vue sur 12 mois glissant  pour un employé. Pour ton besoin, il faudrait que le RH puissent avoir une url unique pour avoir tous les employés...
Essaye avec un employé et dit nous si ça te convient, on passera le ticket en demande d'évolution de la fonctionnalité "export ics".

**Comment by Lulu09320** [comment]
Cet export peut-être une solution, en automatisant le téléchargement d'un fichier ics global à tous les employés sur un serveur par exemple. De cette façon, il sera possible -je pense- de faire une tache pour importer automatiquement ce fichier dans un logiciel type outlook. 
Cela me parait faisable non et répondrait au besoin puisque l'agent d'accueil aura les infos nécessaires sur son logiciel de messagerie par exemple, et ce sans authentification (j'ai cru remarquer que l'URL est accessible sans authentification, je me posais juste la question de si cette URL est toujours identique pour tous les utilisateurs ? 
Je veux bien que tu bascules le ticket en demande d'évolution de cette fonctionnalité
Merci

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
