### ISSUE TITLE
Modification mail sender

### ISSUE THREAD

**Issue by suskemolyon** [libertempo/web#435]
Bonjour,

Est-il possible de modifier le mail sender (adresse du FROM) par une adresse fixe et pas celle de l'utilisateur lors de notifications ?

En effet, j'ai installé la solution Libertempo pour la gestion des congés et j'utilise le serveur mail de l'entreprise dans la configuration SMTP.
Le responsable a son adresse professionnelle renseignée pour recevoir les demandes et envoyer les validations/refus. --> pas de problème
Les utilisateurs ont leur adresse privée (@gmail.com, @hotmail.com, ...) renseignée pour recevoir les validation du responsable. --> par défaut, le serveur Libertempo forge l'adresse du sender à l'adresse privée de l'utilisateur et le responsable du serveur mail de mon entreprise y voit un problème de sécurité (type fishing).

[Question]

**Comment by Prytoegrian** [comment]
En effet, ce serait probablement une bonne approche. Une adresse `no-reply@libertempo` irait ?

**Comment by suskemolyon** [comment]
Je préférerais pouvoir la choisir.

ex: dans un tool PHP que j'ai développé qui utilise PHPMailer
...
$from = 'no-reply@mondomain.ch';
$fromName = 'Objet du mail'; // ou utiliser la variable de la notification
$mail->SetFrom($from, $fromName);
...

**Comment by Prytoegrian** [comment]
Peut-on s'appuyer sur l'URL de l'instance ?
autrement dit, si tu as "http://lt.mondomaine.tld", que le mail soit "no-reply@mondomaine.tld" automatiquement ?

**Comment by suskemolyon** [comment]
Ça ne fonctionnerait pas comme désiré car mon serveur est local :
http://hostname/Libertempo
Et l'adresse mail du sender doit être de type noreply@mondomaine.xxx pour
être acceptée par l'administrateur du serveur/relai SNMP.

Pas possible d'ajouter le mail sender comme paramètre du fichier de
configuration comme toutes autres données relatives au mailing ?


Le 22 sept. 2017 7:01 PM, "Prytoegrian" <notifications@github.com> a écrit :

Peut-on s'appuyer sur l'URL de l'instance ?
autrement dit, si tu as "http://lt.mondomaine.tld", que le mail soit "
no-reply@mondomaine.tld" automatiquement ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Libertempo/Libertempo-web/issues/435#issuecomment-331503377>,
or mute the thread

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
