### ISSUE TITLE
Pas de mail au reponsable pour l'échange de jour

### ISSUE THREAD

**Issue by ghost** [libertempo/web#46]
Bonjour, 
lorsqu'un utilisateur fait un échange de jours congés (ex : modif de jours d'absence de temps partiel de la semaine), le responsable ne reçoit pas de mail pour qu'il valide ou au moins, soit prévenu.
Est-ce normal ?
Si cette fonctionnalité n'existe pas, est-ce qu'elle pourrait être implanté, au moins en option ?
Merci

**Comment by Prytoegrian** [comment]
Décidément, t'es en forme ^^

**Comment by VV666** [comment]
Je ne fais que de rapporter les problèmes rencontrés par les utilisateurs ... ^^

**Comment by wouldsmina** [comment]
C'est une bonne idée. Je l'ai fait pour les absences non soumis a validation...

**Comment by wouldsmina** [comment]
finalement, ce ne sera pas aussi simple que pour les absences. Les échanges de RTT ne sont pas stockés dans la table `periodes`; mais les mails sont généré à partir de cette dernière. 
La demande n'est pas recalé mais elle ne sera pas disponible en 1.7.1...

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
