### ISSUE TITLE
Login sensible à la casse

### ISSUE THREAD

**Issue by exyl** [libertempo/web#484]
Bonjour à la team,

On vient de me faire remonter que le champ login est sensible à la casse.
Un de mes utilisateurs a son compte avec des majuscules dedans, ex : JSmith
Et jsmith ne marche pas.
Je ne sais pas si vous le saviez (qu'il est sensible à la casse).
En général, le champ login ne l'est pas.

**Comment by wouldsmina** [comment]
Salut,
C'est vrai que d'habitude c'est pas sensible à la casse, mais est ce vraiment un problème qu'il le soit? perso ça me choc pas mais si cela gêne vraiment les utilisateurs, on peut rectifier ça (mais c'est pas une priorité).

**Comment by prytoegrian** [comment]
Doublon de #259.
