### ISSUE TITLE
Lisibilité du calendrier

### ISSUE THREAD

**Issue by Nulos** [libertempo/web#488]
Bonjour,

J'ai effectué une MAJ de LiberTempo de 1.8.1 à 1.9.4.
Notre RH me remonte que le calendrier est beaucoup moins lisible que sur la 1.8.1, surtout pour pointer et voir qui est en congés.
Est-ce possible de retourner sur l'ancien affichage en liste?

D'avance merci de votre réponse.

**Comment by Prytoegrian** [comment]
Hello,

nombreuses critiques ont relevé ce fait. L'étude que nous avions menée n'était pas complète, et nous avons pris une direction avec des informations manquantes. Du coup, on a repris [notre copie](https://github.com/Libertempo/Libertempo-web/pull/416) pour la 1.10.

Le bon côté des choses, c'est que cette version est actuellement en [phase de beta](http://libertempo.tuxfamily.org/kantra-beta/), donc je te laisse essayer cette version dans un bac à sable pour nous dire si ça vous rend un meilleur service. 
Habituellement, nos beta durent un mois, durant lequel on corrige les bugs que notre QA a laissé passer.

**Comment by LRCorwin** [comment]
concernant cet affichage, beaucoup plus sympa, beau travail les codeurs :)

quelques remarques : 
1/ on n'a plus la légende (codes couleurs par rapport aux types de jours posés) ?
2/ je ne vois pas les jours et demi-journées "off" : normal ?
3/ est-ce qu'il serait possible de classer les users par ordre alphabétique ?
4/ est-il possible de récupérer une fonction "printing" de ce calendrier ?

**Comment by Prytoegrian** [comment]
1. Je voulais ne pas surcharger l'interface. Donc pour bien comprendre le besoin, je prends la main et je lance les dés : quelle information te manque-t-il dans le code couleur et l'info bulle  ?
2. Tu parles du fait d'avoir pris qu'une demi-journée ?
3. #483 #491 Je suis sur le pont
4. Aucune difficulté là dedans. Comme toujours, j'ai besoin de bien comprendre le besoin pour vérifier que la solution technique est bien la plus adaptée. Le but est de vous offrir le meilleur service après tout.

**Comment by LRCorwin** [comment]
hello 
alors, dans l'ordre : 
1/ le tableau légende permet aux néophytes (et aux responsables) de vite prendre conscience des différentes types d'absence dans un planning, surtout s'il est imprimé pour être affiché dans un service. L'info-bulle doit ramener le libellé du type de congé (là, c'est ok) et éventuellement le commentaire posé par le user (si possible, hein, c'est une demande de mes utilisateurs).
2/ nope. Actuellement, sur la bétâ, j'ai affecté plusieurs planning à des agents : certains bossent en semaine pleine, certains ont des RTT et d'autres des temps partiels. L'affichage du calendrier ne me montre rien de tel, juste les cases des congés posés/validés.
3/ ok, nickel :)
4/ ici, on se sert du calendrier imprimé pour affichage dans certains services. On voudrait récupérer "juste" l'info utile : les utilisateurs, nom du mois, numéro de semaine, du jour, codes couleurs des jours d'absence (posés, validés). Basique :)

**Comment by wouldsmina** [comment]
> certains bossent en semaine pleine, certains ont des RTT et d'autres des temps partiels

Je confirmes, on ne voit pas les demi journées non travaillé.

**Comment by JEPlevallois** [comment]
Je rejoins @LRCorwin sur le besoin métier de voir en grisé les jours et demie-journées non travaillées par agent.
En ce qui me concerne le besoin est le suivant : 
- structure ouverte 7/7j avec un roulement entre les agents
- agents à temps partiels (et variété parmi les fractions de TP)
- alternance semaine courte 4j, semaine longue 6j

Avec le fonctionnement actuel, un agent à mi-temps en semaine courte qui ne travaille que 2j (ou 4 demies-journées) se retrouve avec 7 cases blanches dans le calendrier puisque j'ai paramétré que ma structure était ouverte le samedi et le dimanche.

De là, impossible d'estimer le nombre de présents.

Je précise que je suis pour l'instant en phase de test sur la démo en ligne avant d'envisager le déploiement ; ceci est clairement un frein majeur.

D'avance merci pour vos retours !

**Comment by wouldsmina** [comment]
Merci pour toutes ces remarques. Tout cela va nécessiter beaucoup de travail, nous allons donc passer Kantra en version stable et nous proposerons ces fonctionnalités dés que nous le pourrons.

**Comment by wouldsmina** [comment]
[commentaire à prendre en compte](https://github.com/Libertempo/Libertempo-web/issues/513#issuecomment-339234994)

**Comment by ebrenas** [comment]
Bonjour,

et d'abord un grand merci pour ce super boulot :-)

Sur le calendrier, ok pour que ça ouvre par défaut que sur le grope de l'utilisateur. Mais prenons le cas de l'agent qui est à l'accueil et qui répond au téléphone: il ou elle a besoin de savoir qui est là ou non. Pareil pour des agents d'entretien qui doivent intervenir dans des bureaux, etc...

Donc une petite case à cocher pour autoriser l'accès à tout le calendrier pour un user serait top.

Merci !

**Comment by Nulos** [comment]
Je reviens vers vous pour l'affichage du calendrier.
Je viens de mettre à jour vers la version 1.10.1 stable pour bénéficier du nouvel affichage.

Le responsable / RH / Admin ne voient pas le type de congés dans le calendrier. De plus est-ce possible de trier par nom et non pas par prénom? 

Encore merci pour le travail fait!

**Comment by wouldsmina** [comment]
@Nulos la version 1.10.1 ne fait que corriger un bug d'authentification. Pour le calendrier, il faudra attendre la version 1.11
a+

**Comment by prytoegrian** [comment]
Ce ticket est relatif à la 1.9, je clos donc. Si un vrai besoin émerge vis à vis des échanges que nous avons eu, n'hésitez pas à créer un nouveau ticket sur https://feedback.libertempo.fr/ pour que nous puissions en débattre et le prioriser.
