### ISSUE TITLE
suppression type absence

### ISSUE THREAD

**Issue by regis** [libertempo/web#539]
Le 28/11/2017 22:47, wouldsmina wrote:

> après vérification dans le code source, il s'avère qu'il ne faut aucune 
> absence sur le type à supprimer, quel que soit son statut.

Bonjour,

Est-il possible de prévoir la suppression ou la création d'un flag (en service ou non) d'un type d'absence ?

Merci

Régis

**Comment by prytoegrian** [comment]
Je ne suis pas sûr de comprendre de quoi il retourne. Est-ce en relation avec https://github.com/libertempo/web/pull/714 ?

**Comment by wouldsmina** [comment]
non, au contraire, cela s'applique aux types non natif. Actuellement, il est impossible de supprimer un type d'absence à partir du moment ou il a eu au moins une demande, quel que soit son statut. Cela est nécessaire pour maintenir une cohérence dans l'historique des congés, il n'est donc pas envisageable de supprimer les congés de ce type. 
La solution restante est de permettre de désactiver un type de congés. Cette solution pourrait être accompagnée du retrait de l'option globale "conges_exceptionnel"...

**Comment by prytoegrian** [comment]
Ça marche, je mets en forme et je le rédige sur feedback.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
