### ISSUE TITLE
Ne pas montrer le calendrier : Une bonne option !

### ISSUE THREAD

**Issue by Tera-Two** [libertempo/web#560]
Bonjour,

Je sais que la question a déjà été abordée (#385 et #391) mais l'option permettant de choisir ou non d'afficher le bouton calendrier a été retirée des options de configuration.
Chez nous, c'était indispensable.
Pour éviter que chacun ne réclame à avoir des congés tel ou tel jour alors que son collègue a obtenu les congés demandés.
Certes, je comprends que dans certaines structures, ce calendrier soit utile voire indispensable mais chez nous, il est néfaste et je me suis heurté à un refus de la direction et des RH lorsqu'ils ont constaté que l'option avait disparu...
Alors, je pose la question sans état d'âme : Que pensez-vous de remettre cette option permettant de choisir d'afficher le bouton calendrier ?

**Comment by Prytoegrian** [comment]
Hello et merci de ne pas lâcher l'affaire, 

pour bien comprendre le besoin, j'ai besoin de cerner vos pratiques. Comment un responsable ferait pour choisir telle ou telle absence s'il ne peut voir le contexte ?

**Comment by Tera-Two** [comment]
En réalité, l'utilisation de Php_conges-Libertempo, en ce qui nous concerne, est primordiale pour  : 
- le flux de validation des demandes (demande du salarié, validation du responsable...) assorti de la traçabilité des demandes par mail ainsi que dans l'historique de chaque salarié
- la tenue du compteur des jours totaux/restants pour les congés et les RTT.
Seuls les salariés non cadres font leurs demandes de congés dans Php_conges-Libertempo. 
Les cadres, eux, ne sont pas gérés dans Php_conges-Libertempo. Ils bénéficient d'un forfait de jours de travail par an et établissent un planning prévisionnel annuel (sur tableur) sur lequel ils précisent les jours de travail et les jours non travaillés. 
Les responsables ne peuvent donc pas se "contenter" des seules informations de Libertempo pour valider les demandes.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
