### ISSUE TITLE
Mise à jour du compteur traitement congés 

### ISSUE THREAD

**Issue by oooforum** [libertempo/web#581]
Depuis la page "Responsable" > onglet "Traitement congés". 
Après une validation d'un congé, le compteur mentionné sur l'onglet ne se décrémente pas.

**Comment by wouldsmina** [comment]
Bonjour,
la structure du code ne nous permet pas d'obtenir cette fonctionnalité... pour le moment 
Dans la prochaine version, les onglets n'existerons plus, les différentes vues seront accessible depuis la barre verticale (à gauche), les compteurs reviendront plus tard sous une forme dynamique.

**Comment by prytoegrian** [comment]
L'absence de formatage du ticket rend impossible son traitement, notamment le fait qu'il n'y ai pas de version installée. Je ferme donc, puisqu'on ne peut rien faire.
N'hésitez pas à rouvrir s'il y a de nouvelles infos.
