### ISSUE TITLE
Impossible de retrancher des jours

### ISSUE THREAD

**Issue by oooforum** [libertempo/web#589]
On peut avoir besoin de retrancher des jours de congés/RTT.
Je ne vois pas cette possibilité.

**Comment by wouldsmina** [comment]
retrancher? c'est a dire?

**Comment by oooforum** [comment]
Par défaut, en début d'année, nous avons un nombre de RTT.
Il peut être diminué si l'année précédente, la personne a eu des jours de maladie.
Or, cette info n'est fournie par le service RH que fin janvier.
Il faut donc pouvoir retrancher le total de RTT.
Espérant avoir été plus clair.

----- Mail original -----

**Comment by wouldsmina** [comment]
oui, c'est beaucoup plus clair, merci. En effet cette fonctionnalité n'existe pas. Je ne crois pas que nous ayons déjà abordé cette problématique.

Comment vois tu cela concrètement? Le RH calcule puis retranche au besoin? ou cela devrait ce faire automatiquement?

**Comment by oooforum** [comment]
Je ne pense qu'un automatisme soit possible.
Les règles de calcul de RTT peuvent changer d'une entreprise à l'autre.
Comme pour l'ajout de congés, un responsable doit pouvoir faire l'opération inverse.


----- Mail original -----

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
