### ISSUE TITLE
Perte de fonctionnalités : calendrier, vue calendrier global

### ISSUE THREAD

**Issue by kaioh31** [libertempo/web#609]
Bonjour,

Je viens de mettre à jour ma version Quinnis 1.8.1 par la version Kantra 1.10.

Deux choses m'ont dérangé :

**Restriction de vue du calendrier**
Dans mon entreprise il n'y a pas de tabou sur les dates de congés des uns ou des autres. C'est d'ailleurs important que chaque employé puisse voir si une personne est absente ou non. Depuis la version 1.10, on ne voit les congés que de l'équipe dans laquelle on se trouve et on ne voit pas non plus les congés du responsable de son équipe.
J'ai réalisé les modifications proposées pour le responsable du groupe dans le #568, mais cela ne solutionne mon problème qu'en partie.

**Légende sur le calendrier**
Il n'est désormais plus possible de savoir le type des congés sur le calendrier. la couleur est identique pour tous les congés avec un léger niveau de transparence pour les congés en attente de validation.
En version 1.8.1 il y avait  :
- une différence visuelle entre les trois types de congés : "congés", "absences" et "congés sans solde"
- le libellé exacte du congé dans la fenêtre accessible en surbrillance de la zone
Ces deux distinctions ont disparu, le plus dommage étant que le libellé indique toujours "congés", quelque soit le type de congés.

Je ne sais pas si on vous avait remonté l'ensemble alors je me permets ...

Je vous remercie par avance.

Thierry Lamoureux.

**Comment by wouldsmina** [comment]
bonjour,

> Depuis la version 1.10, on ne voit les congés que de l'équipe dans laquelle on se trouve et on ne voit pas non plus les congés du responsable de son équipe.

nous préférons maintenir quelques limites de confidentialité mais tu peux créer un groupe sans responsable avec tous les employés.

> J'ai réalisé les modifications proposées pour le responsable du groupe dans le #568, mais cela ne solutionne mon problème qu'en partie.

Patience :smile: #568 doit être testé avant d’être inclus dans une future version. 

> Il n'est désormais plus possible de savoir le type des congés sur le calendrier. la couleur est identique pour tous les congés avec un léger niveau de transparence pour les congés en attente de validation.

ces informations sont personnelles, les employés n'ont pas besoin de savoir pourquoi un collègue est absent. En ce qui concerne les responsables, c'est discutable... il y a un ticket à ce sujet mais je n'arrive pas à remettre la main dessus, désolé.

Merci pour ton retour d'expérience. Je t'invite, à l'avenir, à créer un ticket par sujet, ça nous permet de mieux gérer les demandes.

**Comment by kaioh31** [comment]
Bonjour,

Je te remercie de cette réponse. En effet, il serait important dans notre cas que les responsable puissent identifier sur les planning les types d'absences. La gestion d'une absence de type formation n'est pas du tout la même que pour un CP et la vue planning est la seule synthèse qui existe dans l'application.

Merci par avance.

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
