### ISSUE TITLE
PB affichage plannig 

### ISSUE THREAD

**Issue by ocinlas** [libertempo/web#622]
tous les mois s'affiche correctement sauf fevrier 2018 : 

![image](https://user-images.githubusercontent.com/37587184/38139289-1151b18a-342f-11e8-91b1-a15a8c3ed207.png)

bizare !!

**Comment by ocinlas** [comment]
![image](https://user-images.githubusercontent.com/37587184/38139311-2972d7bc-342f-11e8-9c0a-a553e540ff2e.png)

**Comment by ocinlas** [comment]
En fait pour fevrier il ne montre pas tous le monde ??

**Comment by wouldsmina** [comment]
des erreurs dans les logs apache? en fait, si tu pouvais remplir la partie Système et application lors de la création du ticket, ça nous aiderait pas mal.

**Comment by prytoegrian** [comment]
En fait il y a plein de défauts dans ce ticket, le plus important est le fait qu'il n'y a pas la version installée. Sans plus de nouvelles, comme on ne peut pas corriger, je ferme. N'hésitez pas à rouvrir.
