### ISSUE TITLE
Customize logo & app name

### ISSUE THREAD

**Issue by benrubson** [libertempo/web#625]
Hi,

Would be nice to be able to customize the logo, so that we can use for example the company logo.
And as well to customize the application name.

Additionally, the application name could be used through a `__APPNAME__` variable in mail templates.

Thank you 👍 

Ben

**Comment by wouldsmina** [comment]
why not. But for now it's not a priority.

**Comment by prytoegrian** [comment]
Hi. As @wouldsmina said, it's not priority for us. If you want to give it a try though, you will have to `insert into conges_config` for pointing to new logo files in the general configuration. I recommend to allow empty string as a fallback (actual case).
IMO, app name is already customisable. Where did you see hardcoded ?

**Comment by benrubson** [comment]
Hi, and thank you for your feedback.
I'm talking for example about pages' title (the one between `<title> </title>` tags).
Also for example about application title on login page, but for now it is a logo, so perhaps logo should be cut, and application name added as text so that it could be customized.
So a global "application title" / "application name" would make sense, also usable through a `__APPNAME__` var in mail templates.

> IMO, app name is already customisable.

Where ? I did not found the proper setting :)

Thank you 👍

**Comment by prytoegrian** [comment]
You're right, the title tag always shows « libertempo... », I totally forgot that.

First, my advice about inserting a new variable in configuration is still true.
Then, you'll have to track all `header_login()`, `header_popup()`, `header_error()`, `header_menu()` consumptions as theses functions are all responsibles for displaying title tag. I agree with your proposal, an « application name » would be cool and easy to use in them.
Last, for your customisation being full, don't forget `HR : Config > générale > 11 édition papier` and `HR : Config > mails`.
