### ISSUE TITLE
document deployment without .htaccess

### ISSUE THREAD

**Issue by benrubson** [libertempo/web#638]
Hi,

Would be nice to add to the documentation rules required by an Apache VirtualHost for a deployment without `.htaccess` file.
There is a performance hit enabling `.htaccess` files, as well as some security concerns.

Rewrite rules should ideally be given outside of `<Directory>` sections, so that an additional / unwanted `Options +FollowSymLinks` is not needed.

Thank you 👍 

Ben

**Comment by wouldsmina** [comment]
#662 merged

**Comment by benrubson** [comment]
@wouldsmina, thank you, but I'm not sure where this has been documented, could you tell me please ?
Thx 👍

**Comment by wouldsmina** [comment]
http://libertempo.tuxfamily.org/documentation/prerequis/
