### ISSUE TITLE
Affichage du calendrier : groupement

### ISSUE THREAD

**Issue by SomeoneElseIsHere** [libertempo/web#652]
Ne serait il pas intéressant de pouvoir grouper (optionnellement ?), dans le calendrier, les utilisateurs par groupe et/ou plannings ?

![calendrier trie groupe et plannings](https://user-images.githubusercontent.com/38921300/40049660-9f5cdf16-5835-11e8-8d81-d3149e925775.png)

**Comment by Prytoegrian** [comment]
Bonjour,

quel serait le besoin ?

La difficulté pour Libertempo est la possibilité qu'ont les employés d'être dans plusieurs groupes en même temps.

**Comment by SomeoneElseIsHere** [comment]
Cela permettrait pour un responsable de responsable (cas de la double validation) de voir rapidement les plannings des différents groupes/ plannings avant de valider ou non

**Comment by en3rgizz** [comment]
Par ailleurs pour compléter ton post serait t'il possible de différencié les rtt des congés avec des couleurs spécifique ?  ainsi qu'un export ? format pdf peut être.

**Comment by wouldsmina** [comment]
@en3rgizz il y a le ticket #488 à ce sujet. Les couleurs par type sont prévu dans une version futur.
a+
