### ISSUE TITLE
Gestion des périodes RTT / congés

### ISSUE THREAD

**Issue by ccadenel** [libertempo/web#66]
Comment sont géré les 2 périodes différentes d'applicaiton des RTT et des congés?

Les congés étant caclulés du 1 juin au 31 mai et étant acquis sur l'année précédente.

Les RTT étant acquis mois par mois et la période d'application est du 1er janvier au 31 décembre.

**Comment by wouldsmina** [comment]
Les RTT sont gérés par exercice (annualisé).

 La date de début (et la fin) d'un exercice n'est pas définie en dur, elle l'est à chaque changement d'exercice...

**Comment by yuntux** [comment]
Les RTT et les Congés Payés n'ont pas la même date d'exercice (31/12 pour les RTT et 31/05 pour les CP), ni les même règles de repport des reliquats (jusqu'à 5 jours repportables à consommer entre le 1/06 et le 31/12 de l'exercice suivant pour les CP alors qu'aucun repport n'est possible pour les RTT).

Or j'ai l'impression qu'il n'est pas possible de cloturer que les CP ou que les RTT.
De même les variables nb_maxi_jours_reliquats  et jour_mois_limite_reliquats s'appliquent à tous les congés alors qu'elles devraient dans l'idéale être paramétrées par type de congès.

**Comment by wouldsmina** [comment]
C'est que ce fonctionnement est monnaie courante en France. Je vais voir ce qu'on peut faire...

**Comment by lbaey** [comment]
+1 :)

**Comment by Prytoegrian** [comment]
Peut-être qu'on pourrait formaliser la forme d'un exercice, un peu à la manière d'un exercice fiscal.

Nous savons qu'un exercice de CP n'a ni les mêmes dates, ni les mêmes règles de gestion de report qu'un exercice d'une RTT. On pourrait alors contractualiser ça, en permettant au DRH de créer deux types d'exercices exprimant ça : 
* L'exercice de CP pourrait porter les jours de fermetures et le nombre de congés total ainsi que les éventuels règles de report. La quotité de chacun modulera le nombre de CP de chacun.
* L'exercice d'une RTT pourrait gérer, sur la base du volume horaire hebdo inscrit (voir plus loin) et les info du contrat de travail du collaborateur( 39h / 35h + RTT / 35h + heures sup reportables ou non), les règles de gestion à apporter : report, CET, etc.

Les autres types de congés / absences ne sont pas décomptés car non acquérables (il me semble), ils peuvent donc être traités de manière transverse.

Les jours chômés et les jours de travail (ouvrés / ouvrables) devront être traités ailleurs car ils sont communs aux deux types.

Ces exercices devront intégrer les collaborateurs qui suivent ces règles, donc soit les membres d'un groupe, soit la totalité des collaborateurs.


D'après ce que j'ai vu, on aurait qu'une adaptation mineure des exercices actuels pour avoir ce format ( à étudier).

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.
