### ISSUE TITLE
Corriger les défauts de sécurité trouvés par l'audit

### ISSUE THREAD

**Issue by prytoegrian** [libertempo/web#660]
Un audit nous a été transmis et ma stack technique ne me permet pas d'avancer sur le sujet pour le moment, je crée donc un ticket pour organiser la gestion de ça. Puisqu'il s'agit d'un enjeu de sécurité, je ne mets pas le rapport ici, les gens concernés l'ont déjà…

D'expérience, la première des choses est de s'assurer de la reproductibilité des défauts, pour ne pas chasser un fantôme. Ensuite, pour corriger ça, il faut dégainer du ZAP (cf. #284) et passer sur les éléments à la main, l'un après l'autre. C'est long et fastidieux, mais si on peut ajouter des tests automatisés à la volée, on pourra investir sur le long terme. La priorité reste les XSS, stockées comme réfléchis.

**Comment by wouldsmina** [comment]
J'ai ce qu'il faut! je m'y colle une fois Mondaran livré.

**Comment by wouldsmina** [comment]
j'ai fait quelque tests de hack basé sur les retours de l'audit, je n'ai pas réussi à trouver de faille. Cet audit se base sur le code source qui est parfois bien compliqué, il est possible que le script de contrôle n'ai pas été en mesure de tout... contrôler. Mais il est aussi possible que ce soit moi qui ai raté un truc!

**Comment by prytoegrian** [comment]
J'en suis venu à la même conclusion. Par acquis de conscience, on va quand même passer ZAP, mais on fermera derrière.

**Comment by prytoegrian** [comment]
Les derniers tests de ZAP ne remontent rien de dangereux, je ferme donc.
