### ISSUE TITLE
Annulation ou ajout de congés: perte des 0.5 jours

### ISSUE THREAD

**Issue by PascalBogaert** [libertempo/web#669]
En mode responsable, l'annulation de congés ou l'ajout ne prend pas en compte des demi journées. L'arrondi se fait toujours au jour entier.
![ajout_0 5jour_toto](https://user-images.githubusercontent.com/39997112/41044627-f4e40cfc-69a6-11e8-8673-5633b4986e1f.JPG)
![annul_demande](https://user-images.githubusercontent.com/39997112/41044639-faa69f42-69a6-11e8-9ad8-5f8e8f67c13d.JPG)

**Comment by prytoegrian** [comment]
Bonjour,

Peux-tu remplir le template de bug ? Sans information, nous n'allons pas pouvoir t'aider.
Merci.
