### ISSUE TITLE
Droits responsable

### ISSUE THREAD

**Issue by jptran** [libertempo/web#670]
Bonjour,
Juste une question : pourquoi un responsable ne peut pas être membre de son propre groupe dans la version kantra 1.10.2? Il y aurait-il possibilité de rendre cela optionnel..
Merci d'avance.

**Comment by wouldsmina** [comment]
Bonjour,

Le responsable ne peut faire parti de son propre groupe car : 
- il ne doit pas pouvoir traiter ses propres congés
- il est courant en entreprise que les responsables soit rattaché au service de leurs supérieur.

Pour bien faire, il faut intégrer les responsables dans un groupe spécifique. Les employés ont bien sur toujours la possibilité de consulter le calendrier de leurs responsables.

a+

**Comment by prytoegrian** [comment]
Pour moi, en terme de ressources humaines, c'est un non-sens. Quel est ton besoin ?
