### ISSUE TITLE
Samedi travaillé

### ISSUE THREAD

**Issue by droide02** [libertempo/web#676]
Nous activons le samedi travaillé et avons deux planning. Un du lundi au vendredi et un du mardi au samedi.
Lorsqu'un utilisateur qui est associé au planning "lundi au vendredi" pose un congé, il peux séléctionner le samedi dans l'agenda.

Comment faire pour qu'ils ne puissent pas le sélectionner ?

**Comment by prytoegrian** [comment]
Hello,

comme évoqué sur le chat, il y a une version simplissime : on pourrait faire en sorte de ne pas pouvoir poser un congé si la durée de prise n'est pas supérieure à 0. Ça implique de modifier un tantinet `fonction_calcul::compte` mais c'est une façon rapide de faire le job.

**Comment by droide02** [comment]
Hello,
le soucis est pour la personne qui va par exemple poser du jeudi au samedi...

**Comment by prytoegrian** [comment]
Oui, je vois ce que tu veux dire. De cette façon : 
- soit on part du principe que ça n'a pas d'importance, puisque le samedi sort une valeur nulle donc non créditée dans le calendrier,
- soit on met un vrai contrôle serveur (et son pendant client), mais ergonomiquement ça nous pose un autre problème : les utilisateurs ne pourront plus sélectionner « de mardi 3 à mardi 17 » directement, puisqu'il y aura des jours blancs à l'intérieur.

J'avoue que j'ai une nette préférence pour la version ergonomique. En plus d'être lourd pour l'employé, le responsable verra aussi plusieurs séquences de congés alors qu'il ne s'agissait que d'un long congé sur plusieurs semaines.
