### ISSUE TITLE
Upgrade 1.10 vers 1.11

### ISSUE THREAD

**Issue by suskemolyon** [libertempo/web#680]
Bonjour,

J'ai tenté de procéder à l'upgrade de la v1.10 vers v1.11

Cependant, j'ai l'erreur suivante après /install "continuer" :

> login : 
> uri   : /Libertempo/install/upgrade_from_v1.10.php?etape=2&version=1.11&lang=fr_FR
> dump  : ../dump/sql_2018-07-05T08:14:05+02:00.dump
> 
> file  : /home/serv-rp/www/Libertempo/includes/SQL.php
> line  : 86
> fx    : $SQL->query
> error : Can't DROP 'u_see_all'; check that column/key exists
> sql   : ALTER TABLE `conges_users` DROP `u_see_all`;

Après vérification dans la DB, effectivement, la colonne "u_see_all" n'existe pas dans ma table conges_users.

Pouvez-vous me fournir les infos "Type", "Collation", "Attributes", "Null" et "Default" pour que je puisse l'ajouter manuellement svp ?

Merci

**Comment by prytoegrian** [comment]
Hello, la réponse à ta question n'est pas complexe : `ALTER TABLE conges_users ADD u_see_all enum('Y', 'N') NOT NULL DEFAULT 'N`, mais en réalité, j'ai bien l'impression qu'il s'agit d'un bug de migration. #665 empêchera qu'à l'avenir ça arrive, mais en attendant, nous pouvons faire un patch correctif. Je peux te conseiller d'attendre ce dernier pour avoir l'assurance qu'il passe toute notre batterie de test, mais je ne peux rien t'imposer.

**Comment by suskemolyon** [comment]
Hello,
Merci pour la réponse, j'ai tout de même tenté l'update SQL mais après c'est la même erreur pour 'u_resp_login' qui se produit.
Après avoir adapter l'update pour ce champ, j'ai pu faire l'update mais il n'était plus possible de se loguer avec aucun utilisateur.
J'ai alors fait un rollback en 1.10 avec une restauration du backup de ma DB. Tout fonctionne comme avant update.
J'attends donc votre patch correctif, merci d'avance pour votre job.

**Comment by wouldsmina** [comment]
Bonjour @suskemolyon,

> Après avoir adapter l'update pour ce champ, j'ai pu faire l'update mais il n'était plus possible de se loguer avec aucun utilisateur.

Il est fort probable que ce problème soit lié à ta configuration d'apache, #682 te permettra de comprendre et corriger ce problème

a+
