### ISSUE TITLE
Pas de calcul du solde de congés lors de la saisie de nouveau congés

### ISSUE THREAD

**Issue by plorin** [libertempo/web#683]
Description et comment reproduire :
L'application ne calcule pas le solde de congés : un utilisateur saisi une demande de congés. Le solde de congés ne bouge pas (n'y a-t-il pas normalement un calcul qui met à jour le nombre de jours de congés restants ?) D'ailleurs la zone "Nombre de jours" (en dessous des dates de début et date de fin) reste à 0.
J'ai vu que sur la version de démo (v1.9), il y avait un bouton "Compter les jours" qui n'apparait pas dans la version 1.11.

**Comportement attendu**
Si l'utilisateur disposait de 10 jours de congés et en pose 2 (jeudi et vendredi = 2 jours), le solde de congés devrait être positionné sur 8 (10 - 2).

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] : Ubuntu Server 16.04 
 - Navigateur et version : chrome
 - Erreur dans la console : 

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] :Ubuntu Server 16.04 
 - Version de Libertempo : 1.11
 - Version MySQL et PHP :MYSQL 5.7.22 - PHP 7.0.30
 - Erreur dans le log du serveur : 

**Contexte additionnel**
sans objet

**Comment by wouldsmina** [comment]
Salut @plorin,

As tu bien paramétré le planning de l'utilisateur?

**Comment by plorin** [comment]
Merci,
J'avais créé et associé un planning à l'utilisateur mais sans horaires (qui ne me sont pas utiles dans mon cas). Après avoir ajouté des horaires dans le planning, cela semble fonctionner correctement.
Merci pour la réactivité.
