### ISSUE TITLE
labels "début de matinée"  et "début d'après-midi" paramétrables

### ISSUE THREAD

**Issue by ThierryLyon** [libertempo/web#684]
Bonjour

Est il possible de passer en paramétrage les deux labels "début de matinée"  et "début d'après-midi" quand on dépose un congé ?

Nous mettrions simplement "matin" et "après-midi"

Merci

**Comment by ClementNoury** [comment]
Bonjour, 

Je ne suis pas dans l'équipe de développement mais pour notre société j'ai remarqué que chez beaucoup d'utilisateurs c'était important cette précision car certains c'est la reprise d'autre l'absence à sélectionner au final cette précision ne fait pas de mal à mon gout.

**Comment by prytoegrian** [comment]
Hello. Je suis dans l'équipe de dev et nous avons déjà eu un débat à ce sujet et il nous est apparu que ces termes étaient les moins troublants pour guider les utilisateurs dans leurs actions et les conséquences derrière (notamment sur le calcul des jours).
Donc, nous ne changerons pas cet aspect puisque les raisons sont toujours pertinentes à notre sens. Par contre, tu as bien évidemment la liberté de *hacker* le logiciel pour le faire coller à ton besoin ; par contre, prends bien en compte la charge induite par la maintenance.

Quoiqu'il en soit, merci de ton investissement, chaque petite brique nous permet d'améliorer le logiciel.
