### ISSUE TITLE
Synchro date de fin en fonction de la date de début lors du dépot d'un congé

### ISSUE THREAD

**Issue by ThierryLyon** [libertempo/web#685]
Bonjour

Lors de la modification de la date de début lors d'un dépôt de congés, est il possible de synchroniser automatiquement la date de fin en fonction de la date de début saisie ?

quand on anticipe les congés cela évite de trop parcourir le calendrier une seconde fois pour la date de fin

Merci

**Comment by prytoegrian** [comment]
Absolument ! 
Ça fait longtemps que ça me démange. La version abouti de la fonctionnalité serait  : 
  - si la date de début est supérieure à la date de fin, le widget date de fin prend automatiquement la date de début,
  - si la date de fin est inférieure à la date de début, le widget date de début prend automatiquement la date de fin.

On ne parle ici que des widgets front, ce n'est bien évidemment pas à faire côté serveur.

**Comment by ThierryLyon** [comment]
Oui c'est tout à fait ça :-)

**Comment by Weirddo** [comment]
Hello,
Un bout de code qui fait le boulot pour cette demande remontée également par mes utilisateurs.
`var clickDeb=0

$('input.date[name="new_debut"]').on("change",function(){
    {
    clickDeb++;
    var debDate=$(this).val();
    if (clickDeb>1){
    $('input.date[name="new_fin"]').datepicker('setDate',debDate);
        }
    
    }
});`

**Comment by wouldsmina** [comment]
Salut @Weirddo, merci pour ta contribution. Peux tu nous faire un pull request stp? 
C'est plus simple à traiter pour nous et surtout tu sauvera une licorne d'une mort douloureuse :rofl:
