### ISSUE TITLE
Mise à jour 1.10 à 1.11 - Authentification LDAP impossible

### ISSUE THREAD

**Issue by Nulos** [libertempo/web#687]
Bonjour,

Je viens d'effectuer la MAJ de libertempo suivant ces étapes:
- décompression du fichier zip de libertempo version 1.11
- copie des dossier cfg et api dans le dossier web-1.11.0
- renommage du dossier de l'ancienne version www en www-1_10
- renommage du dossier de la nouvelle version web-1.11.0 en www
- ajout d'ACL pour l'écriture de l'utilisateur www-data: 
```
setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx api/
setfacl -R -m u:www-data:rwX -m u:`whoami`:rwX api/
setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx vendor/Libertempo/
setfacl -R -m u:www-data:rwX -m u:`whoami`:rwX vendor/Libertempo/
setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx backup/
setfacl -R -m u:www-data:rwX -m u:`whoami`:rwX backup/
setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx dump/
setfacl -R -m u:www-data:rwX -m u:`whoami`:rwX dump/
```
- Mise à jour de la BDD via l'url http://libertempo/install
Et après ça impossible de se connecter a libertempo, j'ai le message d'erreur suivant: Pas de session ouverte.
La connexion se fait normalement via LDAP.

D'avance merci de votre aide.

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] : Windows 10
 - Navigateur et version : Chrome Version 67.0.3396.99 (Build officiel) (64 bits) / Firefox 61.0.1 (64 bits) 
 - Erreur dans la console : Rien

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : Debian 8.11
 - Version de Libertempo : 1.11.0
 - Version MySQL et PHP : PHP 7.1.19 / MariaDB 10.1.20
 - Erreur dans le log du serveur : Rien

**Comment by wouldsmina** [comment]
Salut,

La configuration du serveur a changé sur mondaran, je t'invite a vérifier les prérequis sur la documentation : http://libertempo.tuxfamily.org/documentation/prerequis/

**Comment by Nulos** [comment]
Bonjour,
J'ai tous les prérequis mais ça ne fonctionne pas.

# dpkg -l |grep php
ii  libapache2-mod-php7.1                 7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php-common                            1:62+0~20180715031352.2+jessie~1.gbpcc3724                        all          Common files for PHP packages
ii  php-geoip                             1.1.1-1+0~20170825111212.1+jessie~1.gbp2bf964                     amd64        GeoIP module for PHP
ii  php-gettext                           1.0.12-0.1                                                        all          transitional dummy package for php-php-gettext
ii  php-igbinary                          2.0.6~rc1-1+0~20180719123827.1+jessie~1.gbp66b051                 amd64        igbinary PHP serializer
ii  php-memcached                         3.0.4+2.2.0-1+0~20180719130840.1+jessie~1.gbpf351eb               amd64        memcached extension module for PHP, uses libmemcached
ii  php-msgpack                           2.0.2+0.5.7-1+0~20180719123854.1+jessie~1.gbpa0678b               amd64        PHP extension for interfacing with MessagePack
ii  php-pear                              1:1.10.5+submodules+notgz-1+0~20170904061701.3+jessie~1.gbpe356ca all          PEAR Base System
ii  php-php-gettext                       1.0.12-0.1                                                        all          read gettext MO files directly, without requiring anything other than PHP
ii  php-redis                             4.0.0-1+0~20180719130919.1+jessie~1.gbp24a357                     amd64        PHP extension for interfacing with Redis
ii  php7.1                                7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.1-cli                            7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        command-line interpreter for the PHP scripting language
ii  php7.1-common                         7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        documentation, examples and common module for PHP
ii  php7.1-curl                           7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        CURL module for PHP
ii  php7.1-gd                             7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        GD module for PHP
ii  php7.1-gmp                            7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        GMP module for PHP
ii  php7.1-intl                           7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        Internationalisation module for PHP
ii  php7.1-json                           7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        JSON module for PHP
ii  php7.1-ldap                           7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        LDAP module for PHP
ii  php7.1-mbstring                       7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        MBSTRING module for PHP
ii  php7.1-mcrypt                         7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        libmcrypt module for PHP
ii  php7.1-mysql                          7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        MySQL module for PHP
ii  php7.1-opcache                        7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        Zend OpCache module for PHP
ii  php7.1-readline                       7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        readline module for PHP
ii  php7.1-soap                           7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        SOAP module for PHP
ii  php7.1-sqlite3                        7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        SQLite3 module for PHP
ii  php7.1-xml                            7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.1-zip                            7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68                    amd64        Zip module for PHP


De plus j'ai effectué une MAJ du serveur passage de debian 8.11 à 9.5 et la notre ancienne version de libertempo est passé en Anglais, malgré le fait que nous choisissons fr_FR en langue.
Et même après une regénération des locales:
# dpkg-reconfigure locales
Generating locales (this might take a while)...
  en_US.UTF-8... done
  fr_FR.ISO-8859-1... done
  fr_FR.UTF-8... done
  fr_FR.ISO-8859-15@euro... done
Generation complete.

Merci de votre aide.

**Comment by wouldsmina** [comment]
Tu utilises les .htaccess ou un vhost?
Si .htaccess, que ce passe t il lorsque tu modifie le fichier api/.htaccess en mettant une lettre au hasard dedans?

**Comment by Nulos** [comment]
Merci de ta réponse.
Voici mon vhost:

<IfModule mod_ssl.c>
<VirtualHost :443>
 ServerName 
 DocumentRoot /home/conges/www

    <Directory /home/conges/www>
	    Require all granted
        AllowOverride All
        Options -Indexes
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteBase /
        RewriteRule ^api/(.*)$ vendor/Libertempo/libertempo-api/Public/ [QSA,L]
    </Directory>

    <Directory /home/conges/www/vendor/Libertempo/libertempo-api>
        <Files "configuration.json">
            Order Allow,Deny
            Deny from all
        </Files>
    </Directory>

 CustomLog /home/conges/log/access.log combined
 ErrorLog /home/conges/log/error.log
SSLCertificateFile /etc/letsencrypt/live//fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live//privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>

**Comment by Nulos** [comment]
Voici l'erreur: 

  |  
-- | --
code | 400
status | "fail"
message | "Bad Request"
data | "Request Content-Type and Accept must be set on application/json only"

**Comment by wouldsmina** [comment]
Ok, c'est une réponse normale. Peux tu suivre ces instructions :
https://github.com/libertempo/web/issues/682#issuecomment-404151673

Et me donner l'erreur retournée. Merci.

**Comment by Nulos** [comment]
Ci-dessous tu trouveras ce que j'ai quand je me connecte avec l'utilisateur admin, car avec mon propre user (LDAP) qui est lui aussi admin ça ne marche pas:

→$e Exception(7)
contents Available methods (11)
protected message -> string UTF-8(30) "Noms d'utilisateurs différents"
private string -> string(0) ""
protected code -> integer0
→protected file -> string(44) "/home/conges/index.php"
protected line -> integer82
private trace -> array(0)
private previous -> NULL
→ Called from <ROOT>/index.php:87

**Comment by wouldsmina** [comment]
Ah oui, tu es sur ldap! Il faut ajouter ddd ici : Line 75 in file index.php at libertempo/web
https://github.com/libertempo/web/blob/master/index.php#L75
Désolé

**Comment by Nulos** [comment]
Bonjour,

Voici le retour:

→$e LogicException(7)
contents Available methods (11)
→protected message -> string(532) "Erreur client : Request -> GET /api/authentification HTTP/1.1 User-Agent: Guzzle…"
Erreur client : Request -> GET /api/authentification HTTP/1.1
User-Agent: GuzzleHttp/6.2.1 curl/7.52.1 PHP/7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68
Host: conges
Authorization: Basic dGF1cmlvbDpub25l
Content-Type: application/json
Accept: application/json

 | Response <- HTTP/1.1 404 Not Found
Date: Fri, 27 Jul 2018 12:10:33 GMT
Server: Apache
Content-Length: 91
Content-Type: application/json;charset=utf-8

{"code":404,"status":"error","message":"Not Found","data":"No user matches these criteria"}
private string -> string(0) ""
protected code -> integer0
→protected file -> string(62) "/home/conges/App/Libraries/ApiClient.php"
File (4,83K)
-rwxrwxrwx
protected line -> integer134
→private trace -> array(4)
→array(6)
→'file' => string(62) "/home/conges/App/Libraries/ApiClient.php"
File (4,83K)
-rwxrwxrwx
'line' => integer106
'function' => string(7) "request"
'class' => string(23) "App\Libraries\ApiClient"
'type' => string(2) "->"
→'args' => array(3)
→array(6)
→'file' => string(62) "/home/conges/App/Libraries/ApiClient.php"
File (4,83K)
-rwxrwxrwx
'line' => integer88
'function' => string(16) "authentifyCommon"
'class' => string(23) "App\Libraries\ApiClient"
'type' => string(2) "->"
→'args' => array(2)
string(7) "xxx"
string(4) "none"
→array(6)
→'file' => string(56) "/home/conges/includes/fonction.php"
File (12,88K)
-rwxrwxrwx
'line' => integer456
'function' => string(20) "authentifyThirdParty"
'class' => string(23) "App\Libraries\ApiClient"
'type' => string(2) "->"
→'args' => array(1)
string(7) "xxx"
→array(4)
→'file' => string(44) "/home/conges/index.php"
File (4,97K)
-rwxrwxrwx
'line' => integer73
'function' => string(13) "storeTokenApi"
→'args' => array(3)
→App\Libraries\ApiClient(1)
contents Available methods (9)
→private client -> GuzzleHttp\Client(1)
contents Available methods (13) Static class properties (1)
→private config -> array(8)
*DEPTH TOO GREAT*
string(7) "xxx"
string(9) "xxxxxxx"
private previous -> NULL
→ Called from <ROOT>/index.php:75

**Comment by Nulos** [comment]
Je viens de supprimer mon post. J'espère qu'il n'y a pas d'historique...

Par contre, je ne sais pas si ça peut aider, mais lorsque j'ai fait un base64 decode j'ai mon nom d'utilisateur (remplacé par xxxx) ça donne = xxxx:none 

→$e LogicException(7)
contents Available methods (11)
→protected message -> string(532) "Erreur client : Request -> GET /api/authentification HTTP/1.1 User-Agent: Guzzle…"
Erreur client : Request -> GET /api/authentification HTTP/1.1
User-Agent: GuzzleHttp/6.2.1 curl/7.52.1 PHP/7.1.19-1+0~20180714181911.1+jessie~1.gbpa53b68
Host: conges
Authorization: Basic 
Content-Type: application/json
Accept: application/json

 | Response <- HTTP/1.1 404 Not Found
Date: Fri, 27 Jul 2018 12:10:33 GMT
Server: Apache
Content-Length: 91
Content-Type: application/json;charset=utf-8

{"code":404,"status":"error","message":"Not Found","data":"No user matches these criteria"}
private string -> string(0) ""
protected code -> integer0
→protected file -> string(62) "/home/conges/App/Libraries/ApiClient.php"
File (4,83K)
-rwxrwxrwx
protected line -> integer134
→private trace -> array(4)
→array(6)
→'file' => string(62) "/home/conges/App/Libraries/ApiClient.php"
File (4,83K)
-rwxrwxrwx
'line' => integer106
'function' => string(7) "request"
'class' => string(23) "App\Libraries\ApiClient"
'type' => string(2) "->"
→'args' => array(3)
→array(6)
→'file' => string(62) "/home/conges/App/Libraries/ApiClient.php"
File (4,83K)
-rwxrwxrwx
'line' => integer88
'function' => string(16) "authentifyCommon"
'class' => string(23) "App\Libraries\ApiClient"
'type' => string(2) "->"
→'args' => array(2)
string(7) "xxx"
string(4) "none"
→array(6)
→'file' => string(56) "/home/conges/includes/fonction.php"
File (12,88K)
-rwxrwxrwx
'line' => integer456
'function' => string(20) "authentifyThirdParty"
'class' => string(23) "App\Libraries\ApiClient"
'type' => string(2) "->"
→'args' => array(1)
string(7) "xxx"
→array(4)
→'file' => string(44) "/home/conges/index.php"
File (4,97K)
-rwxrwxrwx
'line' => integer73
'function' => string(13) "storeTokenApi"
→'args' => array(3)
→App\Libraries\ApiClient(1)
contents Available methods (9)
→private client -> GuzzleHttp\Client(1)
contents Available methods (13) Static class properties (1)
→private config -> array(8)
*DEPTH TOO GREAT*
string(7) "xxx"
string(9) "xxxxxxx"
private previous -> NULL
→ Called from <ROOT>/index.php:75

**Comment by wouldsmina** [comment]
J'ai trouvé la source du problème, c'est lié a l'API et la connexion par ldap. Ca va prendre un peu de temps pour le résoudre. As tu besoin de revenir en 1.10 ou est ce que ce n'est qu'un test?

**Comment by wouldsmina** [comment]
Oui, c'est lié... au moins ton pwd n'a pas fuité :)

**Comment by Nulos** [comment]
Ok super.
C'est bon j'ai une 1.10 :) Merci.

**Comment by Kaioh31870** [comment]
Bonjour,
Ayant exactement le même problème je me permets de poster le résultat du ddd :
<pre>
$e LogicException(7)

        contents Available methods (11) 

        →protected message -> string(566) "Erreur client : Request -> GET /api/authentification HTTP/1.1 User-Agent: Guzzle…"

            Erreur client : Request -> GET /api/authentification HTTP/1.1
            User-Agent: GuzzleHttp/6.2.1 curl/7.19.7 PHP/5.6.33
            Host: absences.devinlecleclerc.com
            Authorization: Basic mybase64pwd
            Content-Type: application/json
            Accept: application/json

             | Response <- HTTP/1.1 404 Not Found
            Date: Fri, 27 Jul 2018 15:58:58 GMT
            Server: Apache/2.2.15 (CentOS)
            X-Powered-By: PHP/5.6.33
            Content-Length: 90
            Connection: close
            Content-Type: application/json;charset=utf-8

            {"code":404,"status":"fail","message":"Not Found","data":"No user matches these criteria"}

        private string -> string(0) ""

        protected code -> integer0

        →protected file -> string(56) "/var/www/Libertempo-web-1.11/App/Libraries/ApiClient.php"
                File (4,83K) 

                -rw-r--r--

        protected line -> integer134

        →private trace -> array(4)

            →array(6)

                →'file' => string(56) "/var/www/Libertempo-web-1.11/App/Libraries/ApiClient.php"
                        File (4,83K) 

                        -rw-r--r--

                'line' => integer106

                'function' => string(7) "request"

                'class' => string(23) "App\Libraries\ApiClient"

                'type' => string(2) "->"

                →'args' => array(3)

                    string(3) "GET"

                    string(16) "authentification"

                    →array(1)

                        →'headers' => array(1)

                            'Authorization' => string(26) "Basic dGxhbW91cmU6bm9uZQ=="

            →array(6)

                →'file' => string(56) "/var/www/Libertempo-web-1.11/App/Libraries/ApiClient.php"
                        File (4,83K) 

                        -rw-r--r--

                'line' => integer88

                'function' => string(16) "authentifyCommon"

                'class' => string(23) "App\Libraries\ApiClient"

                'type' => string(2) "->"

                →'args' => array(2)

                    string(8) "myuser"

                    string(4) "none"

            →array(6)

                →'file' => string(50) "/var/www/Libertempo-web-1.11/includes/fonction.php"
                        File (12,88K) 

                        -rw-r--r--

                'line' => integer456

                'function' => string(20) "authentifyThirdParty"

                'class' => string(23) "App\Libraries\ApiClient"

                'type' => string(2) "->"

                →'args' => array(1)

                    string(8) "myuser"

            →array(4)

                →'file' => string(38) "/var/www/Libertempo-web-1.11/index.php"
                        File (4,97K) 

                        -rw-r--r--

                'line' => integer73

                'function' => string(13) "storeTokenApi"

                →'args' => array(3)

                    →App\Libraries\ApiClient(1)
                            contents Available methods (9) 

                            →private client -> GuzzleHttp\Client(1)
                                    contents Available methods (13) Static class properties (1) 

                                    →private config -> array(8)

                                        *DEPTH TOO GREAT*

                    string(8) "myuser"

                    string(10) "mypassword"

        private previous -> NULL
</pre>

Suis-je victime du même bug ?

Je vous remercie par avance.

Bien cordialement,

Thierry.

**Comment by wouldsmina** [comment]
Bonjour @Kaioh31870,

Oui c'est le même problème. désolé.

**Comment by Kaioh31870** [comment]
Bonjour,
Peut-on revenir facilement à une 1.10 ?
Cordialement,
Thierry

**Comment by wouldsmina** [comment]
Oui, lors d'une mise a jour, lt effectue une backup de la bdd, il te suffit de la restaurer et de remettre les fichiers de la version 1.10

**Comment by wouldsmina** [comment]
@Kaioh31870 le problème ne vient peut être pas de la ou je pensais. Es tu sur de ne pas avoir d'erreur dans les logs apache?

**Comment by Jackano** [comment]
Pas de logs Apache chez moi avec le même constat.
J'ai retracé jusqu'au 
```
public function authentifyThirdParty($login)
    {
        return $this->authentifyCommon($login, 'none');
    }

```
où j'ai arrêté de chercher en me disant pourquoi on passe plus le mot de passe de l'user LDAP ici!

**Comment by wouldsmina** [comment]
Bonjour @Jackano 
Nous sommes justement entrain de corriger cela ;)

**Comment by Kaioh31870** [comment]
Bonjour @wouldsmina,
Je viens de réinstaller la version 1.11 et je te confirme que je n'ai rien dans les logs d'erreur d'Apache.
Bonne journée
Thierry.

**Comment by TLBesante** [comment]
Bonjour,
J'ai mis à jour la 1.11 depuis la 1.10.1 et j'ai eu la même erreur, mais avec l'authentification depuis la BDD. J'ai fait un roll-back. J'ai tenté une installation de la 1.11 depuis zéro et impossible de se connecter avec le compte admin par défaut.
Thomas

**Comment by wouldsmina** [comment]
Bonjour @TLBesante 
Ton problème est différent, il doit certainement être lié a la configuration de ton vhost. Je t'invite a vérifier les prérequis et ouvrir un nouveau ticket si besoin.
A+

**Comment by TLBesante** [comment]
Je n'y avais pas pensé. Merci @wouldsmina.

**Comment by prytoegrian** [comment]
Bonjour,

@Jackano en effet, le mot de passe n'est pas transmis à l'API compte tenu du fait que l'authentification via LDAP est faite au préalable. J'avais conçu l'API pour qu'elle n'aie pas conscience de la méthode de connexion (dans mon idéal, elle devrait s'en ficher), malheureusement, j'ai mal designé le truc. C'est une erreur de jeunesse mais évidemment ça ne me défausse pas. Nous souhaitons d'améliorer ça, mais c'est un sujet complexe et qui est soumis à nos dispos.
Habituellement, quand je débogue la connexion LDAP, je fais : 
```diff
} catch (\Exception $e) {
+ ddd($e->getMessage());
  errorAuthentification();
}
```

Peut-être cela pourra-t-il t'aider, sinon reviens nous voir.

@Kaioh31870 (+ @exyl @Nulos ) revenir à une version antérieure est toujours possible, nous réalisons une sauvegarde avant chaque màj par sécurité, comme l'a évoqué mon camarade @wouldsmina. Par contre, je dois quand même avouer que tu rates un truc dans la pratique du logiciel libre. Bien sûr que la participation de chacun est conditionnée par les qualifications, l'envie ou le temps. Mais la position consistant à rollback en attendant que les autres règlent le problème ne tient pas, ne fut-ce-que parce que nous n'avons pas ta pile logicielle. Je rappelle que nous ne sommes que deux devs officiels, et nos dispos fondent à vu d'oeil ; autrement dit, le logiciel est à **deux doigts de mourir**. C'est une réalité.
Je le dis et le répète : ce logiciel est le votre, à tous. Les apports métiers et la fiabilité viennent de vous, la communauté constituée vient de chacun d'entre vous. Vous n'avez aucun support officiel, donc c'est en agissant ensemble, chacun à son niveau, que l'on fera de ce logiciel un produit qui répond à ses enjeux.

Croyez bien que c'est pas plaisant à écrire et probablement pas à lire, mais nous ne pouvons pas tenir la charge seuls.

**Comment by Jackano** [comment]
Ok de ce fait sur la base de

>  "le mot de passe n'est pas transmis à l'API compte tenu du fait que l'authentification via LDAP est faite au préalable"

voici une solution avec un if pas glamour mais qui fonctionne chez nous
`\libertempo\vendor\Libertempo\libertempo-api\Authentification\AuthentificationController.php ~l.50
 
            if($password!='none') 
                $utilisateur = $this->repository->find([
                    'login' => $login,
                    'password' => $password,
                    'isActif' => true,
                ]);
            else // LDAP mode already authenticated
                $utilisateur = $this->repository->find([
                    'login' => $login,
                    'isActif' => true,
                ]);`

**Comment by wouldsmina** [comment]
@prytoegrian est un peu brut mais il a raison!

**Comment by Kaioh31870** [comment]
Bonjour @prytoegrian,
J'utilise libertempo pour la gestion des congés dans mon équipe de 20 personnes et malheureusement, si je passe sur une version supérieure et que ce passage bloque l'accès à l'application, il me faut trouver une solution pour rétablir l'accès à mes utilisateurs. Avant de faire un "roll-back", j'essaie de vous exposer le problème, quand le problème est complexe (ce qui a l'air d'être le cas) je suis obligé de revenir à la version précédente.
Je n'ai malheureusement pas de compétence en développement web et, comme ce n'est pas mon métier, je ne dispose pas du temps nécessaire pour les acquérir.
J'essaie par contre de contribuer à ma façon en installant les versions "beta" afin de participer à la recette.
Je sais que ma réponse ne te satisfera pas @prytoegrian mais je ne vois pas comment vous aider plus que je ne le fais aujourd'hui...
Thierry

**Comment by wouldsmina** [comment]
L'idée n'est pas de bloquer la prod bien évidemment, mais on ne peut que conseiller de tester la beta sur une copie de la prod. Cela nous permet d'échanger tranquillement sur le problème et de le corriger avant  le passage de la beta en stable.

**Comment by prytoegrian** [comment]
Bonjour à tous,

@Jackano je suis surpris que tu doives faire cela puisque le mot de passe transmis (« none ») est bien celui qui est stocké dans la BDD (chiffré évidemment). Je viens de terminer les specs pour la mise en place de la connexion LDAP dans l'API. Si comme je le vois tu es confortable en développement, je peux te mettre dans la boucle pour que tu réalises le dev dans l'API (parce que ce que tu as modifié est en réalité [l'API](https://github.com/libertempo/api), mais importée).

@Kaioh31870 une partie de moi comprend (comme je l'ai noté plus haut), une autre se rend compte que ce n'est pas tenable à long terme et vous en informe. Le problème n'est pas tant que tu ne puisses pas contribuer (ou ne saches pas comment faire), il est dans le nombre de personnes qui sont dans ta situation. Dans tous les logiciels libres, il y a un ratio entre les contributeurs et les non contributeurs, c'est naturel ; mais dans notre situation l'équilibre n'est pas atteint et nous manquons de résilience.
Nous avons évoqué la question avec @wouldsmina et nous avons compris que nous ne mettions pas assez l'accent sur les autres types de contribution. Le compte-rendu de la réunion est trop long pour être écrit dans un message de ticket, donc sachez que nous *cherchons officiellement des contributeurs* pour : 
- tester les beta dans des situations cibles : différentes connexions, cas métiers, ergonomie, etc.,
- animer la communauté : communiquer sur le métier actuel, les actions de l'équipe, les bugs et les mises à jour,
- effectuer des recherches sur les congés en France dans un but de communication ou d'intégration dans LT,
- participer à la production du code.

Aucun n'est très long ni coûteux, de l'ordre de ~5 heures par mois.

De notre côté, sachez aussi que nous sommes en train de prendre des dispositions pour mieux nous organiser et hiérarchiser vos besoins. Notre espoir est qu'elles nous permettent d'être plus réactifs, plus précis sans toutefois vivre dans une urgence permanente.

Voilà pour le drama. Maintenant je vais me bouger pour mettre LDAP dans l'API...

**Comment by prytoegrian** [comment]
Je clos, nous avons déployé la release qui corrigeait : https://github.com/libertempo/web/releases/tag/v1.11.1

**Comment by Nulos** [comment]
Bonjour,

Je viens d'installer la 1.11.1 mais ça ne fonctionne toujours pas pour moi.
J'ai pourtant téléchargé le dernier zip, modifier la bbd avec la requête... Je ne vois pas.

D'avance merci de votre aide.

**Comment by prytoegrian** [comment]
Ah, ton message est passé à la traque. Note nous ce que tu fais, à la manière de https://github.com/libertempo/web/issues/new?template=rapport-de-bug.md
