### ISSUE TITLE
Problème mise à jour depuis Ceres

### ISSUE THREAD

**Issue by exyl** [libertempo/web#692]
Bonjour,

Je me lance dans la mise à jour de Libertempo depuis la v1.9
J'ai mis à jour les fichiers de la dernière version de Cères.
Tout est ok.

Je viens de copier les fichiers de la version 1.10 en ayant pris soin de vérifier les points (groupe vide, etc...)
Quand je vais sur la page de connexion, j'ai la page de login, et à la place du bouton Connexion, il est écrit "ERREUR ! Modifications NON enregistrées !"
En entrant, j'ai des titres non traduits partout.

Je suis sur Centos

**Comment by exyl** [comment]
Je suis aller sur http://libertempo/install/index.php
Et j'ai : 
version déjà installée. Internet Explorer n'est pas pris en charge par Libertempo!utilisez un autre navigateur ...

Je suis sur Chrome !

**Comment by wouldsmina** [comment]
Salut, 
Gettext a besoin d'être rechargé. Restart ton apache et vide le cache de ton navigateur, ça devrait suffire.
A+

**Comment by exyl** [comment]
Effectivement, c'est revenu.
Merci !
Je continue les mises à jour :)

**Comment by exyl** [comment]
Mise à jour en 1.11 effectuée. 
Mais je ne peux plus ouvrir de session LDAP.
J'ai vérifié la conf, ca semble ok.

**Comment by exyl** [comment]
Dans les logs j'ai ca : 

> Mon Aug 06 12:06:36.537835 2018] [:error] [pid 2734] [client 192.168.2.1:54499] PHP Warning:  ldap_search(): Search: Bad search filter in /var/www/html/libertempo/library/authLDAP.php on line 130, referer: http://libertempo/index.php?error=session-invalid
[Mon Aug 06 12:06:36.537893 2018] [:error] [pid 2734] [client 192.168.2.1:54499] PHP Warning:  ldap_get_entries() expects parameter 2 to be resource, boolean given in /var/www/html/libertempo/library/authLDAP.php on line 134, referer: http://libertempo/index.php?error=session-invalid

**Comment by wouldsmina** [comment]
Hmmm, le fichier config_ldap.php a changé sur Mondaran et j'ai carrément oublié de le préciser dans la documentation ! Jette un oeil sur config_ldap_new.php... je vais, de mon côté, essayer de mettre a jour la doc ce soir.
Désolé

**Comment by exyl** [comment]
J'ai regardé, à part $config_ldap_filtre_complet = "";    je ne vois rien d'autre
Par contre, je ne sais pas quoi mettre.

**Comment by exyl** [comment]
Bonjour,
Je suis toujours bloqué.
Est-ce que je dois revenir en arrière ?

**Comment by wouldsmina** [comment]
Désolé, je suis pas mal pris sur autre chose, je n'ai pas eu le temps de regarder. Tu peux revenir en arrière avec la backup post update.

**Comment by wouldsmina** [comment]
re @exyl 
je viens de regarder ton problème de plus près, $config_ldap_filtre_complet n'est plus utilisé depuis Mondaran. Si ton fichier config_ldap.php n'utilise pas cette variable, tu n'as rien à changer dedans. En tout cas, ça a l'air d'être lié à ton install...

As tu réussi à revenir à Ceres? 
Pourrais tu faire un débug sur une install de test? si oui, dis moi ce que retourne LT lorsque tu ajoutes cette ligne de code [ici](https://github.com/libertempo/web/blob/develop/library/authLDAP.php#L130) :  `ddd($filtre,$this->ldap_login,$this->user_login);` tu dois aussi modifier cfg/env.php pour passer en `ENV_DEV`.

**Comment by exyl** [comment]
Je suis revenu à la version 1.10

**Comment by wouldsmina** [comment]
désolé @exyl ta réponse m'avait échappée. après tu te connectes sur lt pour avoir un retour détaillé du contenu des variables. Pense à modifier le fichier cfg/env.php

**Comment by wouldsmina** [comment]
@exyl, j'imagine que tu es passé à autre chose depuis le temps. Désolé de ne pas avoir trouvé de solution à ton problème. 
Pour info, la connexion LDAP a été revu et testé sur la version 1.12.
++
