### ISSUE TITLE
Affichage Calendrier 

### ISSUE THREAD

**Issue by exyl** [libertempo/web#693]
Bonjour à l'équipe,

Une petite question.
Je suis passé donc de la v1.9 à v1.10 il y a une semaine.
Mes utilisateurs me font remarquer qu'ils ne voient plus que leur groupe dans le calendrier.
Je viens de farfouiller un peu partout mais je ne trouve pas où revenir à une vision collective.

**Comment by wouldsmina** [comment]
Bonjour @exyl,
Le sujet a déjà été abordé dans un autre ticket sur le calendrier. Nous avons prévu de rétablir un certains nombres de fonctionnalités, mais pas celle ci. Fait une recherche dans les tickets, tu trouveras les raisons qui nous poussent à limiter la vue des employés à leurs groupes...
A+
