### ISSUE TITLE
Gestion modification/suppression de congés en workflow simple

### ISSUE THREAD

**Issue by SyTry** [libertempo/web#696]
Bonjour,

Utilisant l'application (en version 1.11) avec le workflow "simple" (sans double validation), nous nous sommes aperçus que nous n'étions pas capables de modifier ou de supprimer des demandes de congés.
Ceci nous posant problème, nous avons donc modifié le code pour intégrer l'état pré-validé pour pouvoir faire ces actions (cf bloc plus bas).

Il nous a fallu aussi modifier la vérification de la variable $interdictionModification (suppression de la négation par rapport au code d'origine). C'est ce point qui serait selon nous un bug.
En effet, il semblerait que le nom de la variable ne correspond pas à l'état réel : 
$interdictionModification prends la valeur de canUserModifieDemande()
canUserModifieDemande() return la négation de la configuration interdit_modif_demande

_Pour faire plus propre on pourrait changer l'affectation de interdictionModification_ 

Les modifications sont donc les suivantes : 
utilisateur/user_liste_conge.php lignes 84 à 86 :
```
        $data->isModifiable = $conges["p_etat"] == \App\Models\Conge::STATUT_DEMANDE && !$interdictionModification;
        $data->numConge = $conges['p_num'];
        $data->isSupprimable = $conges["p_etat"] == \App\Models\Conge::STATUT_DEMANDE;
```
par 

```
        $data->isModifiable = ( $conges["p_etat"] == \App\Models\Conge::STATUT_DEMANDE || $conges["p_etat"] == \App\Models\Conge::STATUT_PREMIERE_VALIDATION ) && $interdictionModification;
        $data->numConge = $conges['p_num'];
        $data->isSupprimable = ( $conges["p_etat"] == \App\Models\Conge::STATUT_DEMANDE || $conges["p_etat"] == \App\Models\Conge::STATUT_PREMIERE_VALIDATION
);
``` 

et 
utilisateur/Fonctions.php ligne 1438
` if (($conge["p_etat"]  == \App\Models\Conge::STATUT_DEMANDE) && ($conge['p_login'] == $user)) {
`
par
` if ((($conge["p_etat"]  == \App\Models\Conge::STATUT_DEMANDE || $conge["p_etat"]  == \App\Models\Conge::STATUT_PREMIERE_VALIDATION)) && ($conge['p_login'] == $user)) {`

**Comment by wouldsmina** [comment]
Merci pour l'info @SyTry . Je teste ça dés que possible

**Comment by landryb** [comment]
Bonjour,

j'essaie de tester ce patch sur la v1.11 mais ici sans validation, un congé passe directement au statut VALIDATION_FINALE sans passer par PREMIERE_VALIDATION, donc je ne comprends pas comment ce patch devrait permettre a un utilisateur de modifier/supprimer ses congés...

actuellement, mes utilisateurs sont génés car uniquement un RH peut 'supprimer' un congé, et ca ne supprime pas vraiment le congé, certes ca recrédite le solde, mais le congé apparait toujours dans le calendrier/export ICS en état 'TENTATIVE' plutot que ne pas apparaitre du tout.
