### ISSUE TITLE
Pas de traductions de l'interface en 1.11 (que des clefs)

### ISSUE THREAD

**Issue by landryb** [libertempo/web#698]
**Décrivez le bug**
sur une nouvelle installation de 1.11, toutes les chaines affichees a l'ecran ne sont pas 'traduites' via gettext, j'ai les clefs sur tous les écrans/menus:

```
config_comment_how_to_connect_user
how_to_connect_user
```

L'extention gettext de php est installée et activée:
```
$php7.0 -m |grep gettext
gettext
```
et dans la db j'ai bien `fr_FR` pour la langue installée. Comment je peux débugguer ceci ?

**Comment by landryb** [comment]
Pour information, le context c'est une debian stretch avec nginx 1.14 et php-fpm. Pareil si je passe lang=fr_FR en querystring..

Mon virtualhost est actuellement le suivant, en cours d'affinage:
```
server {
        listen  80;
        listen [::]:80;
        server_name conges.mon.domaine;

        access_log /var/log/nginx/conges_access.log fwd_log;
        error_log /var/log/nginx/conges_error.log;

        root /var/www/libertempo;
        index index.php;

        location / {
                try_files $uri $uri/ /index.php$is_args$args;
        }
        location /api/ {
                try_files $uri $uri/ /vendor/Libertempo/libertempo-api/Public/index.php$is_args$args;
        }

        location ~ \.php$ {
                fastcgi_split_path_info ^(.+?\.php)(|/.*)$;
                include fastcgi_params;
                # Block httpoxy attacks. See https://httpoxy.org/.
                fastcgi_param HTTP_PROXY "";
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        }
}

```

**Comment by landryb** [comment]
J'ai essayé en changeant les différents réglages de firefox (`intl.accept_languages`, `general.useragent.locale`) mais ca ne change rien. Si j'affiche la langue avec un print dans includes/lang_profile.php j'ai bien fr_FR.

Ce qui est étrange c'est que les sous-items des menus sont traduits mais pas les boutons/menus... ce n'est pas completement cassé.

![screenshot_2018-08-30_12-16-48](https://user-images.githubusercontent.com/3421760/44845729-9b6f7680-ac4e-11e8-98a1-f5970d8080b9.png)

**Comment by landryb** [comment]
hello @wouldsmina , oui comme je l'ai dit dans mon premier commentaire gettext est présent.. (fourni par le paquet php7.0-common dans debian stretch), et l'extension est chargée par php-fpm..
```
$tail -1 /etc/php/7.0/fpm/conf.d/20-gettext.ini
extension=gettext.so
```

**Comment by wouldsmina** [comment]
Ok. Tu utilises nginx, de mémoire tu es le premier! Avant de nous pencher dessus, peux tu vérifier que ton serveur a bien la locale Fr_fr d'installé (je ne pense pas que le problème vienne de la, mais il faut etre sur).
 En tout cas, tu as réussi a (presque) faire tourner LT sur nginx, bien joué! :)

**Comment by landryb** [comment]
c'était bien ca.. mon conteneur lxc n'avait aucune locale configurée, après un dpkg-reconfigure locales et l'activation de fr_FR.UTF-8 c'est correct.

Autre détail à mettre peut-être dans les dépendances.. il manquait php7.0-mbstring pour la fonction mb_substr(), j'ai du l'installer en plus.
