### ISSUE TITLE
Nombre de jours incorrect lors d'ajout Nouveau Congé (1.9 ou 1.11)

### ISSUE THREAD

**Issue by kamekool** [libertempo/web#699]
Bonjour,

J'ai installé il y a près d'un an en test une version 1.9, pour finalement m'y remettre cette semaine.
Je n'arrive pas à comprendre où peut se configurer ce réglage, mais lors d'un nouveau congé, le nombre de jours calculé est divisé par 2 (2,5 jours pour une semaine par ex > voir lien)
J'ai effectué une mise à jour vers la 1.11, mais le souci se reproduit, il doit y avoir une config enregistrée en DB qui force cela...

[https://zupimages.net/up/18/36/6ydy.png](url)

Merci pour votre aide

**Comment by wouldsmina** [comment]
Bonjour,
Tu as certainement mal paramétré le planning, a vu de nez tu as paramétré tes plages horaires que le matin...

**Comment by kamekool** [comment]
Merci pour le retour,
J'avais vérifié ce point et ça semblait bon 👍 
Mais en fait ce sont des plages entières, sans pause de midi, ça doit être le souci !
Je check de suite

Jour | Créneaux de travail | 50h
-- | -- | --

Lundi | 08:00  18:00 (pm) |  
Mardi | 08:00  18:00 (pm) |  
Mercredi | 08:00  18:00 (pm) |  
Jeudi | 08:00  18:00 (pm) |  
Vendredi | 08:00  18:00 (pm)

**Comment by kamekool** [comment]
C'est tout bon ! je vais essayer de marqué le sujet en résolu !
Bonne journée,
