### ISSUE TITLE
Problème d'installation de Libertempo

### ISSUE THREAD

**Issue by ttaduy** [libertempo/web#701]
Bonjour à tous,
Je sollicite votre aide car, étant une courge en web, j'ai un problème pour installer Libertytempo v.1.11.0
 J'ai suivi le tuto pourtant. Voici ce que j'ai fait : 

1/ apt install apache2 mariadb-client php-mysql php-curl php-gettext
2/ apt install mariadb-server
3/ a2enmod rewrite
4 /J’ai modifié le fichier /etc/apache2/apache2.conf comme indiqué dans le tuto.
 
<Directory /var/www/>
     Options Indexes FollowSymLinks
     AllowOverride All
     Require all granted
</Directory>
 
6/ J'ai décommenté la ligne AccessFileName .htaccess

7/ Mon vhost est exactement celui sur le site :
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName conges.bomi.com
    DocumentRoot /var/www/libertempo
 
    <Directory /var/www/libertempo>
        Options -Indexes
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteBase /
        RewriteRule ^api/(.*)$ vendor/Libertempo/libertempo-api/Public/ [QSA,L]
     </Directory>
 
     <Directory /var/www/libertempo/vendor/Libertempo/libertempo-api>
        <Files "configuration.json">
            Order Allow,Deny
            Deny from all
        </Files>
     </Directory>
 
    ErrorLog ${APACHE_LOG_DIR}/error-lt.log
    CustomLog ${APACHE_LOG_DIR}/access-lt.log combined
</VirtualHost>
 
8/ J’ai crée la base db_conges dans Mariadb, crée un utilisateur et lui ai donné plein droits sur cette base
9/ J’ai donné les droits www-data sur mon répertoire 
10/ J’ai copié le fichier cfg/env_new.php vers cfg/env.php
 
Les problèmes que je rencontre est : 
1/ En tapant http://conges.bomi.com/api/hello_world, j'obtiens cette erreur 
{"code":400,"status":"fail","message":"Bad Request","data":"Request Content-Type and Accept must be set on application\/json only"}

2/ J'ai bien la homepage de Libertempo mais je suis dans l'impossibilité de me loguer en utlisant le compte admin / responsable.
 L'erreur que j'obtiens est utilsateur/passe incorrect.
J'ai vérifié que le username admin existe bien dans la table conges_users

Pourriez-vous m'aider ? Pourriez-vous me dire ce que je dois vérifier en plus, ou changer ?
Je vous remercie d'avance pour toute l'aide que vous pouvez m'apporter.

**Comment by ttaduy** [comment]
Bonjour,
Finalement, avec l'aide d'un ami, qui a mis le nez dans le code et on a vu que ça bloquait à ce niveau.
storeTokenApi($api, $session_username, $session_password); dans le fichier index.php.
Il a réussi à intercepter l'erreur en retour. Et l'erreur se portait sur une absence de record DNS sur le serveur.
J'ai ajouté cette ligne dans le hosts et j'arrive maintenant à me loguer.

Merci à Wouldsmina pour l'aide et je suis désolé de t'avoir embêté autant.

**Comment by ttaduy** [comment]
Ceci dit, même si je peux me logguer et utiliser l'app, j'ai toujours cette erreur 
{"code":400,"status":"fail","message":"Bad Request","data":"Request Content-Type and Accept must be set on application/json only"}
avec le lien  http://conges.bomi.com/api/hello_world

Si je peux avoir une explication, ce serait cool. Merci

**Comment by prytoegrian** [comment]
L'api n'est pas censée être contactable en l'état, seul le client web peut l'appeler. Wouldsmina t'a conseillé de taper dessus car c'est un bon moyen de verifier que techniquement tout fonctionne.

**Comment by wouldsmina** [comment]
Je t'ai induit en erreur @ttaduy 
L'erreur que tu obtiens est normal, l'important c'est que c'est l'API qui répond.

**Comment by ttaduy** [comment]
Tout va bien donc. Je ferme ce ticket.
Merci à vous 2 pour l'aide et les explications apportées
