### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Nath73** [libertempo/web#702]
Bonjour,
Je voudrais installer Libertempo 1.11 sur notre serveur, mais j'obtiens le message suivant :
 Échec de l'installation / mise à jour : Création du fichier de config API impossible. Les droits sont-ils bien configurés ?
Voici les caractéristiques du serveur
Serveur de base de données
    Serveur : Localhost via UNIX socket
    Type de serveur : MySQL
    Version du serveur : 5.5.55-0+deb8u1 - (Debian)
    Version du protocole : 10
    Utilisateur : eid-gestion@localhost
    Jeu de caractères du serveur : UTF-8 Unicode (utf8)

Serveur web
    Apache/2.4.10
    Version du client de base de données : libmysql - 5.5.55
    Extension PHP : mysqli Documentation
    Version de PHP : 5.6.30-0+deb8u1

En lisant qq commentaires, j'ai supposé que cela est dû à la version de Mysql. Ai-je moyen de contourner ce problème ? Faut-il installer une autre version de Libertempo mais qui gère également les heures supplémentaires ?

Merci d'avance,
Cordialement

Nathalie

**Comment by prytoegrian** [comment]
Bonjour @Nath73,

le message d'erreur arrive quand tous les droits du répertoire `repertoireLibertempo` n'ont pas été accordé à `www-data` (en récursif évidemment), tel que décrit dans la [procédure d'installation](http://libertempo.tuxfamily.org/documentation/installation/). À cet endroit, MySQL ne rentre par encore dans la balance. Je te laisse donc vérifier ça.

Par contre, tu mets le doigt sur un fait intéressant : LT 1.11 n'est pas compatible avec MySQL 5.5 (Cf. https://github.com/libertempo/web/tree/1.11#support-minimum), tu n'es donc pas assurée que LT fonctionne sur cette version et nous ne pourrons pas faire de support dans ce cas.

Également, nous n'avons pas à proprement parler de gestion d'heures supplémentaires. Ces dernières possèdent beaucoup de règles et de conséquences métiers, que nous n'avons pas pu mettre en place pour le moment. Nous avons cependant des heures additionnelles / de repos, mais ce sera à toi de donner un sens métier. Cette fonctionnalité est disponible depuis la 1.9.

Par contre, et j'insisterai vivement là-dessus, MySQL 5.5 et PHP 5.6 ne seront plus supportés par ses mainteneurs en décembre 2018. Nous ne supporterons donc plus ces versions à courte échéance et je ne peux te fournir de moyens de contourner ce problème.

Ai-je répondu à toutes tes questions ?
N'hésite pas à me dire si l'installation est capricieuse.

**Comment by Nath73** [comment]
Merci pour tes réponses
Effectivement, en changeant les droits j'ai pu lancer l'install mais j'ai ensuite le message d'erreur suivant:
``login : 
uri   : /z_libertempo/install/install.php
dump  : ../dump/sql_2018-09-11T11:06:00+02:00.dump

file  : /home/eid-gestion/public_html/z_libertempo/includes/SQL.php
line  : 55
fx    : $SQL->query
error : Invalid default value for 'date_inscription'
sql   : CREATE TABLE IF NOT EXISTS `conges_users` (`u_login` varbinary(99) NOT NULL DEFAULT '',`u_nom` varchar(30) NOT NULL DEFAULT '',`u_prenom` varchar(30) NOT NULL DEFAULT '',`u_is_resp` enum('Y','N') NOT NULL DEFAULT 'N',`u_is_admin` enum('Y','N') NOT NULL DEFAULT 'N',`u_is_hr` enum('Y','N') NOT NULL DEFAULT 'N',`u_is_active` enum('Y','N') NOT NULL DEFAULT 'Y',`u_passwd` varchar(64) NOT NULL DEFAULT '',`u_quotite` int(3) DEFAULT '100',`u_email` varchar(100) DEFAULT NULL,`u_num_exercice` int(2) NOT NULL DEFAULT '0',`planning_id` int(11) UNSIGNED NOT NULL,`u_heure_solde` int(11) NOT NULL DEFAULT '0',`date_inscription` DATETIME NOT NULL DEFAULT NOW(),`token` VARCHAR(100) NOT NULL DEFAULT '',`date_last_access` DATETIME NOT NULL,PRIMARY KEY (`u_login`),KEY `planning_id` (`planning_id`),KEY `token` (`token`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
j'imagine que cela est dû à la version :-( ?
Ca me fait souci du coup ce problème de version MySQl et PHP, il faut que je vois avec mon hébergeur ce que cela va impliquer pour nos autres sites...
Merci

**Comment by prytoegrian** [comment]
Absolument ! ([Source](https://optimize-this.blogspot.com/2012/04/datetime-default-now-finally-available.html))

**Comment by prytoegrian** [comment]
Le reste du problème sort du cadre de LT.
