### ISSUE TITLE
Pb intall mandaran

### ISSUE THREAD

**Issue by thomas64400** [libertempo/web#703]
Bonjour, 
je suis en train d'installer la version 1.11. lorsque le systeme demande nouvelle install ou mise a jour, je choisis nouvelle installe et voici le message d'erreur affiché:
login : 
uri   : /install/install.php
dump  : ../dump/sql_2018-09-13T04:25:26-04:00.dump

file  : /home/pharmaci/conges.pharmacie-briol.com/includes/SQL.php
line  : 55
fx    : $SQL->query
error : Invalid default value for 'date_inscription'
sql   : CREATE TABLE IF NOT EXISTS `conges_users` (`u_login` varbinary(99) NOT NULL DEFAULT '',`u_nom` varchar(30) NOT NULL DEFAULT '',`u_prenom` varchar(30) NOT NULL DEFAULT '',`u_is_resp` enum('Y','N') NOT NULL DEFAULT 'N',`u_is_admin` enum('Y','N') NOT NULL DEFAULT 'N',`u_is_hr` enum('Y','N') NOT NULL DEFAULT 'N',`u_is_active` enum('Y','N') NOT NULL DEFAULT 'Y',`u_passwd` varchar(64) NOT NULL DEFAULT '',`u_quotite` int(3) DEFAULT '100',`u_email` varchar(100) DEFAULT NULL,`u_num_exercice` int(2) NOT NULL DEFAULT '0',`planning_id` int(11) UNSIGNED NOT NULL,`u_heure_solde` int(11) NOT NULL DEFAULT '0',`date_inscription` DATETIME NOT NULL DEFAULT NOW(),`token` VARCHAR(100) NOT NULL DEFAULT '',`date_last_access` DATETIME NOT NULL,PRIMARY KEY (`u_login`),KEY `planning_id` (`planning_id`),KEY `token` (`token`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;

une idéee pour sortir de ce mauvais pas ?

**Comment by wouldsmina** [comment]
Bonjour @thomas64400,

Sans plus d'infos je ne pourrai pas t'aider beaucoup, mais vu l'erreur j'ai l'impression que tu n'as pas la bonne version de Mysql (ou mariadb).

**Comment by prytoegrian** [comment]
Cf. #702. Par chance, j'ai reconnu le bug. Par contre, pour l'avenir, je t'invite vivement à décrire le bug avec le template fourni (https://github.com/libertempo/web/issues/new?template=rapport-de-bug.md), c'est le meilleur moyen pour que ton bug soit reconnu rapidement.

**Comment by wouldsmina** [comment]
ping @thomas64400 . As tu testé avec une version de mysql plus récente?
