### ISSUE TITLE
Mondaran 1.11.1 - configuration LDAP (filtre multi groupe)

### ISSUE THREAD

**Issue by philippebaque** [libertempo/web#705]
Bonjour,

J'ai posé une question dans le fil d'une autre (la #309), comme conseillé je formule ici la suite.

Je passe de la version 1.9 en réinstallant une version 1.11.1 (puisque maintenant le LDAP fonctionne)

 Sur ma 1.9 les paramètres:
#-----------------------
$config_ldap_filtre = "";
$config_ldap_filrech= "";
$config_ldap_filtre_complet = "(|(memberOf=cn=GROUPE,ou=g,ou=group,dc=domain,dc=fr)(memberOf=cn=GROUPE-ext,ou=g,ou=group,dc=domain,dc=fr))";
#-------------------------

fonctionnaient et me permettaient de récupérer les usagers des groupes GROUPE et GROUPE-ext

Sur le forum on m'a répondu très rapidement que:

#-------
La variable $config_ldap_filtre_complet n'existe plus dans mondaran.
Tu peux essayer :
$config_ldap_filtre= "memberOf";
$config_ldap_filrech= "GROUPE*";
#-------

Ce que j'ai fait mais qui ne fonctionne pas, ni même si je mets 
$config_ldap_filrech= "GROUPE";
pour ne récupérer que ceux de GROUPE

Par contre j'ai tenté une syntaxe LDAP:
 $config_ldap_filrech= "cn=GROUPE,ou=g,ou=group,dc=domain,dc=fr";

ET là ça fonctionne, je peux récupérer ceux du groupe GROUPE, mais comment spécifier que je souhaite aussi faire 'remonter' ceux du groupe GROUPE-ext...

j'ai tenté en mettant 'GROUPE*', rien ne 'remonte'
j'ai tenté une syntaxe du style:
(|(memberOf=cn=GROUPE,ou=g,ou=group,dc=domain,dc=fr)(memberOf=cn=GROUPE-ext,ou=g,ou=group,dc=domain,dc=fr))

rien non plus!

À l'aideeeeeeeee...

(merci et merci pour la réactivité... chapeau)

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : Debian 9.4
 - Version de Libertempo :  1.11.1
 - Version MySQL et PHP : mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
 PHP 7.0.30-1~dotdeb+8.1 (cli) ( NTS )

**Comment by wouldsmina** [comment]
Re,
Memberof ne doit pas être indexé dans ton ldap, essaye avec cn.

` &(" . $this->configuration['attrNomAff'] . "=" . $nom . "*)(" . $this->configuration['Attrfiltre'] . "=" . $this->configuration['filtre'] . "))`
Attrfiltre et filtre représente respectivement config_ldap_filtre et config_ldap_filrech

**Comment by philippebaque** [comment]
Bonjour,

Ce n'est pas moi qui gère le LDAP et aucune info filtre à ce sujet :(, il n'est peut-être pas indexé effectivement, mais je dois me débrouiller avec, jusqu'à là les requêtes avec  OU (|) fonctionnaient à merveille (comme dans nextcloud ou grr ou libertempov1.9)
Comme je le mentionnais, j'avais trouvé que:
cn=GROUPE,ou=g,ou=group,dc=domain,dc=fr
fonctionne
Mais je n'arrive pas à trouver la syntaxe qu'accepte Libertempo pour faire un OU avec 2 groupes.

Je veux bien essayer avec 'cn', mais en fait à part formuler comme cela:
(|(memberOf=cn=GROUPE,ou=g,ou=group,dc=domain,dc=fr)(memberOf=cn=GROUPE-ext,ou=g,ou=group,dc=domain,dc=fr))
Je ne sais pas faire (j'ai bien tenté différentes syntaxes, avec, sans partenthèses...).

[Wed Sep 19 07:55:30.645475 2018] [proxy_fcgi:error] [pid 5425] [client XXXXXX:34772] AH01071: Got error 'PHP message: PHP Warning:  ldap_search(): Search: Bad search filter in /var/www/web-1.11.1/App/Libraries/Ldap.php on line 77\nPHP message: PHP Warning:  ldap_get_entries() expects parameter 2 to be resource, boolean given in /var/www/web-1.11.1/App/Libraries/Ldap.php on line 78\n', referer: http://liber.domain.fr/hr/hr_index.php?onglet=liste_groupe

Si vous avez une piste de syntaxe ou une solution pour exprimer différement les usagers qui peuvent être dans 2 groupes... je suis preneur...

Je ne vais pas pouvoir ré-installer la version 1.9, je suis donc bloqué... Il me restera à fusionner 'a la mano' ces 2 groupes, en espérant qu'il n'y ait pas trop de modifications pendant l'année... Je voulais juste faire propre avant de ne pas pouvoir y toucher pendant 1 an (les congés c'est trop sensible).
Mais là j'ai déjà la pression RH pour effectuer la fermeture de l'année pécédente.

En tous cas... Merci.

**Comment by wouldsmina** [comment]
j'ai peut etre une piste (la nuit porte conseil) pour améliorer le filtre ldap. Je teste ça dés que possible, j'espère proposer une solution pour la prochaine version...
a+

**Comment by wouldsmina** [comment]
La nuit fut longue :sweat_smile: 
désolé, je suis pas mal occupé ces derniers mois... On travail tout de même sur les problèmes de ldap globalement, j'espere pouvoir apporter une solution à ce problème. Ou en es tu de ton coté?

>Je veux bien essayer avec 'cn', mais en fait à part formuler comme cela:
(|(memberOf=cn=GROUPE,ou=g,ou=group,dc=domain,dc=fr)(memberOf=cn=GROUPE-ext,ou=g,ou=group,dc=domain,dc=fr))

un détail vient de me sauter aux yeux : `memberOf=cn=GROUPE-ext` pourquoi pas simplement `cn=GROUPE-ext`?

**Comment by pitrackster** [comment]
@philippebaque ça date et tu as certainement résolu ton soucis mais au cas ou ça puissse servir.

Si tu veux faire la requête `(|(memberOf=cn=GROUPE,ou=g,ou=group,dc=domain,dc=fr)(memberOf=cn=GROUPE-ext,ou=g,ou=group,dc=domain,dc=fr))` dans ton LDAP. Il suffit de remplir les 2 variables de la configuration comme suit : 
 
```php
$config_ldap_filtre= "|(memberOf";
$config_ldap_filrech= "cn=GROUPE,ou=g,ou=group,dc=domain,dc=fr)(memberOf=cn=GROUPE-ext,ou=g,ou=group,dc=domain,dc=fr)";
```
Avec ça la concaténation devrait te donner le filtre que tu cherches...
