### ISSUE TITLE
export ics: syntaxe invalide

### ISSUE THREAD

**Issue by landryb** [libertempo/web#706]
Bug legerement différent de #436, avec 1.11 sur debian stretch, si on n'utilise pas de validation (j'imagine que c'est lié) les congés entrés en base ont 'NULL' pour le champ `p_date_demande` dans la table `conges_période`.

Ce champ est utilisé pour générer les valeurs UID et DTSTAMP dans les events ICS ici: https://github.com/libertempo/web/blob/master/export/Fonctions.php#L104

vu que la valeur est nulle, l'ICS se retrouve avec des events ayant le meme UID, ce qui ne plait guere a tous les parseurs ICS...

```
BEGIN:VCALENDAR
PRODID:-//Libertempo 
VERSION:2.0

BEGIN:VEVENT
DTSTAMP:Z
ORGANIZER:MAILTO:foo@foo
CREATED:20180924T070000Z
STATUS:CONFIRMED
UID:tous@Libertempo-
DESCRIPTION:Vacances
SUMMARY:conges payes
CLASS:PUBLIC
PRIORITY:1
DTSTART:20180924T070000Z
DTEND:20181003T120000Z
TRANSP:OPAQUE
END:VEVENT

BEGIN:VEVENT
DTSTAMP:Z
ORGANIZER:MAILTO:foo@foo
CREATED:20181015T070000Z
STATUS:CONFIRMED
UID:tous@Libertempo-
DESCRIPTION:Jura
SUMMARY:conges payes
CLASS:PUBLIC
PRIORITY:1
DTSTART:20181015T070000Z
DTEND:20181015T210000Z
TRANSP:OPAQUE
END:VEVENT

BEGIN:VEVENT
DTSTAMP:Z
ORGANIZER:MAILTO:foo@foo
CREATED:20181022T070000Z
STATUS:CONFIRMED
UID:tous@Libertempo-
DESCRIPTION:Cong&eacute;s
SUMMARY:conges payes
CLASS:PUBLIC
PRIORITY:1
DTSTART:20181022T070000Z
DTEND:20181102T210000Z
TRANSP:OPAQUE
END:VEVENT

END:VCALENDAR
```
Comme dit en #436, pour DTSTAMP et UID je pense qu'il faudrait utiliser plutot le champ `p_date_traitement` qui est correctement renseigné et unique pour chacune des entrées de la table. Si je fais ca localement, mon export ICS est bien mieux accepté par lightning p.ex.

Je peux faire une PR dans ce sens si la correction vous parait logique.

**Comment by landryb** [comment]
En fait je pense que c'est le meme bug que #436, qui ne montre qu'un seul event vu que chacun des objets dans l'ICS se retrouve avec le meme UID..

**Comment by wouldsmina** [comment]
gg @landryb! le top serait un petit PR :wink:

**Comment by landryb** [comment]
En fait, c'est plutot la logique qui me gène.. pourquoi `p_date_demande` est `NULL` dans le cas ou il n'y a pas de validation ? pourquoi les deux champs n'auraient pas la même valeur ? est-ce qu'il y'a plein d'effets de bords potentiels si on corrige le problème à cet endroit ? (si je regarde le code a gauche à droite, j'ai l'impression...)

On peut toujours faire l'équivalent de 'si `p_date_demande` est `NULL` alors prendre la valeur de `p_date_traitement`' mais je trouve ca moche.. enfin, PR pending.

**Comment by wouldsmina** [comment]
> En fait, c'est plutot la logique qui me gène.. pourquoi p_date_demande est NULL dans le cas ou il n'y a pas de validation ?

En effet, c'est peut être à ce niveau qu'il y a un problème. Je regarderai ça durant le test de #715.

Merci.
