### ISSUE TITLE
Mondaran 1.11.1 - impossible de supprimer des types d'absences

### ISSUE THREAD

**Issue by philippebaque** [libertempo/web#707]
Bonsoir,

 Sur ma version 1.11.1 nouvellement installée je tente de supprimer des types d'absences à partir du menu Configuration… une item 'rtt' mise en standard et une crée mais inutile 'Conge maladie'…
 Lorsque j'active le bouton croix pour supprimer ce type d'absence (qui en fait sont des 'conges' (soumis à décompte)… J'ai:

Suppression IMPOSSIBLE !
Des congés/absences de ce type sont en cours !

avec un bouton <RECOMMENCER>

Que faire? 

Merci.

Serveur (veuillez remplir les informations suivantes):

    Système [i.e. iOS8.1] : Debian 9.4
    Version de Libertempo :  1.11.1
    Version MySQL et PHP : mysql Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
    PHP 7.0.30-1~dotdeb+8.1 (cli) ( NTS )

**Comment by philippebaque** [comment]
Ahh oui, bien évidement nous n'avons aucun congè en attente sur ce type d'absence (ni sur sur rien d'ailleurs puisque nous sommes en cours de préparation d'une 'fresh-install' plutôt que d'une migration 1.9 -> 1.11, celle-ci nous posant des pbs)

**Comment by wouldsmina** [comment]
Bonjour @philippebaque 
Pourquoi as tu fermé ce ticket? Tu as trouvé une solution?

**Comment by philippebaque** [comment]
NON...

Je l'ai fermé par erreur (de manipulation), pensant juste rajouter un 
commentaire à mon POST... J'ai tout simplement clos le ticket.

désolé.


Le 02/10/2018 à 12:46, wouldsmina a écrit :

**Comment by prytoegrian** [comment]
Je t'invite à mettre à jour vers la version 1.12, les correctifs à #232 ont refondu tout le système des types d'absences.
