### ISSUE TITLE
Mondaran 1.11.1 - champs Noms, Prénoms & Email non modifiables après import LDAP

### ISSUE THREAD

**Issue by philippebaque** [libertempo/web#708]
Re-Bonsoir,

Toujours moi, désolé, mais bon je suis en plein tests donc, mais promis après je me tais.

Je suis toujours en 1.11.1 et lorsque j'utilisais la version 1.9 je pouvais importer les usagers du LDAP et m'authentifier dessus et ensuite modifier certains paramètres NOM, PRÉNOM, EMAIL.

En 1.11.1, bizarrement on ne peut plus du moins NOM et EMAIL et encore pas tout à fait dans PRÉNOM.

NOM est grisé...impossible à modifier
vous allez me dire: Pourquoi vouloir modifier le nom?
Pour simplement le mettre avec les accents qui ne sont pas présents sur le LDAP que nous récupérons, que nous ne gérons pas et que nous ne pouvons pas modifier.

PRÉNOM lui est modifiable 
utile pour adapter les prénoms d'usages qui sont légaux, mais pas pris en compte sur notre fameux LDAP
et de toute façon
On ne peut pas y mettre des caractères bizarres comme des accents... 

EMAIL non modifiable et il serait utile pour utiliser le mail d'usage.

Bon il y a la possibilité d'aller modifier la base directement, mais j'avoue ne pas être fan de ça... Je n'aime pas toucher aux bases qui sont gérées par des applis (on ne sait jamais quelles incidences cela peut avoir quand on ne maîtrise pas le code)

Merci.

**Comment by wouldsmina** [comment]
> Bon il y a la possibilité d'aller modifier la base directement, mais j'avoue ne pas être fan de ça... Je n'aime pas toucher aux bases qui sont gérées par des applis

Et tu as parfaitement raison, si il y a un ldap, l'email est systématiquement récupéré dessus.

Merci pour tout tes retours, cela nous sera certainement utile, même si nous aurions préféré les avoirs durant la beta :wink:

**Comment by prytoegrian** [comment]
Faire ce que @philippebaque demande requiert de modifier deux fichiers :  
* https://github.com/libertempo/web/blob/develop/App/ProtoControllers/HautResponsable/Utilisateur.php#L116L129
* https://github.com/libertempo/web/blob/pry/ajoutUser/App/Views/HautResponsable/Employe/Ajout.php#L45L51 (si le dev est fait après mon travail sur la branche `pry/ajoutUser`)

Mais en réalité, je me pose une question : si tu ne veux pas importer les données utilisateurs, pourquoi est-ce que tu ne décoches tout simplement pas l'option « Importer les utilisateurs » ?
