### ISSUE TITLE
Mondaran 1.11.1 - calendrier Couleurs des cases en fonction du type d'absence

### ISSUE THREAD

**Issue by philippebaque** [libertempo/web#709]
Bonsoir,

 Pour notre part nous étions satisfait du calendrier 1.9 (je ne veux pas rentrer dans le débat ou la polémique)

 Il avait l'avantage de mettre des couleurs en fonction du type de congés.
 Sur la version actuelle de Mondaran 1.11.1, il me semble que cette discrimination à disparu à l'exception des congés pas encore validés.

Si la question se pose +1 pour mettre en place un système équivalent à celui de la 1.9

(quand je dis +1 c'est +1 fois 50, car tous nos usagers le réclament)

Merci

**Comment by wouldsmina** [comment]
même réponse que #710. Merci.
