### ISSUE TITLE
Problème d'affichage des jours non travaillés dans le calendrier en v1.11.1

### ISSUE THREAD

**Issue by carolegimenez** [libertempo/web#710]
Bonjour,

En installant la v1.11.1, nous avons perdu la possibilité d'afficher dans le calendrier les demi-journées ou journées non travaillés de nos personnels qui ont des aménagements d'horaires ou qui travaillent à temps partiel. Nous étions avant en V1.9 et cela fonctionnait très bien. 
Ce manque est bloquant pour notre structure. Est-ce qu'il y aurait la possibilité d'avoir un patch pour modifier ceci?

De même, la différenciation des types de congés et d'absences par un code couleur dans le calendrier était très appréciée par nos responsables. C'est vraiment dommage d'avoir perdu aussi cela.

En vous remerciant d'avance pour votre réponse.

Serveur :
    Système [i.e. iOS8.1] : Debian 9.4
    Version de Libertempo :  1.11.1
    Version MySQL et PHP : mysql Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
    PHP 7.0.30-1~dotdeb+8.1 (cli) ( NTS )

**Comment by wouldsmina** [comment]
Bonjour,
Nous sommes conscient du besoin d'améliorer le calendrier. Tes demandes ont d'ailleurs déjà été formulé dans un autre ticket (que je ne retrouve pas :disappointed: mais il existe c'est sur! ). Malheureusement on ne peut s'avancer sur une date ou une version.
