### ISSUE TITLE
Échec de l'installation auto si le fichier de dernière version n'existe pas

### ISSUE THREAD

**Issue by prytoegrian** [libertempo/web#712]
**Décrivez le bug**
Suite à une montée en version via le nouvel installateur, il y a un cas d'erreur si le fichier `lt-last-version` n'existe pas.

**Pour reproduire**
Étapes de la reproduction du comportement :
1. Prérequis (rôle connecté, options de configuration, méthode de connexion, …) : LT 1.12 et le fichier `lt-last-version`  inexistant
2. Cliquer sur : Après avoir installé une première fois l'application ou l'avoir upgradé vers LT 1.12, faire un `make update`. Ça marche aussi en supprimant le fichier manuellement.
3. Constater l'erreur : Le make donne : 
```sh
Contrôles généraux…

Warning: file_get_contents(/tmp/lt-last-version): failed to open stream: No such file or directory in /var/www/web/App/Tools/update on line 17

Call Stack:
    0.0003     378328   1. {main}() /var/www/web/App/Tools/update:0
    0.0106    1638312   2. getVersionDerniereMiseAJour() /var/www/web/App/Tools/update:69
    0.0107    1658680   3. file_get_contents() /var/www/web/App/Tools/update:17

```

**Comportement attendu**
Cas d'échec propre si toute les maj ont été faite ou maj.

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] : Debian 9
 - Navigateur et version : Fx 60
 - Erreur dans la console : na.

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : Debian 9
 - Version de Libertempo : LT 1.12
 - Version MySQL et PHP : Mysql 5.7 / PHP 7.0
 - Erreur dans le log du serveur : na.

**Contexte additionnel**
Je pense que la séquence est mal codée (votre serviteur est un idiot). Si `$versionLastMaj` a une valeur, il n'est pas nécessaire d'ouvrir le fichier. Il est par contre nécessaire de vérifier que le fichier existe. Dans le cas contraire, on laissera le dernier cas retourner la valeur qu'il veut.

**Comment by wouldsmina** [comment]
Ce bug me donne une idée... `make check` pour vérifier les dépendances...

**Comment by prytoegrian** [comment]
Quand tu parles de dépendances, tu parles des dépendances composer / npm ?
Parce que mon objectif est de faire en sorte que make install installe directement les dépendances. Suite à quoi :
- on aura plus de vendors dans le repo
- les vérifications système seront faites par les utilisateurs eux-mêmes 

Mais tu pensais peut-être à autre chose ?

**Comment by wouldsmina** [comment]
Oui, je pensais plutôt aux modules d'apache et php (rewrite, php-curl, php-gettext), l'accès à mysql, l'accès à l'API...

**Comment by wouldsmina** [comment]
Pourquoi créer le fichier dans /tmp?

**Comment by prytoegrian** [comment]
Ce fichier n'est pas censé être important et est volatile. En effet, notre installateur se base sur la 1.8. Mais avant la 1.12, il n'y a pas le patch qui permet de stocker en db la valeur et sans cette valeur, on ne sait pas jusqu'où on a installé.

**Comment by wouldsmina** [comment]
`ldap_bind(): Unable to bind to server: Invalid credentials in /var/www/html/vendor/libertempo/api/Vendor/adldap2/adldap2/src/Connections/Ldap.php on line 287`

Pourtant le login est bon et il est bien transmis dans Ldap.php on line 287

Je cherche la source du problème...
