### ISSUE TITLE
Bug Base de Donnée après installation

### ISSUE THREAD

**Issue by elbertondu62** [libertempo/web#719]
**Décrivez le bug**
impossible de se connecter après installation fraîche de libertempo en version 1.11.1
le compte admin ne se connecte pas. Lors de la connexion à phpmyadmin sur la table conges_users, un message d'erreur apparaît.

**Pour reproduire**
Étapes de la reproduction du comportement :
Installation de libertempo 1.11.1 sur un serveur tout frais.

**Comportement attendu**
connexion à libertempo

**Copies d'écran**
`Warning in ./libraries/sql.lib.php#613
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/sql.lib.php#2128: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#2079: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'db_conges',
string 'conges_users',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `conges_users`',
NULL,
NULL,
)
./sql.php#221: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'db_conges',
string 'conges_users',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `conges_users`',
NULL,
NULL,
)`

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] : windows 10
 - Navigateur et version : chrome 69
 - Erreur dans la console : 

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : ubuntu 18.04
 - Version de Libertempo : 1.11.1
 - Version MySQL et PHP :5.7 php 7.2
 - Erreur dans le log du serveur :

**Comment by wouldsmina** [comment]
Bonjour @elbertondu62 
as tu bien suivi les [prérequis](http://libertempo.tuxfamily.org/documentation/prerequis/)?

Tu as certainement un problème d'accès à l'API, tu peux vérifier en allant à l'adresse http://tonserveurLT/api/hello_world
Tu devrais obtenir une réponse au format JSON comme suit : 
````
{"code":400,"status":"fail","message":"Bad Request","data":"Request Content-Type and Accept must be set on application\/json only"}
````

Si ce n'est pas le cas, ton vhost ou ta config apache n'est pas bonne.

**Comment by elbertondu62** [comment]
petit erreur dans le vhost.
Le message d'erreur est lié à phpmyadmin sur une version ancienne et php7.2. il faut mettre à jour phpmyadmin manuellement
