### ISSUE TITLE
Clôture exercice

### ISSUE THREAD

**Issue by jbilloue** [libertempo/web#722]
Bonjour,

Je suis sous Libertempo 1.8.1 et je souhaite clôturer un exercice.
Actuellement, je suis bloquer pour faire cette opération en mode RH car tous mes utilisateurs ont une croix rouge en face de leur nom dans la colonne "cloturer" (à l'exception des 5 nouveaux utilisateurs depuis la clôture de l'année dernière).
J'ai cherché dans l'historique des issues sur le git mais je ne trouve pas de réponses.

Avez-vous une piste d'explication et de déblocage ?

**Comment by jbilloue** [comment]
Je confirme que les utilisateurs ont déposés des congés depuis la dernière clôture, et pourtant ils ont une croix rouge.

Depuis la dernière clôture (l'année dernière) nous avons migré le serveur mais nous avons utilisé la procédure de backup/restore pour les données, donc je ne pense pas que cela vienne de ce point.

**Comment by wouldsmina** [comment]
Voici le [code source](https://github.com/libertempo/web/blob/develop/hr/Fonctions.php#L1788) qui vérifie si un employé peut changer d'exercice ou non : 
```PHP
if ($tab_current_user['num_exercice'] < $_SESSION['config']['num_exercice']) {
```

En clair si le numéro d'exercice de l'employé est inférieur au numéro d'exercice global (table conges_appli) alors on peut le changer d'exercice. 
Si t'es sur de ton coup, tu peux incrémenter la valeur conges_appli.num_exercice

**Comment by rayaa1991** [comment]
J'ai le même problème ou alors je ne comprend pas :
1) J'ai clôturé l'exercice pour un seul utilisateur (pour essayer).
2) Cet utilisateur "test" a fait une demande de congé que le responsable a accepté. 
3) J'aimerai maintenant de nouveau clôturer l'exercice mais pour l'ensemble des utilisateurs mais celui ci a une croix rouge ...

**Comment by wouldsmina** [comment]
salut @rayaa1991,

La réponse est [dans le code](https://github.com/libertempo/web/blob/develop/hr/Fonctions.php#L1651) ;)

**Comment by rayaa1991** [comment]
Salut wouldsmina,

//si le num d'exercice du user est < à celui de l'appli (il n'a pas encore été basculé): on peut le cocher ?

SI je comprend bien, je dois clôturer tous les autres user pour re denouveau pouvoir le clôturer (avec les tous les autres cette fois ci)?

**Comment by wouldsmina** [comment]
Oui, c'est tout a fait ça. Le user à un exercice d'avance sur les autres, il ne peux pas en avoir 2

**Comment by jbilloue** [comment]
Pour apporter une réponse à mon problème, je confirme que j'ai du modifier le $_SESSION['config']['num_exercice'] pour faire fonctionner la clôture.

Du coup, après avoir effectué la clôture, je constate que la variable $_SESSION['config']['num_exercice'] reste à la même valeur. Est ce normal ? Quand cette variable sera t'elle incrémentée pour faire une nouvelle clôture ?

**Comment by jbilloue** [comment]
Erreur de ma part effectivement, je confirme que j'ai bien modifié la valeur de conges_appli.num_exercice dans la base de données.

Toutefois, ma question reste la même, après avoir effectué la clôture, je constate que la variable conges_appli.num_exercice reste à la même valeur. Est ce normal ? Quand cette variable sera t'elle incrémentée pour faire une nouvelle clôture ?

**Comment by wouldsmina** [comment]
Nooma va proposer une nouvelle procédure de clôture d'exercice. Si ton problème persiste dans cette version ouvre à nouveau ce ticket.
++
