### ISSUE TITLE
Couleurs pour les congés / absences

### ISSUE THREAD

**Issue by sig-pnrnm** [libertempo/web#735]
Bonjour,

Désolé si cette option a déjà été proposée, voire même si elle est déjà possible.
Je trouverais pertinent que les types de congés / absences soient associés à des codes couleurs paramétrables en admin.
Je vois que vous utilisez aussi la bibliothèque Bootstrap.
Les badges de Bootstrap permettraient de faire cela assez proprement : 

![libertempo_absences](https://user-images.githubusercontent.com/26482054/47363445-1bf2a680-d6d7-11e8-97d0-1f1bba0445ea.png)

Exemple en JSFiddle : https://jsfiddle.net/qj25nhfr/

Bravo à tous pour vos développements !

**Comment by wouldsmina** [comment]
Bonjour, c'est en cours de discussion sur #725 (en anglais)
