### ISSUE TITLE
Installation sur serveur avec un port

### ISSUE THREAD

**Issue by Nath73** [libertempo/web#743]
Bonjour,
Je voudrais installer libertempo sur un serveur mysql pour lequel un port est obligatoire.
Comment faire ? merci d'avance
Nathalie

**Comment by wouldsmina** [comment]
Bonjour @Nath73,
Dans le fichier cfg/dbconnect.php il te suffit d'ajouter le port après le serveur.
A+

**Comment by Nath73** [comment]
Bonjour,
J'ai écrit comme cela $mysql_serveur="bf1389-001.privatesql:35765" ;
Puis j'ai pu accéder à la page d'install. J'ai d'abord eu ce message file  : /home/geoi/sites/eidra/eid-gestion
/libertempo/includes/SQL.php
line  : 86
fx    : $SQL->query
error : Table 'eid_db_conges.conges_config' doesn't exist
sql   : SELECT * FROM conges_config ORDER BY conf_groupe
J'ai cliqué sur "Nouvelle installation"
J'arrive ensuite sur la page de login
Je tape login : admin, mdp : reponsable et j'obtiens une erreur "nom utilisateur/mdp incorrect"
alors que les tables ont bien été créées et la ligne admin existe bien dans conges_users
Nathalie

**Comment by Nath73** [comment]
J'ai "récupéré" un user sur mon serveur local et l'ai enregistré directement ds la table conges_users via phpmyadmin (J'avais installé Libertempo sur mon serveur local avant d'essayer de l'installer sur un serveur distant) --> pas mieux, même message d'erreur. On dirait qu'on arrive pas à accéder à la base , ce qui est étrange puisque l'installation s'est bien effectuée

**Comment by wouldsmina** [comment]
Ça ressemble à un problème d'accès a l'api. Vérifie que tu as bien tout les prérequis en particulier rewrite et php-curl et que ton vhost est bien configuré.

**Comment by wouldsmina** [comment]
Pour savoir si l'api répond bien, tu dois obtenir la même réponse que sur la démo : http://demo.libertempo.fr/api/hello_world

**Comment by Nath73** [comment]
J'obtiens cela: (la meme chose que sur la page dont tu m'as donné le lien)

code | 400
-- | --
status | "fail"
message | "Bad Request"
data | "Request Content-Type and…n application/json only"

**Comment by wouldsmina** [comment]
Ok. Vérifie le fichier vendor/libertempo/libertempo-api/configuration.json s'il contient bien les accès à la base de données avec le port.

**Comment by Nath73** [comment]
oui {"db":{"serveur":"bf1389-001.privatesql:35765","base":"###","utilisateur":"###","mot_de_passe":"###"}}

**Comment by Nath73** [comment]
pour les autres pré requis, je demande à mon hebergeur, mais je suppose que c'est ok vu la réponse hello world

**Comment by wouldsmina** [comment]
peux tu tester l'API à l'aide de l'extension RESTED (sur firefox ou chrome)? 
![rested](https://user-images.githubusercontent.com/12614881/47993608-29089000-e0f0-11e8-8ec9-924809e37ad9.png)

**Comment by Nath73** [comment]
je l'ai installé ms je vois pas comment la lancer .... un peu nulle

**Comment by wouldsmina** [comment]
Tu dois avoir un icone </> en haut a droite de ton navigateur.

**Comment by Nath73** [comment]
ok, voici la réponse
Response (0.195s) - http://eid-gestion2.geo2i.com/libertempo/index.php
200 OK

**Comment by Nath73** [comment]
![screen shot 11-05-18 at 12 06 pm](https://user-images.githubusercontent.com/43165789/47994676-5c98e980-e0f3-11e8-912c-abb41a84242d.PNG)

**Comment by wouldsmina** [comment]
J'ai oublié de préciser qu'il faut saisir les mêmes infos que sur ma capture.

**Comment by Nath73** [comment]
![screen shot 11-05-18 at 01 19 pm](https://user-images.githubusercontent.com/43165789/47997828-7dfed300-e0fd-11e8-8af5-ad1f2efb669d.PNG)

**Comment by Nath73** [comment]
désolée, j'ai oublié un paramètre

**Comment by wouldsmina** [comment]
C'est parce que tu ne tape pas sur la bonne adresse

**Comment by wouldsmina** [comment]
On a déja rencontré ce problème auparavant, mais je ne retrouve pas le ticket à ce sujet :/ de mémoire, ta configuration d'apache filtre le header "authorization".

**Comment by wouldsmina** [comment]
c'est bon, j'ai retrouvé l'info : https://github.com/libertempo/web/issues/700#issuecomment-423068540

**Comment by Nath73** [comment]
j'ai du mal à comprendre ce que je dois faire du coup...
Modifier le .htaccess comme dit ici https://docs.holodyn.com/KnowledgeBase/Hosting/Apache/PHP_FastCGI_Authentication_Headers

**Comment by wouldsmina** [comment]
ça dépend de ta configuration, mais je pense qu'il vaut mieux paramétrer ça dans le vhost

**Comment by wouldsmina** [comment]
perso je tenterais `CGIPassAuth on` dans le vhost 👍

**Comment by Nath73** [comment]
je demande ça à mon hébergeur...

**Comment by wouldsmina** [comment]
tu héberges sur du dédié ou du mutualisé? si c'est le second, il faudra passer par .htaccess à coup sur

**Comment by Nath73** [comment]
en attendant, j'ai modifié le .htaccess comme ceci, ms ça ne change rien
`<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ /libertempo/vendor/Libertempo/libertempo-api/Public/ [QSA,L]
	RewriteCond %{HTTP:Authorization} ^(.+)
	RewriteRule ^(.*)$ $1 [E=HTTP_AUTHORIZATION:%1,PT]
</IfModule>`

**Comment by Nath73** [comment]
sur du mutualisé chez ovh

**Comment by wouldsmina** [comment]
alors, il faut plutôt ajouter ça dans un .htaccess : 
````
RewriteCond %{HTTP:Authorization} ^(.+)
RewriteRule ^(.*)$ $1 [E=HTTP_AUTHORIZATION:%1,PT]
````

Étant donné que le problème vient du serveur, je ne saurai t'aider plus...

**Comment by Nath73** [comment]
je me permets une dernière question : faut-il garder les autres lignes du htaccess?

**Comment by Nath73** [comment]
merci pour tout le temps que tu m'as accordé

**Comment by wouldsmina** [comment]
> faut-il garder les autres lignes du htaccess?

oui, sinon l'api ne répondra plus.

**Comment by Nath73** [comment]
Bonjour,
J'ai essayé plusieurs choses ds le .htaccess mais rien ne fonctionne, et j'arrive au message 404 Not Found selon les modif...
Quelqu'un a t'il trouvé un .htaccess qui corrige ce problème de headers ?
Merci

**Comment by Nath73** [comment]
Merci, c'est fait
