### ISSUE TITLE
Installation 1.12

### ISSUE THREAD

**Issue by ImWanted** [libertempo/web#766]
Bonjour, 
Ce n'est pas réellement un bug mais plutôt une demande d'information, j'essaye d'installer la 1.12 sur un Debian et lors de l'installation on me demande une "adresse web :" pour joindre mon application je suppose mais lorsque je renseigne "http://localhost/Libertempo" il me valide mon choix ensuite je doit créer un utilisateur puis l'installation est terminer. Cependant je n'arrive pas à accéder a l'interface de Libertempo.

Je tient a dire que je n'ai aucun message d'erreur tout est bien installer je voudrais simplement savoir ce que je doit renseigner dans "adresse web" et comment je peux accéder a Libertempo ensuite.

En vous remerciant.

**Comment by prytoegrian** [comment]
Hello,

pour commencer, sache que la 1.12 est la version qui vient de sortir, elle est encore en beta. Nous n'avons pas encore eu de retour de bug, mais je tenais à le préciser.

Ensuite, je suppose que tu as suivi [cette documentation](http://libertempo.tuxfamily.org/documentation/installation/) pour arriver au `make`. Au moment où il installe l'application, il a besoin du nom du site sur lequel il a installé libertempo mais ce n'est qu'une configuration stockée dans sa base interne, ça ne te dispense pas de créer un vhost (http://libertempo.tuxfamily.org/documentation/prerequis/).
En effet, seul le vhost va dire à apache où se trouve ton appli sur le disque et même si LT est bien installé, sans lui, rien ni personne ne pourra y accéder. En saisissant comme adresse web du make : `http://{ServerNameDuVHost}/` tu devrais retomber sur tes pattes.

Bonus : si tu es en local, puisqu'il n'y a pas de DNS qui rentrent en jeu, il te faut aussi ajouter dans le fichier `/etc/hosts` : 
```
127.0.0.1 {ServerNameDuVHost}
```
Si c'est pour du test, nous avons mis en place [un docker](https://github.com/libertempo/docker) qui fait le travail pour toi.

**Comment by ImWanted** [comment]
Excusez moi du retard,
Effectivement j'avais complètement oublier de réaliser le vhost :)
En te remerciant tout fonctionne 👍

**Comment by ImWanted** [comment]
Juste un autre problème impossible de me connecter en admin / responsable
Je me suis donc rendue dans la BDD et j'ai vue que j'avais un seul utilisateur dans la table conges_users qui est lcler1 -> mon identifiant que j'ai paramétrer seulement impossible de me connecter via cette utilisateurs, si vous pouviez m'envoyer l'utilisateur admin que je puisse l'ajouter dans ma BDD afin de pouvoir m'authentifier je vous en remercie.

**Comment by prytoegrian** [comment]
Salut. On va faire encore mieux : tape `make createHR` dans la console pour créer un autre utilisateur pour te connecter. Dans un deuxième temps, tu pourras supprimer le compte qui ne te permet plus de t'authentifier.

**Comment by wouldsmina** [comment]
Salut,
Si tu n'arrive toujours pas à te connecter, tu as certainement un problème d'API...
Tu obtiens quoi a l'adresse http://tonserveur/api/authentification

**Comment by ImWanted** [comment]
Merci de vos réponses effectivement j'ai un code 400 avec un Bad request
Data : "Request Content -Type and accept must be set on application/json only"

**Comment by wouldsmina** [comment]
Erreur 400 est normal depuis le navigateur, ce serait une erreur 404 qui aurait été problématique.
Donc les conseils de Prytoegrian devrait suffir à corriger ton problème. 
Si le problème persiste, on ne pourra pas t'aider plus si tu ne nous donne pas plus d'infos sur ta config (cf le formulaire lors de la création d'un nouveau ticket).

**Comment by ImWanted** [comment]
**Décrivez le bug**
Je ne peux pas m'authentifier a l'interface libertempo.

**Pour reproduire**
Étapes de la reproduction du comportement :
1. Prérequis (rôle connecté, options de configuration, méthode de connexion, …) : aller sur la page de connexion
2. Cliquer sur : Valider
3. Constater l'erreur : ERREUR : Nom d'utilisateur et/ou mot de passe incorrect !!!

**Comportement attendu**
Une description claire et concise de l'attendu.
Je devrais accéder a l'interface de la solution

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] : Debian 9 64 bit
 - Navigateur et version : Firefox
 - Erreur dans la console : 

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : Debian 9 64 bit
 - Version de Libertempo : 1.12
 - Version MySQL et PHP : php 7.0.33 / MySQL 10.1.37
 - Erreur dans le log du serveur :

**Comment by prytoegrian** [comment]
Tu utilises LDAP, SSO ou un truc du genre ?
As-tu essayé avec la version 1.11 ?

**Comment by ImWanted** [comment]
Non j'utilise juste la BDD.
Non j'ai voulut tester la 1.12 directement.
Je voulais la tester afin de savoir si on pouvais faire une extraction des congés pris par les utilisateurs afin de les renvoyer vers la compta ?

**Comment by wouldsmina** [comment]
@ImWanted Pourrais tu tester l'API à l'aide du plugin RESTED (dispo sur firefox et chrome), comme sur cette capture : 
![capture d ecran du 2019-01-23 10-50-58](https://user-images.githubusercontent.com/12614881/52218713-8224c300-289b-11e9-8d44-51292a2fc1cd.png)

**Comment by ImWanted** [comment]
Bonjour,
je viens de tester avec l'application RESTED j'ai une réponse 200 OK
Qui est exactement comme votre page.
En attente de vos recommendations

**Comment by wouldsmina** [comment]
Tu test en local? Si c'est le cas, tu dois déclarer le nom de domaine dans /etc/hosts

**Comment by ImWanted** [comment]
Oui je suis bien en local j’accède a la page de connexion mais lorsque j'essaie de me connecter impossible.
Je n'ai rien touché dans le host de etc puisque j’accède a Libertempo directement via localhost.
j'ai jeté un oeil dans les fichier hosts et dans le host.conf mais je ne vois rien d'anormal.

**Comment by wouldsmina** [comment]
Tu as mis quoi dans serverName dans le virtualhost d'apache?

**Comment by ImWanted** [comment]
J'ai mit libertempo

**Comment by wouldsmina** [comment]
Alors tu dois déclarer le nom «libertempo» dans /etc/hosts

**Comment by wouldsmina** [comment]
@ImWanted je pense que ton problème vient de la. Si ce n'est pas le cas, fait moi signe.
a+

**Comment by wouldsmina** [comment]
pas de nouvelle, bonne nouvelle!
