### ISSUE TITLE
impossible de se logger à l'installation

### ISSUE THREAD

**Issue by mda34** [libertempo/web#781]
Bonjour

Après installation en local ubuntu 18.04.1, impossible de se connecter avec les identifiants
admin/resposnables
j'ai l'erreur suivante

```
login : 
uri   : /Libertempo/index.php
dump  : dump/sql_2019-01-09T16:29:16+01:00.dump
file  : /var/www/html/Libertempo/includes/SQL.php
line  : 55
fx    : $SQL->query
error : Your password does not satisfy the current policy requirements
sql   : SELECT u_passwd   FROM conges_users   WHERE u_login="admin" AND ( u_passwd='5f120a7b838c6f3fa9cc0021dfda244b' OR u_passwd=PASSWORD("resposnable") ) 
```
sql serveur 5.7
PHP 7.0.33-1+ubuntu18.04.1+deb.sury.org+1 

Merci de vos lumières

**Comment by prytoegrian** [comment]
Bonjour. Au moment de créer un rapport de bug, il vous est demandé de remplir quelques informations pour nous aider à comprendre plus vite votre problème, et donc le corriger rapidement aussi, car sans informations nous aidant à le reproduire, votre bug restera lettre morte.

Merci de remplir ces informations : 
```**Décrivez le bug**
Une description claire et concise de la nature du bug.

**Pour reproduire**
Étapes de la reproduction du comportement :
1. Prérequis (rôle connecté, options de configuration, méthode de connexion, …) :
2. Cliquer sur : 
3. Constater l'erreur : 

**Comportement attendu**
Une description claire et concise de l'attendu.

**Copies d'écran**
Si applicable, ajoutez des captures d'écran pour aider à expliquer le problème.

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] :
 - Navigateur et version : 
 - Erreur dans la console : 

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] :
 - Version de Libertempo : 
 - Version MySQL et PHP :
 - Erreur dans le log du serveur : 

**Contexte additionnel**
Ajoutez tout ce qui vous paraît utile pour la bonne résolution du défaut.
```

@mda34 : je penche pour une typo dans la saisie : 
> sql   : SELECT u_passwd   FROM conges_users   WHERE u_login="admin" AND ( u_passwd='5f120a7b838c6f3fa9cc0021dfda244b' OR u_passwd=PASSWORD("***resposnable***") )

**Comment by mda34** [comment]
J'ai installé cette version Libertempo 1.11.1 Mondaran et vous ?

**Comment by mda34** [comment]
> Bonjour,
> 
> J'ai le même problème. Quelqu'un a une solution ?

J'ai installé cette version Libertempo 1.11.1 Mondaran et vous ?

**Comment by mda34** [comment]
> Pour te sortir de ce mauvais pas facilement, je te propose de modifier le mot de passe de l'admin directement dans la base de donnée, table conges_users. le mot de passe doit être encodé avec la fonction `PASSWORD()` de mysql.

Je viens de faire directement la requête sql via phpmyadmin

`UPDATE `conges_users` SET `u_passwd` = PASSWORD('636d61cf9094a62a81836f3737d9c0da') WHERE `conges_users`.`u_login` = CAST(0x61646d696e AS BINARY)`
Mais toujours erreur
```
MySQL a répondu: Documentation#1819 - 
Your password does not satisfy the current policy requirements
```

**Comment by wouldsmina** [comment]
le mot de passe dans PASSWORD() doit être en clair. ou alors tu saisi 636d61cf9094a62a81836f3737d9c0da en guise de mot de passe...
Pour plus d'infos [RTFM](https://dev.mysql.com/doc/refman/5.6/en/validate-password.html) :)
