### ISSUE TITLE
calendriers des membres du groupe ne remontent pas.

### ISSUE THREAD

**Issue by JLaviron** [libertempo/web#783]
Bonjour,

Je rencontre un problème avec les calendriers : certains utilisateurs ne voient pas les calendriers des membres de leurs groupes.

J'ai un groupe Achats avec deux utilisateurs et un responsable.
L'utilisateur 1 voit son calendrier et celui de l'utilisateur 2 (et pas le responsable ce qui est normal)
L'utilisateur 2 ne voit pas de calendrier du groupe.

J'ajoute parce que je suppose que le problème vient de là : 
L'utilisateur 2 est responsable d'un autre groupe (Magasin) et voit bien les calendriers des membres.

J'ai fait différents tests pour essayer de trouver d'où venait le problème : 
- J'ai rajouté mon compte (qui est responsable du groupe Informatique) au groupe Achat et les calendriers ne remontent pas.
- j'ai rajouté un compte utilisateur standard au groupe Achat, il voit bien tous les calendriers.
- j'ai ensuite passé ce même utilisateur responsable d'un autre groupe et il à tout de suite perdu la vue sur les calendriers du groupe Achats.

Voici pour la partie "Simple" du problème : en faisant mes tests j'ai trouvé d'autres comportements bizarres.

Voici la liste des différents groupes dans l'entreprise
![groupes-libertempo](https://user-images.githubusercontent.com/46715553/51186742-a283e200-18da-11e9-85bc-daa1826a2aee.png)

-Si je rajoute mon compte (responsable donc) dans un (ou plusieurs) des 3 derniers groupes, je récupère bien tous les calendriers.
-Si je rajoute mon compte dans un autre groupe, je n'ai rien qui remonte.
-Si je rajoute mon compte dans deux (ou plus) des autres groupes, j'ai les calendriers du (ou des) groupes les plus bas dans la liste qui remontent

Voilà pour les informations que j'ai pu récupérer, j'espère que c'est suffisamment compréhensible.

Merci pour votre aide et n'hésitez pas à me demander des informations supplémentaires si besoin.

**Poste :**
 - Système [i.e. iOS] : Windows 7 ou 10
 - Navigateur et version : testé avec IE, Edge, et firefox
 - Erreur dans la console : 

**Serveur :**
 - Système [i.e. iOS8.1] : Debian 8
 - Version de Libertempo : 1.10
 - Version MySQL et PHP : MySQL : 14.14 dist 5.7.20 PHP :  5.6.30
 - Erreur dans le log du serveur :

**Comment by wouldsmina** [comment]
salut @JLaviron et merci pour ces détails. Si je comprend bien, à partir du moment ou un utilisateur est responsable d'un groupe, il ne voit plus les groupes dont il est simplement membre. C'est bien ça?

**Comment by wouldsmina** [comment]
pas simple à comprendre ce bug :disappointed_relieved: je vais essayer de reproduire sur la démo pour mieux comprendre.

**Comment by JLaviron** [comment]
effectivement, c'est pas simple :). 
Merci en tout cas de prendre le temps de regarder

**Comment by sbdUPJV** [comment]
perso j'ai eu le problème.
J'ai modifié la fonction getListeGroupesVisibles de ProtoControllerS\Utilisateurs.php
J'ai changé 
$groupesVisibles = $groupesResponsable + $groupesGrandResponsable + $groupesEmploye;
par 
$groupesVisibles = array_merge($groupesResponsable, $groupesGrandResponsable, $groupesEmploye);
Le + ne gardant q'une occurence de clé identique, ce qui retirait certains groupes

**Comment by wouldsmina** [comment]
C'est corrigé dans Akhaten :)

**Comment by JLaviron** [comment]
ça fonctionne !
merci beaucoup !
