### ISSUE TITLE
Identifiant refusés après redirection http > https

### ISSUE THREAD

**Issue by hydrofyse** [libertempo/web#791]
**Décrivez le bug**
Une fois le champs URL_ACCUEIL_CONGES remplis avec une adresse en https le site deviens inaccesible.

**Pour reproduire**
Étapes de la reproduction du comportement :
1. L'application a été installé avec URL_ACCUEIL_CONGES = http://x.x.x.x (où x.x.x.x est une ip privée. Les utilisateurs accèdes actuellement au site via son de domaine et ne rencontrent pas de soucis
2. Modification de la configurations du virtual host apache pour prendre en compte l'https (configuration disponible plus bas). 
3. Modifications de l'url d'accueil avec https et le nom de domaine URL_ACCUEIL_CONGES = https://conges.domaine.test
4. Tentative de connexion avec le compte admin, accés refusé

**Poste client**
Le problème de connexion est rencontré sur tout les navigateurs testés.

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : Ubuntu 16.04
 - Version de Libertempo : 1.12
 - Version MySQL et PHP : Mysql 10.0.36 et PHP 7

**Contexte additionnel**
La méthode de connexion utilisé est "dbconges"

Le champs URL_ACCUEIL_CONGES a également été testé avec les valeurs suivantes : "https://ip.publique", "http://ip.publique" et "http://conges.domain.test" 

Configuration apache

<VirtualHost *:80>
    ServerName conges.domaine.test

    RewriteEngine on
    RewriteCond %{HTTPS} !on
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

</VirtualHost>

<VirtualHost *:443>
    ServerName conges.domaine.test
    DocumentRoot /var/www/libertempo

    <Directory /var/www/libertempo>
        RewriteEngine On
        RewriteBase /
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^api/(.*)$ vendor/libertempo/api/Public/index.php [QSA,L]
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^(.*)$ Public/index.php [QSA,L]
    </Directory>
    <Directory /var/www/libertempo/vendor/libertempo/api>
        <Files "configuration.json">
                Order Allow,Deny
                Deny from all
        </Files>
    </Directory>

    SSLEngine On
    SSLCertificateFile /etc/letsencrypt/live/conges.domaine.test/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/conges.domaine.test/privkey.pem
</VirtualHost>

Je m'excuse de ne pas pouvoir fournir certaines informations suplémentaire, le site étant déjà en production il ne m'est pas facile de reproduire le problème durant la journée.

Cordialement

**Comment by wouldsmina** [comment]
Bonjour @hydrofyse,
Je viens de tester et en effet, le rewrite ne fonctionne pas très bien en https.
Merci.

**Comment by wouldsmina** [comment]
Finalement, ce n'est peut etre pas un problème de rewrite, ma config en ssl n'était pas bonne. la [démo](https://demo.libertempo.fr) fonctionne actuellement en ssl. Peux tu interroger l'API (en https) comme dans la capture suivante?
![capture d ecran du 2019-01-23 10-50-58](https://user-images.githubusercontent.com/12614881/52220482-4855bb80-289f-11e9-87f1-c61ca9282bb1.png)

**Comment by wouldsmina** [comment]
Regarde aussi dans les logs si tu n'as pas d'erreur. Je pense que ta section <VirtualHost *:80> ne doit pas plaire à l'API...

**Comment by hydrofyse** [comment]
Merci pour ta réponse rapide, je m'excuse de ne pas pouvoir avoir donner de retour rapidement, je dois attendre le soir pour maniper sur la prod.

Le premier virtualhost posait effectivement soucis, je peux parfaitement me connecter une fois ce dernier remplacé par une configuration valide, cependant URL_ACCUEIL_CONGES vaut toujours http://x.x.x.x

Une fois passé sur https://conges.domaine.test j'obtiens le même problème. La requète vers l'api me retourne bien un 200 mais quand j'essaye de me connecter via le web j'ai "ERREUR : Nom d'utilisateur et/ou mot de passe incorrect !!!" 

Coté interface, j'ai la page qui charge pendant un long moment (plus d'une minute) avant de m'afficher le message d'erreur
Coté log apache, pendant que la page charge en boucle, j'ai plusieurs fois les même requêtes jusqu'à l'apparation du message d'erreur sur la page web :

conges.domaine.fr:443 x.x.x.x - - [04/Feb/2019:22:28:17 +0100] "POST / HTTP/1.1" 200 4089 "https://conges.ville-avallon.fr/" "Agent"

Mais pas de log d'erreur

Petite question  qui n'a rien à voir mais j'ai essayé plusieurs fois de modifié URL_ACCUEIL_CONGES à l'aide de make reconfigure, mais je n'ai pas reussi à trouver la bonne syntaxe, serait-il possible de l'avoir ?

Ce n'est plus vraiment un problème pour moi, tant que le traffic est bien en https =)
Cependant si cela est réellement un bug, sa serait volontier pour tester un peu voir ce qui ne va pas

**Comment by wouldsmina** [comment]
Non, ce n'est pas un bug à proprement dit.
Make configure t'affiche la liste des options puis un exemple :
`make configure option=URL_ACCUEIL_CONGES valeur=https://domaine.fr/`

**Comment by wouldsmina** [comment]
> Ce n'est plus vraiment un problème pour moi, tant que le traffic est bien en https =)

Tu as réussi a configurer ton vhost en https?

**Comment by wouldsmina** [comment]
ping @hydrofyse

**Comment by hydrofyse** [comment]
My bad, je n'étais plus sur le sujet actuellement.
L'https est fonctionel quand j'y accède directement via https://conges.domaine.test
Cependant des que je configure mon <VirtualHost *:80> avec un _redirect_ vers <VirtualHost *:443> j'ai le même problème qui survient.

Je n'ai pas trouvé de solution où l'application ne me refuse pas l'accés quand le traffic http est redirigés vers l'https.

**Comment by wouldsmina** [comment]
ok! :)

**Comment by hydrofyse** [comment]
J'ai essayé en retirant le virtual host http pour ne laisser que l'https d'actif, le problème est toujours le même dans cette configuration, j'accède bien à la page de login mais après impossible de s'authentifier 

Cordialement

**Comment by wouldsmina** [comment]
Je viens d'appliquer la règle suivante sur le vhost:80 de la démo : 
`        Redirect permanent "/" "https://demo.libertempo.fr/"`

ça m'a l'air fonctionnel... dit moi ce que ça donne de ton coté.
a+

**Comment by wouldsmina** [comment]
@hydrofyse, n'ayant pas constaté de problème global et n'ayant pas de nouvelle de toi, je clos le ticket. N'hésite pas à réagir si besoin ;)
