### ISSUE TITLE
Heures additionelles

### ISSUE THREAD

**Issue by Nath73** [libertempo/web#795]
**Décrivez le bug**
Bonjour,

J'essaie de déposer une demande d'heure additionnelle (8h -12h), mais cela ne fonctionne pas
Des erreurs sont apparues, veuillez recommencer

    Durée : la durée est nulle

**Pour reproduire**
J'ai essayé sur un utilisateur standard, et avec un utilisateur ayant les roles admin, RH
Et aussi plusieurs créneaux. Les utilisateurs avaient bien un planning

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] : windows 10
 - Navigateur et version : firefox 65
 - Erreur dans la console : 

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : installation en local sur mon pc pour test
 - Version de Libertempo : 1.11
 - Version MySQL et PHP : php 5.6, Mysql 5.7
 - Erreur dans le log du serveur : 

Merci,

Nathalie

**Comment by wouldsmina** [comment]
Bonjour @Nath73 
désolé pour le temps de réponse. les heures additionnelles se font en dehors des heures de travail. vérifie le planning de l'utilisateur.
