### ISSUE TITLE
Migration : Erreur de connexion sur tous les comptes

### ISSUE THREAD

**Issue by LeSeb93** [libertempo/web#799]
Depuis la migration de la version 1.10 Kantra à la version 1.11 Mondaran, aucun des utilisateurs ne peut se connecter à leur interface.

Libertempo installé sur Windows 2012, sur WAMP.

**Comment by wouldsmina** [comment]
Salut @LeSeb93 
Le passage vers la version 1.11 nécessite une modification dans le vhost d'apache. 
Tu as corrigé ton soucis ou tu es revenu à la version 1.10?
