### ISSUE TITLE
Loose Camparision lors de l'export

### ISSUE THREAD

**Issue by Areizen** [libertempo/web#817]
## Description
Dans le cas ou le hash du login d'un utilisateur commence par 0e, il est possible d'exporter son calendrier depuis un autre utilisateur

## Mise en évidence
https://github.com/libertempo/web/blob/de936e75272c7386c79eb91723be94317216f4a6/includes/fonction.php#L361

Le contrôle se fait par une comparaison utilisant `==` or si le hash commence par 0e il va etre converti en entier pour la comparaison.

## Remediation

Utiliser `===` pour les comparaisons

## References :
https://www.owasp.org/images/6/6b/PHPMagicTricks-TypeJuggling.pdf

**Comment by prytoegrian** [comment]
Salut, merci de ta contribution. Tu as l'air d'avoir bien étudié la question, tu t'y colles ?
Je pense pas qu'il y ai d'effet de bord, c'est relativement facile à tester.
