### ISSUE TITLE
Impossible d'éditer ou ajouter users via IHM ?

### ISSUE THREAD

**Issue by apio-sys** [libertempo/web#821]
Sur une install fresh 1.12 impossible d'éditer un utilisateur ou en ajouter un via l'IHM. Lors de la validation je retrouve ces erreurs dans le log Apache :

> [Fri` May 03 09:40:08.137867 2019] [:error] [pid 3102] [client 172.50.2.214:10312] PHP Warning:  implode(): Invalid arguments passed in /var/www/html/App/ProtoControllers/HautResponsable/Utilisateur.php on line 870, referer: `https://libertempo.keepcoolpro.fr/hr/hr_index.php?onglet=modif_user&login=[username]

> [Fri May 03 09:40:08.138731 2019] [:error] [pid 3102] [client 172.50.2.214:10312] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /var/www/html/includes/SQL.php:163\nStack trace:\n#0 /var/www/html/includes/SQL.php(163): mysqli->real_query('REPLACE INTO co...')\n#1 [internal function]: includes\\Database->query('REPLACE INTO co...')\n#2 /var/www/html/includes/SQL.php(104): call_user_func_array(Array, Array)\n#3 /var/www/html/App/ProtoControllers/HautResponsable/Utilisateur.php(871): includes\\SQL->__call('query', Array)\n#4 /var/www/html/App/ProtoControllers/HautResponsable/Utilisateur.php(812): App\\ProtoControllers\\HautResponsable\\Utilisateur::updateSoldeUtilisateur(Array, Object(includes\\SQL))\n#5 /var/www/html/App/ProtoControllers/HautResponsable/Utilisateur.php(479): App\\ProtoControllers\\HautResponsable\\Utilisateur::putUtilisateur(Array, Array)\n#6 /var/www/html/App/ProtoControllers/HautResponsable/Utilisateur.php(63): App\\ProtoControllers\\HautResponsable\\Utilisat in /var/www/html/includes/SQL.php on line 163, referer: https://libertempo.keepcoolpro.fr/hr/hr_index.php?onglet=modif_user&login=[username]`

Cette version ne tourne pas en Debian 9 avec sa version php officielle 7.0.33 ?

Joris.

**Comment by wouldsmina** [comment]
bonjour @apio-sys,
Désolé pour le temps de réponse. As tu trouvé la raison de ce bug ?

**Comment by apio-sys** [comment]
Merci pour ton retour @wouldsmina . Non pas eu le temps de m'y remettre après. Et bcp de choses ont changé depuis. Je testerai prochainement sur un Debian 10 "boxfresh" avec PHP 7.3. Je reposterai ensuite au besoin.

Merci,

Joris.
