### ISSUE TITLE
Bonjour!  quand je fais un ek check, j'obtiens: l'API semble inaccessible 

### ISSUE THREAD

**Issue by AntsaHerisoa** [libertempo/web#823]
**Décrivez le bug**
Une description claire et concise de la nature du bug.

**Pour reproduire**
Étapes de la reproduction du comportement :
1. Prérequis (rôle connecté, options de configuration, méthode de connexion, …) :
2. Cliquer sur : 
3. Constater l'erreur : 

**Comportement attendu**
Une description claire et concise de l'attendu.

**Copies d'écran**
Si applicable, ajoutez des captures d'écran pour aider à expliquer le problème.

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] :
 - Navigateur et version : 
 - Erreur dans la console : 

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] :
 - Version de Libertempo : 
 - Version MySQL et PHP :
 - Erreur dans le log du serveur : 

**Contexte additionnel**
Ajoutez tout ce qui vous paraît utile pour la bonne résolution du défaut.

**Comment by wouldsmina** [comment]
Bonjour! Tu peux pas faire plus court! :D
Assure toi d'avoir bien suivi les prérequis dans la documentation. En particulier le paramétrage du module rewrite d'apache.
