### ISSUE TITLE
Haut responsable accès page de gestion des groupes

### ISSUE THREAD

**Issue by Mistermuggles** [libertempo/web#834]
**Décrivez le bug**
Un responsable RH (haut responsable) ne peut accéder à liste des groupes en cliquant sur "Groupes" dans le menu latéral.

**Pour reproduire**
Étapes de la reproduction du comportement :
1. Créer un utilisateur avec le rôle RH (pas admin)
2. Cliquer sur : Groupes dans le menu latéral
3. Constater l'erreur : La page ne s'affiche pas et produit le message d'erreur suivant : 
```
Fatal error:  Uncaught LogicException: Erreur client : Request -> GET //api/groupe HTTP/1.1
User-Agent: GuzzleHttp/6.2.1 curl/7.58.0 PHP/7.3.6-1+ubuntu18.04.1+deb.sury.org+1
Host: demo.libertempo.fr
Token: $2y$10$wSzNQNGjKL./6nFTn..aQuRnXpFVBwnsnWX3Cdxls5nDJRvdFZA5W
Content-Type: application/json
Accept: application/json

 | Response <- HTTP/1.1 401 Unauthorized
Date: Fri, 21 Jun 2019 13:38:26 GMT
Server: Apache/2.4.29 (Ubuntu)
Content-Length: 74
Content-Type: application/json;charset=utf-8

{"code":401,"status":"fail","message":"Unauthorized","data":"Bad API Key"} in /home/reynardt/php/libertempo_112/App/Libraries/ApiClient.php:140
Stack trace:
#0 /home/reynardt/php/libertempo_112/App/Libraries/ApiClient.php(63): App\Libraries\ApiClient->request('GET', 'groupe', Array)
#1 /home/reynardt/php/libertempo_112/App/Libraries/ApiClient.php(45): App\Libraries\ApiClient->securedRequest('GET', 'groupe', '$2y$10$wSzNQNGj...')
#2 /home/reynardt/php/libertempo_112/hr/hr_liste_groupe.php(40): App\Libraries\ApiClient->get(' in /home/reynardt/php/libertempo_112/App/Libraries/ApiClient.php on line 140
```

**Comportement attendu**
La page est supposée afficher la liste des groupes et permettre d'intéragir avec ceux-ci.

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] : Ubuntu 18.0.4
 - Navigateur et version : 67.0.3
 - Erreur dans la console : 

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] :apache2
 - Version de Libertempo : 1.12
 - Version MySQL et PHP : php 7.3 / 10.1.40-MariaDB
 - Erreur dans le log du serveur : 

**Contexte additionnel**
Lorsque l'on change dans l'URL "liste_groupe" par "ajout_groupe" on accède à la page d'ajout de groupe normalement.
Il semblerait que le problème vienne de l'API car lorsque l'on modifie la condition ligne 34 dans le fichier '/home/reynardt/php/libertempo_112/vendor/libertempo/api/Tools/Middlewares/AccessChecker.php' comme suit (!$user->isAdmin() **&& !$user->isHautResponsable()**) on arrive à accéder à la page.
Reste à savoir si cette restriction est souhaitée ou bien si il s'agit d'un bug.

**Comment by wouldsmina** [comment]
Bonjour,
Vraiment désolé, j'ai oublié de te répondre! La version 1.13 ne semble pas présenter ce problème. Tu confirme ?
