### ISSUE TITLE
[HELP] Impossible de make

### ISSUE THREAD

**Issue by Sabobo33** [libertempo/web#839]
Bonjour,

Assez noob pour installer tout un tas de truc apache and co....j'ai l'impression d'avoir fait ce qu'il fallait pour tester l'installation de LiberTempo sur un serveur de test.
En tout cas, pour les pré-requis (mais je ne suis même pas sûr)...

Par contre, lorsque je tente le moindre make (check, install ou autre), j'ai un message d'erreur qui apparait à la ligne 5...

make check
App/Tools/check
PHP Parse error: syntax error, unexpected ':', expecting '{' in /var/www/libertempo/App/Tools/check on line 5
make: *** [check] Erreur 255

J'ai récupéré la version 1.12.

Je tourne sur un CentOS Linux release 7.3.1611.
Je n'y connais rien en code / programmation...

Si j'ai bien compris, sur CentOs, mon apache c'est httpd...voilà ce qui est installé sur mon serveur :
httpd-manual-2.4.6-45.el7.centos.noarch
httpd-2.4.6-45.el7.centos.x86_64
httpd-devel-2.4.6-45.el7.centos.x86_64
httpd-tools-2.4.6-45.el7.centos.x86_64

Bref, je veux bien de l'aide parceque là j'en peux plus...je peux vous donner les infos que vous souhaitez pour m'aider.

Merci d'avance à vous.

**Comment by wouldsmina** [comment]
Bonjour @Sabobo33 

Quel version de php utilises tu?

**Comment by Sabobo33** [comment]
Bonjour @wouldsmina et merci de ton aide.
J'ai ça d'installer sur la machine....

php-pecl-ncurses-1.0.2-6.el7.x86_64
php-cli-5.4.16-42.el7.x86_64
php-mysql-5.4.16-42.el7.x86_64
php-pear-1.9.4-21.el7.noarch
php-mbstring-5.4.16-42.el7.x86_64
php-pgsql-5.4.16-42.el7.x86_64
php-pdo-5.4.16-42.el7.x86_64
php-imap-5.4.16-3.el7.x86_64
php-gd-5.4.16-42.el7.x86_64
php-common-5.4.16-42.el7.x86_64
php-xmlrpc-5.4.16-42.el7.x86_64
php-xml-5.4.16-42.el7.x86_64
php-devel-5.4.16-42.el7.x86_64
php-bcmath-5.4.16-42.el7.x86_64
php-snmp-5.4.16-42.el7.x86_64
php-dba-5.4.16-42.el7.x86_64
php-odbc-5.4.16-42.el7.x86_64
php-process-5.4.16-42.el7.x86_64
php-soap-5.4.16-42.el7.x86_64

**Comment by wouldsmina** [comment]
il faut PHP7 minimum. La prochaine version (1.13) nécessitera PHP7.3 des fois que tu veuilles prendre de l'avance ;)
++

**Comment by Sabobo33** [comment]
Ok super, je vais déjà tenter de mettre à jour voir ce que ça donne.
Je reviens dans tous les cas dire si c'est OK ou non.
Merci beaucoup.

**Comment by Sabobo33** [comment]
Bon...je vais laisser tomber.
Mon serveur n'a pas d'accès à internet et je ne trouve rien de FACILE et NORMAL pour mettre à jour php.

Y a environ 2 500 dépendances quand je tente un truc.
Pas de package prêt ou tu pourrais faire un update simplement.

Je suis épuisé et découragé. C'est quand même FOU qu'on ne trouve rien de faisable facilement...incompréhensible.

**Comment by Sabobo33** [comment]
Pour info, j'ai tenté de choper un rpm php 7.x.
Alors là c'est la foire aux dépendances.

J'ai ensuite trouvé un gros package en tar.gz.

J'ai du faire du ./configure et ensuite un make test pour au final avoir une erreur :
FAILED TEST SUMMARY

Donc le make install, autant dire qu'il ne passe pas non plus...

Et les trucs que tu trouves sur le net c'est "fais un yum blablabla update".....
Super, je n'ai accès à rien sur mon serveur !
Pas moyen de mettre un package dessus et de faire un update ?!

**Comment by Sabobo33** [comment]
Et pourquoi cet "issue" est fermé aussi.....?!

**Comment by wouldsmina** [comment]
> Et pourquoi cet "issue" est fermé aussi.....?!
Parce que ce n'est pas un bug mais un problème de prérequis :)

avec une CentOS rien n'est facile :p tente ta chance avec la dernière debian, il y a tout ce qu'il faut pour Libertempo ;)

Bon courage.

**Comment by Sabobo33** [comment]
J'aurai les mêmes soucis car pas d'accès à internet....

**Comment by wouldsmina** [comment]
avec l'iso complet, tu devrais pouvoir installer tous les paquets
++

**Comment by wouldsmina** [comment]
> J'ai du faire du ./configure et ensuite un make test pour au final avoir une erreur :
FAILED TEST SUMMARY

c'est `make check` :)
