### ISSUE TITLE
Upgrade 1.10 vers 1.12

### ISSUE THREAD

**Issue by suskemolyon** [libertempo/web#842]
Bonjour,

J'ai un serveur Debian 9.9 avec PHP7.0.33.

Libertempo v1.10 fonctionne correctement.

J'ai suivi les pré-requis v1.11 (pas de date remontée suite au patch BDD) et v1.12.

Mon serveur n'accueille pas uniquement Libertempo mais d'autres application web. Ma structure de fichier est : 

/home/serv-rp/www
|--> Libertempo
|--> AppX
|--> AppY
|--> ...

Voici mon virtualhost défini dans /etc/apache2/sites-enabled/000-default.conf :

`<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /home/serv-rp/www

        <Directory /home/serv-rp/www>
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
        </Directory>

       <Directory /home/serv-rp/www/Libertempo>
               Options None
               AllowOverride None
               Require all granted

               RewriteEngine On
                # Forbidden resources
               RewriteRule ^(/dump/|/backup/|/vendor/libertempo/api/configuration.json$) - [F]
                # API redirection
               RewriteRule ^/api(/|$) /vendor/libertempo/api/Public/index.php [PT]
                # Main redirection
               RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
               RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
               RewriteRule ^(.*)$ /Public/index.php [NS,PT]
       </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>`

Quand je fait un make check, j'ai toujours le message d'erreur :
[ERREUR] L'API semble inaccessible. Vérifiez la configuration d'apache.

http://hostname/Libertempo/api --> 404
http://hostname/Libertempo/vendor/libertempo/api/Public --> 404
http://hostname/Libertempo/api/authentification --> 404

En attendant une solution, j'ai fait un rollback sur v1.10 et restauré la BDD.

Une idée ?

Merci d'avance

**Comment by wouldsmina** [comment]
Salut @suskemolyon,

je pense que ta première balise `Directory` n'est pas bonne. Puisque tu as installé Libertempo dans un sous dossier, tu dois certainement adapter le vhost :+1: 

```
<Directory /home/serv-rp/www/Libertempo>
...
```

**Comment by ValentineGI** [comment]
Problème similaire

**Comment by wouldsmina** [comment]
@suskemolyon on a un début de solution dans #844. Je ferme ton ticket pour ne pas faire doublon.

**Comment by suskemolyon** [comment]
Hello,

Merci pour l'info.
Je vais suivre le post #844 et retenterai l'upgrade quand le temps me le
permettra ;)

Bon weekend

Le mer. 28 août 2019 à 11:40, wouldsmina <notifications@github.com> a
écrit :
