### ISSUE TITLE
Impossible de se connecter 

### ISSUE THREAD

**Issue by ValentineGI** [libertempo/web#844]
Bonjour, 

Après plusieurs essaye de réinstallation, je n'arrive pas à me connecter.
Voici ce que l'erreur me dit : 

`App/Tools/check
#!/usr/bin/env php
[INFO] Version actuelle de Libertempo : 1.12
[INFO] Adresse web : ....
[ERREUR] L'API semble inaccessible. Vérifiez la configuration d'apache.
Makefile:20 : la recette pour la cible « check » a échouée
make: *** [check] Erreur 

J'ai donc suivi les instructions sur votre site internet et même sur RESTED où j'obtient un 200 OK

 - Navigateur et version : Chrome
 - Version de Libertempo : 1.12

![libertempo1](https://user-images.githubusercontent.com/27960793/63772761-0c855080-c8da-11e9-9c28-3512a178abc8.PNG)

![libertempo](https://user-images.githubusercontent.com/27960793/63772754-08f1c980-c8da-11e9-80fc-e40b8f51503f.PNG)

Le mot de passe et l'identifiant sont pourtant correcte

**Comment by wouldsmina** [comment]
Bonjour,

As tu suivi [les prérequis](http://libertempo.tuxfamily.org/documentation/prerequis/) ? En particulier le paramétrage du virtualhost d'apache.

**Comment by ValentineGI** [comment]
Voici mon VirtualHost 👍 
`<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf

    	<Directory /var/www/html/gestionconges>
        	Options None
        	AllowOverride None
        	Require all granted
    	</Directory>
    
	RewriteEngine On
    	# Forbidden resources
    	RewriteRule ^(/dump/|/backup/|/vendor/libertempo/api/configuration.json$) - [F]
    	# API redirection
    	RewriteRule ^/api(/|$) /vendor/libertempo/api/Public/index.php [PT]
    	# Main redirection
   	RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
    	RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
    	RewriteRule ^(.*)$ /Public/index.php [NS,PT]

</VirtualHost>`

**Comment by wouldsmina** [comment]
ok. Ton problème semble proche de #842. Est ce que tu héberges d'autres applications web sur ton serveur ?

**Comment by ValentineGI** [comment]
Oui j’héberge d'autres sites mais je ne voie pas d'ou vient le problème

**Comment by wouldsmina** [comment]
Le problème vient du fait que les requetes vers l'API ne sont pas redirigé correctement. Tu peux comparer la réponse de l'API avec la [démo](https://demo.libertempo.fr/api/).

étant donné que ton install se trouve dans le sous dossier gestionconges, je serais tenté de dire qu'il faut adapter les règles de rewrite comme suit : 
```
        RewriteEngine On
	# Forbidden resources
	RewriteRule ^(/dump/|/backup/|/vendor/libertempo/api/configuration.json$) - [F]
	# API redirection
	RewriteRule ^/gestionconges/api(/|$) /gestionconges/vendor/libertempo/api/Public/index.php [PT]
	# Main redirection
        RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
	RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
	RewriteRule ^(.*)$ /gestionconges/Public/index.php [NS,PT]
```

**Comment by ValentineGI** [comment]
`App/Tools/check
#!/usr/bin/env php
[INFO] Version actuelle de Libertempo : 1.12
[INFO] Adresse web : http://intranet.goulard.local/gestionconges/
[ERREUR] Le fichier de configuration de l'api est exposé. Vérifiez la configuration du virtual host.
Makefile:20 : la recette pour la cible « check » a échouée
make: *** [check] Erreur 1`

J'ai réussi à me connecter mais je ne peux pas accéder à toutes les pages. Cela vient de l'api ?

**Comment by wouldsmina** [comment]
Cool! ça avance. 

> Le fichier de configuration de l'api est exposé.

`RewriteRule ^(gestionconge/dump/|gestionconge/backup/|gestionconge/vendor/libertempo/api/configuration.json$) - [F]`

> je ne peux pas accéder à toutes les pages

Oui, peut-etre que les RewriteCond doivent aussi être adapté. Sans grande conviction, tu peux essayer ça : 
```
        RewriteCond %{DOCUMENT_ROOT}/gestionconges/%{REQUEST_FILENAME} !-d
	RewriteCond %{DOCUMENT_ROOT}/gestionconges/%{REQUEST_FILENAME} !-f
```
J'ai pour le moment pas de possibilité de tester ça de mon coté... Pense aussi à vérifier qu'il n'y a pas d'effet de bord avec les autres applications hébergées.

**Comment by ValentineGI** [comment]
> Oui, peut-etre que les RewriteCond doivent aussi être adapté. Sans grande conviction, tu peux essayer ça :
> 
> ```
>         RewriteCond %{DOCUMENT_ROOT}/gestionconges/%{REQUEST_FILENAME} !-d
> 	RewriteCond %{DOCUMENT_ROOT}/gestionconges/%{REQUEST_FILENAME} !-f
> ```
> 
Cela fait erreur sur tout le serveur 

![Capture](https://user-images.githubusercontent.com/27960793/63846623-765e3280-c98c-11e9-9ab5-ffb806f26ac0.PNG)
Voici pour le moment ce qui marche : 
`        <Directory /var/www/html/gestionconges>
                Options None
                AllowOverride None
                Require all granted
        </Directory>

        RewriteEngine On
        # Forbidden resources
        RewriteRule ^(gestionconges/dump/|gestionconges/backup/|gestionconges/vendor/libertempo/api/configuration.json$) - [F]
        # API redirection
        RewriteRule ^/gestionconges/api(/|$) /gestionconges/vendor/libertempo/api/Public/index.php [PT]
        # Main redirection
        RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
        RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ /gestionconges/Public/index.php [NS,PT]
`

**Comment by ValentineGI** [comment]
Seul les liens ../gestionconges/config/general et ../gestionconges/admin/db_sauve ne marchent pas

**Comment by wouldsmina** [comment]
essaye ça :
`RewriteRule ^/gestionconges/(.*)$ /gestionconges/Public/index.php [NS,PT]`

**Comment by ValentineGI** [comment]
Pas d'amélioration. Comment pourrais-je faire pour vous aider à m'aider ? 👍

**Comment by ValentineGI** [comment]
Je vous met tout mon VirtualHost.

`
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf

        <Directory /var/www/html/gestionconges>
                Options None
                AllowOverride None
                Require all granted
        </Directory>

        RewriteEngine On
        # Forbidden resources
        RewriteRule ^(gestionconges/dump/|gestionconges/backup/|gestionconges/vendor/libertempo/api/configuration.json$) - [F]
        # API redirection
        RewriteRule ^/gestionconges/api(/|$) /gestionconges/vendor/libertempo/api/Public/index.php [PT]
        # Main redirection
        RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
        RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
        RewriteRule ^/gestionconges/(.*)$ /gestionconges/Public/index.php [NS,PT]

</VirtualHost>
`

**Comment by wouldsmina** [comment]
> Comment pourrais-je faire pour vous aider à m'aider ?

Pas grand chose. Il faut que je trouve le temps d'installer une vm pour tester ça...

> Pas d'amélioration. 

pourtant le problème vient forcément de cette dernière règle. Essaye en retirant le / au début et/ou à la fin, par exemple : 
```
RewriteRule ^/gestionconges(.*)$ /gestionconges/Public/index.php [NS,PT]
```

Je suis vraiment pas spécialiste du rewrite! @benrubson pourrait peut être nous donner un tuyau... mais il faut réexpliquer en anglais :smile: 

Je ne t'ai pas posé la question, mais j'imagine que tu ne peux pas demander la création d'un CNAME dans votre DNS ? c'est une solution propre et simple.

**Comment by ValentineGI** [comment]
J'ai testé l'url ../gestionconges/config/index.php et elle marche contrairement à ../gestionconges/config/general

**Comment by wouldsmina** [comment]
> J'ai testé l'url ../gestionconges/config/index.php et elle marche contrairement à ../gestionconges/config/general

oui, c'est possible, mais pour que tout fonctionne bien, il faut passer par l'url ../gestionconges/config/general

**Comment by wouldsmina** [comment]
Tu as essayé différente forme pour `^/gestionconges(.*)$` ?

`^gestionconges/(.*)$ ` me semble plus logique finalement.

**Comment by ValentineGI** [comment]
![conge](https://user-images.githubusercontent.com/27960793/63916588-02c62f00-ca39-11e9-9bc1-9b5c2723d677.PNG)

Oui oui j'ai testé, je pense que je ne suis pas loin de trouvé enfin j'espère :) 

`
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf

        <Directory /var/www/html/gestionconges>
                Options None
                AllowOverride None
                Require all granted
        </Directory>

        RewriteEngine On
        # Forbidden resources
        RewriteRule ^(gestionconges/dump/|gestionconges/backup/|gestionconges/vendor/libertempo/api/configuration.json$) - [F]
        # API redirection
        RewriteRule ^/gestionconges/api(/|$) /gestionconges/vendor/libertempo/api/Public/index.php [PT]
        # Main redirection
        RewriteCond "%{DOCUMENT_ROOT}/gestionconges/%{REQUEST_FILENAME}" !-d
        RewriteCond "%{DOCUMENT_ROOT}/gestionconges/%{REQUEST_FILENAME}" !-f
        RewriteRule "^gestionconges/(.*)$" "/gestionconges/Public/index.php" [NS,PT]

</VirtualHost>

`

**Comment by wouldsmina** [comment]
et comme ça ? : 
`RewriteRule "^gestionconges/(.*)$" "gestionconges/Public/index.php" [NS,PT]`

**Comment by wouldsmina** [comment]
d'après ta capture d'écran, je vois qu'il y a aussi un problème avec cette règle : 
`RewriteRule ^(gestionconges/dump/|gestionconges/backup/|gestionconges/vendor/libertempo/api/configuration.json$) - [F]`

essaye ça : 
`RewriteRule ^gestionconges/(dump/|backup/|vendor/libertempo/api/configuration.json$) - [F]`

J'ai monté une nouvelle vm... je vais tester de mon coté dés que possible.

**Comment by wouldsmina** [comment]
Il te manque aussi `ServerName intranet.goulard.local`

Tu ne m'as pas répondu au sujet du CNAME dans le DNS. cela permettrait d'avoir une adresse du genre gestionconges.goulard.local avec un vhost à part, donc pas d'effet de bord avec tes autres applis.

**Comment by ValentineGI** [comment]
Pour le moment pas d'amélioration.
`<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.

        ServerName intranet.goulard.local

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf

        <Directory /var/www/html/gestionconges>
                Options None
                AllowOverride None
                Require all granted
        </Directory>

        RewriteEngine On
        # Forbidden resources
        RewriteRule ^gestionconges/(dump/|backup/|vendor/libertempo/api/configuration.json$) - [F]
        # API redirection
        RewriteRule ^/gestionconges/api(/|$) /gestionconges/vendor/libertempo/api/Public/index.php [PT]
        # Main redirection
        RewriteCond "%{DOCUMENT_ROOT}%{REQUEST_FILENAME}" !-d
        RewriteCond "%{DOCUMENT_ROOT}%{REQUEST_FILENAME}" !-f
        RewriteRule "^gestionconges/(.*)$" "gestionconges/Public/index.php" [NS,PT]

</VirtualHost>
`

Je vais essayer de configurer un CNAME sur le DNS de mon Raspberry. Merci

**Comment by wouldsmina** [comment]
c'est aussi le raspi qui fait DNS?? il fait tout ce truc :rofl: 

Si tu peux faire ça, je te conseils de : 
- remettre le vhost default comme avant
- déplacer gestionconges dans /var/www/
- créer un nouveau vhost dans /etc/apache2/site-available/lt.conf
- l'activer `a2ensite lt.conf`

enjoy ! :)

**Comment by ValentineGI** [comment]
Oui il peut mais j'ai beaucoup de mal à comprendre 🤣 Je continue mes recherches demain

**Comment by wouldsmina** [comment]
il peut, mais ça ne veut pas dire que c'est lui le (ou les) DNS dans ton réseau...

par contre, il est possible de tricher en ajoutant dans le fichier /etc/hosts de ton pc :
`192.168.0.1	gestionconges.goulard.local`

il faut remplacer l'ip que j'ai mis par celle de ton serveur intranet.

Par contre, tout ça dépasse le cadre de Libertempo, tu va donc devoir chercher un peu sur le net. Les exemples ne manque pas.

**Comment by ValentineGI** [comment]
J'ai testé `192.168.0.1  gestionconges.goulard.local` avec la bonne adresse IP et bien tout plante 🤣 
Je continue mes recherches. Merci à toi

**Comment by ValentineGI** [comment]
Bonjour, 

Petit avancée, en configurant correctement un deuxième VirtualHost par rapport au autres sites que je dispose. Je peux accéder à toute le site sur le Raspberry seulement il n'est pas encore accessible sur le réseau. 

![capture](https://user-images.githubusercontent.com/27960793/64259906-8096a880-cf19-11e9-8183-76db7f96b8d2.PNG)
 
Avoir la même adresse IP peut-il faire conflit ? 

Merci bien,

**Comment by wouldsmina** [comment]
Salut,
> J'ai testé 192.168.0.1 gestionconges.goulard.local avec la bonne adresse IP et bien tout plante 

Je ne pourrais t'aider sur ce sujet étant donné que je ne maîtrise pas ton environnement réseau.

> Avoir la même adresse IP peut-il faire conflit ?
C'est certain, si tu utilise la même ip sur 2 serveurs, tu va avoir des problèmes. As tu déclaré gestionconges en tant que CNAME dans le serveur DNS de ton réseau ? Si tu as juste modifié le fichier hosts sur ton poste, alors c'est normal que tu ne puisse y accéder que depuis ce poste.

**Comment by prytoegrian** [comment]
@ValentineGI Au vu de #850, j'en déduis que ce ticket est résolu ?

**Comment by ValentineGI** [comment]
@prytoegrian Tout à fait grâce à la création d'un CNAME mais le problème est aussi corriger grâce à la création d'un autre VHOST
