### ISSUE TITLE
Nooma - 1.13 / Ldap

### ISSUE THREAD

**Issue by lucaguindani** [libertempo/web#847]
Bonjour,

Depuis la maj 1.13 je me retrouve avec une erreur de connexion ldap. Je précise que l'authentification fonctionnait correctement en 1.12, je n'ai rien changé au niveau de la configuration ldap ou vhost.

`[Mon Sep 02 10:11:54.801266 2019] [php7:warn] [pid 7592] [client 127.0.0.1:44382] PHP Warning:  ldap_bind(): Unable to bind to server: No such object in /var/www/libertempo/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 287
[Mon Sep 02 10:11:54.804769 2019] [php7:error] [pid 7598] [client xxxxxxx] PHP Fatal error:  Uncaught Error: Call to undefined function ddd() in /var/www/libertempo/index.php:108\nStack trace:\n#0 /var/www/libertempo/index.php(132): authDefault('ldap', Object(App\\Libraries\\ApiClient))\n#1 {main}\n  thrown in /var/www/libertempo/index.php on line 108, referer: https://xxxxxxxxx/`

La maj c'est déroulée sans problèmes, et le `make check` ne retourne aucune erreur.

`make check
App/Tools/check
#!/usr/bin/env php
[INFO] Version actuelle de Libertempo : 1.13
[INFO] Adresse web : https://xxxxxxxxx/
Vérifications effectuées avec succès.`

**Comment by wouldsmina** [comment]
Bonjour @lucaguindani ,

Merci pour se retour de bug. Je n'avais pas remarqué de problème avec LDAP durant mes tests. Je regarde ça dés que possible. Si tu as le temps de regarder ce qu'il se passe, n'hésite pas.

Tu peux d'abord interroger directement l'API à l'aide du plugin RESTED, une petite de doc se trouve [ici](http://libertempo.tuxfamily.org/connexion-impossible/).
Tu peux  aussi regarder dans le code source la fonction qui s'occupe d'authentifier en LDAP : https://github.com/libertempo/api/blob/master/Tools/Services/LdapAuthentifierService.php#L26

Par exemple, tu peux vérifier que la configuration est bien transmise en ajoutant la ligne suivante [ici](https://github.com/libertempo/api/blob/master/Tools/Services/LdapAuthentifierService.php#L43) : 
`dd($config);`

**Comment by lucaguindani** [comment]
Une fois la correction faite dans le fichier index.php (-> `dd($e->getMessage());`) je reçois l'erreur suivante:

`{"code":404,"status":"fail","message":"Not Found","data":"No user matches these criteria"}`

Et j'ai logiquement la même erreur avec une requête postman directement sur l'api.

Je regarde plus en détail dès que j'ai un moment.

**Comment by wouldsmina** [comment]
ok, c'est plutôt l'erreur `Unable to bind to server: No such object` qui est intéressante. Je pense qu'un paramètre n'est pas correctement transmis...
Merci.

**Comment by lucaguindani** [comment]
J'ai changé des paramètres dans cfg/config_ldap.php et c'est à nouveau fonctionnel !

Apparement cette erreur peut venir d'un soucis de configuration -> https://www.linuxtopia.org/online_books/network_administration_guides/ldap_administration/appendix-common-errors_Common_causes_of_LDAP_errors.html

Par contre je ne sais pas pourquoi ça fonctionnait avant la 1.13... peut-être suite à une maj de Adldap2 (https://github.com/libertempo/api/commit/b71e78931f0abcaeedc66316f0a43b8a7eabf68a#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) ?

**Comment by prytoegrian** [comment]
C'est sans doute ça @lucaguindani. Il est noté nulle part que AdLDAP2 suit semver, mais j'imagine que s'il y a eu un changement de majeure, c'est qu'il y avait des choses à surveiller. Merci de ton retour. A-t-on une doc à préciser de notre côté ?

**Comment by wouldsmina** [comment]
Gg @lucaguindani
Peux-tu me dire ce que tu as changé concrètement ? Je mettrai à jour la doc en conséquence.

**Comment by prytoegrian** [comment]
Après étude, ça ne peut pas être ça car le contenu de la 1.13 ne contient pas ce changement. Je préfère attendre plus de réponse de ta part avant de me prononcer

**Comment by lucaguindani** [comment]
Si c'est pas un changement dans AdLDAP2 ca doit venir de notre LDAP logiquement. Ca c'est peut être croisé avec la maj en 1.13 ?

J'ai ajouté un `ou=xxx` à la $config_basedn.

**Comment by wouldsmina** [comment]
Je confirme, aucun changement dans le code entre 1.12 et 1.13 et je ne constate pas de problème avec mon ldap. CE n'est donc qu'un simple soucis de paramétrage... Je clos.
