### ISSUE TITLE
Problème saisie congés

### ISSUE THREAD

**Issue by ptitpopey** [libertempo/web#849]
**Bug**
Erreur lors de la saisie d'une demande de congés :

Message d'erreur : Attention le nombre de jours d'absence demandé (3) est supérieur à votre solde (somme du solde (7) et des congés à valider) (0)

**Version**
1.13

**Comment by wouldsmina** [comment]
Bonjour @ptitpopey
Peux tu m'en dire plus sur ton problème ? Arrives tu as reproduire sur la [démo](https://demo.libertempo.fr) (compte : georges/georges) ?

**Comment by ptitpopey** [comment]
Aucun problème sur l'interface de démo.
![libertempo](https://user-images.githubusercontent.com/14994180/64529506-57a45800-d30b-11e9-8f71-19ba1c15ddb6.png)

**Comment by wouldsmina** [comment]
tu as des demandes en attente ?

**Comment by ptitpopey** [comment]
Non aucune

**Comment by ptitpopey** [comment]
Oui, pas de problème pour modifier le code source.
je peux mettre quelque var_dump. Juste me dire où

**Comment by wouldsmina** [comment]
Ok, je pense avoir identifié le problème. Je prépare le patch pour que tu puisses tester.

**Comment by wouldsmina** [comment]
#851 à toi de jouer @ptitpopey ;)

**Comment by ptitpopey** [comment]
Patch appliqué. Bug corrigé. Merci
