### ISSUE TITLE
Mauvais redirection en se déconnectant 

### ISSUE THREAD

**Issue by ValentineGI** [libertempo/web#850]
**Décrivez le bug**
Lorsque l'on fait une déconnexion le site est mal redirigé.
Nous devrions avoir http://gestionconges.goulard.local/authentification/ mais nous avons http://gestionconges.goulard.localauthentification/

![capture](https://user-images.githubusercontent.com/27960793/64688639-0f14a800-d48d-11e9-9438-101a55c2629d.PNG)

 - Version de Libertempo : 1.13
 - Version MySQL et PHP : 7.3

**Comment by wouldsmina** [comment]
Salut,

Dans la configuration générale, ajoute un slash à la fin de l'URL d'accueil

**Comment by ValentineGI** [comment]
Ohlala honte à moi :) merci !
