### ISSUE TITLE
Difficulté à installer libertempo 1.13

### ISSUE THREAD

**Issue by albert1963** [libertempo/web#863]
Bonjour ,
J'ai un blocus lors de l'installation de libertempo 1.13. En effet j'ai exécuté avec succès les commandes Make comme indiqué dans la doc et j'arrive  à accéder à la page de connexion avec une base de données utilisée avec la version 1.11.
Néanmoins, lorsque je rentre les paramètres de connexion j'ai une erreur  '**Erreur client : Request -> GET /libertempo//api/authentification HTTP/1.1'** 

Je joins mon virtualhost paramétré dans le fichier **/etc/apache2/sites-available/cssw-local.conf**
'<VirtualHost *:80>
    ServerName [libertempo]
    DocumentRoot /var/www/html/libertempo
    <Directory /var/www/html/libertempo>
        Options None
        AllowOverride None
        Require all granted
    </Directory>
    RewriteEngine On
    # Forbidden resources
    RewriteRule ^(/dump/|/backup/|/vendor/libertempo/api/configuration.json$) - [F]
    # API redirection
    RewriteRule ^/api(/|$) /vendor/libertempo/api/Public/index.php [PT]
    # Main redirection
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ /Public/index.php [NS,PT]
</VirtualHost>'

Voici mon hosts dans le dossier **/etct/hosts/**

'192.168.1.188 localhost.libertempo libertempo
127.0.0.1	localhost.localdomain	localhost
'
Je tiens à préciser que libertempo est installé sur une machine virtuelle linux.
Merci d'avance!

**Comment by wouldsmina** [comment]
Vu en direct sur irc

**Comment by wouldsmina** [comment]
Pour ton dernier problème, l'erreur vien de la dernière règle de Rewrite :  
```
- RewriteRule ^(.)$ /Public/index.php [NS,PT]
+ RewriteRule ^(.*)$ /Public/index.php [NS,PT]
```
