### ISSUE TITLE
Mise a jour sans make

### ISSUE THREAD

**Issue by thomas64400** [libertempo/web#865]
Bonjour, 
je sous sous libertempo 1.10 kantra. 
je souhaiterai passer sous une version supérieure malheureusement, mon plan d'hébergement ne me permets pas d'avoir accès à une ligne de commande et donc de faire un make. 
Y a t il une autre technique possible de mise à jour? 
merci !

**Comment by wouldsmina** [comment]
Bonjour @thomas64400 ,
Le passage par make est indispensable. Si tu es de nature joueur, tu peux faire une installation local (ou sur une vm), mettre à jour libertempo puis dumper la bdd vers ton hébergement. Mais tu devras aussi passer par le paramétrage du rewrite, car j'imagine que tu n'as pas accès au virtualhost non plus.
En clair, il faut que tu maîtrises parfaitement le fonctionnement d'apache et de mysql pour y arriver.

**Comment by thomas64400** [comment]
Merci pour ta réponse.
donc pas de mise a jour possible pour moi !


________________________________
De : wouldsmina <notifications@github.com>
Envoyé : lundi 18 novembre 2019 20:00
À : libertempo/web <web@noreply.github.com>
Cc : thomas64400 <pharmacie-briol@orange.fr>; Mention <mention@noreply.github.com>
Objet : Re: [libertempo/web] Mise a jour sans make (#865)


Bonjour @thomas64400<https://github.com/thomas64400> ,
Le passage par make est indispensable. Si tu es de nature joueur, tu peux faire une installation local (ou sur une vm), mettre à jour libertempo puis dumper la bdd vers ton hébergement. Mais tu devras aussi passer par le paramétrage du rewrite, car j'imagine que tu n'as pas accès au virtualhost non plus.
En clair, il faut que tu maîtrises parfaitement le fonctionnement d'apache et de mysql pour y arriver.
