### ISSUE TITLE
saisie de congés exceptionnels par un responsable

### ISSUE THREAD

**Issue by alainco75** [libertempo/web#866]
**Votre demande est-elle associée à un problème ? Décrivez.**
Bonjour,
Nous avons constaté que les responsables ne peuvent pas saisir de congés exceptionnels pour leurs agents (ils n'ont pas la main pour cela, alors qu'ils peuvent saisir d'autres types de congés à la place de leurs agents). Est-ce un fonctionnement voulu et si oui pourquoi ?
nous sommes sous la version  1.10.2 Kantra Stable. Est-ce la version la plus récente permet de corriger cela ?

cordialement

Alain C.
Observatoire de Paris

**Comment by wouldsmina** [comment]
Bonjour,
C'est une limite hérité de php_conges. Ce sera rectifié dans une future version.
Cordialement.
