### ISSUE TITLE
connexion impossible?

### ISSUE THREAD

**Issue by alexraimondo** [libertempo/web#870]

**Comment by wouldsmina** [comment]
As-tu correctement paramétré le virtualhost d'apache comme dans les pré-requis de la documentation ?

**Comment by alexraimondo** [comment]
comment j'y accede c'est ca .... je suis sous cpanel ....

**Comment by wouldsmina** [comment]
Si tu n'as pas accès à la conf d'apache, tu peux peut-être créer des .htaccess.

**Comment by alexraimondo** [comment]
ok donc je rajoute  a mon .htaccess 
<VirtualHost *:80>
    ServerName [domaine LT]
    DocumentRoot /var/www/repertoireLT
    <Directory /var/www/repertoireLT>
        Options None
        AllowOverride None
        Require all granted
    </Directory>
    RewriteEngine On
    # Forbidden resources
    RewriteRule ^(/dump/|/backup/| web/vendor/libertempo/api/configuration.json$) - [F]
    # API redirection
    RewriteRule ^/api(/|$)web/vendor/libertempo/api/Public/index.php [PT]
    # Main redirection
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ /Public/index.php [NS,PT]
</VirtualHost>

comme ceux ci????

**Comment by alexraimondo** [comment]
je mets quoi dans le .htaccess ????

**Comment by alexraimondo** [comment]
Bon j'ai inserer dans   .htaccess 

RewriteEngine On
    RewriteRule ^(/dump/|/backup/|/vendor/libertempo/api/configuration.json$) - [F]
    # API redirection
    RewriteRule ^/api(/|$) /vendor/libertempo/api/Public/index.php [PT]
    # Main redirection
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ /Public/index.php [NS,PT]
![image](https://user-images.githubusercontent.com/59066278/71259445-bfb9ff80-2338-11ea-99f1-66ee8ab04645.png)
et niveau login :
![image](https://user-images.githubusercontent.com/59066278/71259482-d82a1a00-2338-11ea-9962-9439c5a77545.png)

**Comment by prytoegrian** [comment]
Bonjour. Nous t'invitons à fournir plus de détails, en l'état on ne peut pas t'aider.
