### ISSUE TITLE
Base de données vide (make install)

### ISSUE THREAD

**Issue by eglyn** [libertempo/web#872]
Bonjour, 

Je tente d'installer Libertempo sur une Debian 10, mais j'ai une erreur lors du make install: 
`[ERREUR] La base de données semble vide, une réinstallation est nécessaire.`

Je ne comprends pas trop cette erreur car effectivement la base de données est vide vu que je viens de la créer :/

J'ai bien rempli le fichier dbconnect.php, et la connexion à la base avec l'utilisateur fonctionne bien en ligne de commande.

Une idée ?

Merci d'avance :)

**Comment by wouldsmina** [comment]
Bonjour,
`Make install` à pour effet de créer la bdd, si elle existe déjà, il suffit de faire un `make reinstall` pour supprimer et recréer la bdd.

**Comment by eglyn** [comment]
Ah oui, tout bête... merci :)
