### ISSUE TITLE
Calendrier HS

### ISSUE THREAD

**Issue by MaximeVirot** [libertempo/web#877]
Bonjour, 

Je viens de faire la migration de la 1.10 vers la 1.13 tout fonctionne correctement sauf la page du calendrier qui ne m'affiche absolument rien. 

Voici les infos dans mon fichier log : 

[Wed Jan 15 12:22:35.161902 2020] [php7:error] [pid 30623] [client X.X.X.X:60910] PHP Fatal error:  Uncaught Exception: Donnee de configuration inexistante in /var/www/Libertempo/conges/App/Libraries/Configuration.php:481\nStack trace:\n#0 /var/www/Libertempo/conges/App/Libraries/Configuration.php(406): App\\Libraries\\Configuration->getValeur('afficher_types_...', '12_Fonctionneme...')\n#1 /var/www/Libertempo/conges/App/Libraries/Configuration.php(389): App\\Libraries\\Configuration->getGroupeFonctionnementEtablissementValeur('afficher_types_...')\n#2 /var/www/Libertempo/conges/calendrier.php(21): App\\Libraries\\Configuration->getQuiAfficheTypeCongesCalendrier()\n#3 /var/www/Libertempo/conges/calendrier.php(127): canSessionVoirTypesConges(Array, Object(App\\Libraries\\Configuration))\n#4 /var/www/Libertempo/conges/Public/index.php(52): require_once('/var/www/Libert...')\n#5 {main}\n  thrown in /var/www/Libertempo/conges/App/Libraries/Configuration.php on line 481, referer: http://congesadico.adico.fr/utilisateur/user_index.php

J'ai essayé de refaire la migration plusieurs fois, mais sans succès.

Merci par avance pour votre aide !

**Comment by wouldsmina** [comment]
Bonjour,
As tu exécuté un make update après le remplacement des fichiers ?

**Comment by MaximeVirot** [comment]
Bonjour, 
Je viens de le refaire dans le doute et toujours le même problème. (page calendrier complètement vide.)

Entre temps, j'ai refait la migration en passant chaque version une par une, et même soucis.

**Comment by MaximeVirot** [comment]
Rectification je viens de mettre a jour nodejs et toujours le même problème

**Comment by wouldsmina** [comment]
Il manque une option dans la table conges_config. Elle aurait dû être créée lors du make update. Peux tu me dire quelle version est retourné par la commande 'make check' ?

**Comment by MaximeVirot** [comment]
Voici ce que me retourne la commande : 

[INFO] Version actuelle de Libertempo : 1.13

**Comment by MaximeVirot** [comment]
Problème résolu ! J'ai exporté la table config d'une instance neuve et j'ai réimporté sur mon instance et le calendrier fonctionne. Merci pour votre aide :)
