### ISSUE TITLE
Fonctionnalités / Bugs

### ISSUE THREAD

**Issue by bopware** [libertempo/web#878]
Bonjour, nous utilisons votre logiciel (Libertempo 1.8.1), et il facilite la vie de toute l'équipe, nous tenions à vous remercier.

Nous avons quelques questions :

1- Est-il possible de ne pas déduire les congés posés tant qu'ils ne sont pas consommés (ou alors de permettre le choix entre les deux modes de visualisation : solde des congés consommés et posés et solde de seulement les congés consommés) ? Car les salariés ne comprennent pas que leur solde de congés n'est pas le même que sur leur bulletin de salaire.

2- Le report des congés peut-il se faire automatiquement au 1er janvier ?

3- Actuellement, si l'on pose des congés pour l'année N+1, le système de calcul des jours ne fonctionne pas. Il faut saisir le nombre de jours comptés manuellement.

Merci pour vos retours.

**Comment by wouldsmina** [comment]
Bonjour,

1. Il est vrai que c'est ainsi que le solde des congés devrait être calculé, mais pour le moment il n'est pas possible de faire cela avec Libertempo.
2. Pas pour le moment.

3. Ce n'est pas normal. Est ce que les jours fériés sont posés sur N+1 ?

**Comment by bopware** [comment]
<img width="772" alt="Capture d’écran 2020-01-22 à 16 49 49" src="https://user-images.githubusercontent.com/22081165/72909465-5d895b80-3d37-11ea-8baa-bcb9cc12cfd6.png">

Bonjour,

Merci pour votre retour.
Effectivement, pour le point 3, les jours fériés ne sont pas posés pour l'année N+1 (voir PJ).

**Comment by prytoegrian** [comment]
Attention, la version 1.8 n'est plus maintenue. Nous t'invitons a mettre la version a niveau si tu veux profiter des dernières fonctionnalités et correctifs.

**Comment by wouldsmina** [comment]
En effet! Je je n'avais pas vu que c'était sur une 1.8
