### ISSUE TITLE
impossible d'installer Akhaten

### ISSUE THREAD

**Issue by alainco75** [libertempo/web#880]
Bonjour,

j'essaie d'installer la version web-1.12.0.tar.gz (Akhaten) sur une machine Debian.
J'ai décompressé le fichier web-1.12.0.tar.gz, mis les bons droits, mais quand je lance la commande make install-dep && make install, j'obtiens le message suivant :

make: *** No rule to make target 'install-dep'.  Stop.

Comme je ne suis pas un habitué de la compilation sous linux, je ne sais pas d'où vient le problème.

En vous remerciant par avance

Alain C.
Obs de Paris.

J'ai ça dans le fichier Makefile 👍 
.DEFAULT_GOAL := help

#
# Thanks to https://blog.theodo.fr/2018/05/why-you-need-a-makefile-on-your-project/
#

help:
	@grep -E '(^[a-zA-Z_-]+:.*?##.*$$)|(^##)' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}{printf "\033[32m%-30s\033[0m %s\n", $$1, $$2}' | sed -e 's/\[32m##/[33m/'

## Purge
destroy: ## Détruit l'instance
	App/Tools/destroy

## Mise à jour
update: ## Met l'application à la toute dernière version (patch compris)
	App/Tools/update

## Vérification de l'integrité avant installation
check: ## Controle les prérequis
	App/Tools/check

## Création haut responsable / administrateur
createHR: ## Créé un utilisateur avec les droits HR et administrateur
	App/Tools/createHR ${login} ${nom} ${prenom} ${courriel} ${hash}

## Installation
setup:
	App/Tools/setup ${nom_instance}

install: check setup update createHR check ## Installe la nouvelle instance

reinstall: destroy install ## Reset usine

## Test
test: ## Lance les tests unitaires
	vendor/bin/atoum -ulr

## Configuration
configure: ## Paramètre une option de configuration
	App/Tools/configure ${option} ${valeur}

**Comment by wouldsmina** [comment]
Bonjour @alainco75
La version 1.12 embarqué déjà les dépendances, inutile d'exécuter install-dep, make install suffira.
J'attire tout de même ton attention sur le fait que cette version n'est pas compatible CAS, nous cherchons toujours un spécialiste pour remettre ça sur pied.

**Comment by alainco75** [comment]
Bonjour,
merci pour votre réponse.

cordialement

Alain C.
Obs de Paris
