### ISSUE TITLE
 Erreur lors de la connexion de l'admin après  install

### ISSUE THREAD

**Issue by teger** [libertempo/web#886]
Bonjour,

Je viens d'installer la version 1.13 sur un nouveau serveur.
J'ai un problème de connexion avec l'admin

"""
Erreur client : Request -> GET /api/authentification HTTP/1.1
User-Agent: GuzzleHttp/6.3.3 curl/7.64.0 PHP/7.3.9-1~deb10u1
Host: xxxx.xxxx.fr
Authorization: Basic anVsaWVuOk1hYXC3RlAZ45KGF84MTDSIyMDEx
Content-Type: application/json
Accept: application/json
 | Response <- HTTP/1.1 400 Bad Request
Date: Mon, 03 Feb 2020 22:40:52 GMT
Server: Apache
Content-Length: 122
Connection: close
Content-Type: application/json;charset=utf-8
{"code":400,"status":"fail","message":"Bad Request","data":"Authorization header doesn't comply to authentication method"}
"""

Avec Rested, sur l'ur https://xxxx.xxxx.fr/api/authentification, j'obtiens la même erreur 400

Si je passe un make check, je n'ai aucun erreur 

[INFO] Version actuelle de Libertempo : 1.13
[INFO] Adresse web : https://xxxxx.xxxxxx.fr
Vérifications effectuées avec succès.

Dans les logs d'Apache, je n'ai aucune erreur !

Que puis-je faire svp ?

Je suis sur une Debian 10, Apache 2.4.x, PHP 7.3.9-1~deb10u1, 10.3.18-MariaDB-0+deb10u1-log

Merci d'avance,

**Comment by wouldsmina** [comment]
Bonjour @teger ,

peux tu envoyer une capture d'écran du Rested stp ? 
As tu configuré ton apache d'une façon particulière ? J'ai l'impression que quelque chose modifie la requête avant qu'elle n'arrive à l'API. Un reverse proxy pourrait aussi créer ce genre de problème.

**Comment by teger** [comment]
Bonsoir,

Voici une capture d'écran de RESTED
![Uploading Capture d’écran 2020-02-04 à 23.38.57.png…]()

Mod_security est installé sur ce serveur ? je vais le désactiver pour tester.
Je regarde si dans ce cas j'ai un reverse proxy s'exécute.

merci de votre aide

**Comment by teger** [comment]
Bonsoir,

Donc pas de reverse proxy sur le serveur. J'ai désactivé mod_security mais toujours le même problème.
Que puis-je encore vérifier pour corriger ce problème ?
Merci d'avance

**Comment by wouldsmina** [comment]
tu peux essayer de faire une requête sur la démo, tu sauras si quelque chose cloche entre ton poste et ton serveur ou si c'est vraiment la configuration de ton serveur qui pose problème.

C'est une deb10 fraîchement installée pour l'occasion ?

**Comment by teger** [comment]
oui, elle est toute neuve. Je ne trouve aucun log nulle part qui explique ce problème. Est ce qu'un module Apache pourrait bloquer la requete ?

Merci d'avance,

**Comment by wouldsmina** [comment]
Si tu n'as rien fait de particulier sur ton serveur, le problème est ailleurs... Ça donne quoi sur la demo ?

**Comment by teger** [comment]
Sur la démo, ca fonctionne.

Après étude, en fait c'est l'accès à l'API qui bloque. 
Cette fonction est appelée 

private function authentifyCommon($login, $password)
    {
        $options = [
            'headers' => [
                'Authorization' => 'Basic ' . base64_encode($login . ':' . $password),
            ],
        ];
        return $this->request('GET', 'authentification', $options);
    }

Et l'erreur arrive à l'appel de cette requete sur api/authentification

A quel endroit est géré l'authentification pour l'accès à 'API stp ? Quelle classe s'occupe de cela ?

Merci d'avance,

**Comment by conanedogawa2** [comment]
Salut,

Essaye d'ajouter ca dans ta conf apache, cela a résolu le soucis pour moi.
`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

**Comment by teger** [comment]
Salut,

Super bravo !
Avec cette directive, l'application arrive enfin à faire les connexions.

Merci de votre aide
