### ISSUE TITLE
recherche developpeur pour installer libertempo

### ISSUE THREAD

**Issue by thomas64400** [libertempo/web#895]
bonjour, 
mes capacités en insatllation de logiciel etant tres limitées, je cherche un developpeur etant capable de pouvoir installer libertempo sur un serveur vps .
moyennant paiement bien sur.

**Comment by wouldsmina** [comment]
Salut @thomas64400
Tu m'as l'air bien en galère... Contact moi par mail, je vais essayer de t'aider un peu.
A+

**Comment by thomas64400** [comment]
reglé !

**Comment by wouldsmina** [comment]
Cool :+1:
