### ISSUE TITLE
connexion impossible

### ISSUE THREAD

**Issue by alainco75** [libertempo/web#898]
**Décrivez le bug**
Bonjour.
j'ai installé Akhaten avec la nouvelle procédure (make ...)
Après quelques problèmes rencontrés au cours de l'installation (droits d'accès sur le répertoire App/Tools, , fichier configuration.json manquant) l'appli s'est enfin 
<img width="378" alt="authentfication_error" src="https://user-images.githubusercontent.com/4649106/78146604-ab56ca00-7432-11ea-81ad-8699184be678.png">
<img width="378" alt="authentfication_error" src="https://user-images.githubusercontent.com/4649106/78146688-c88b9880-7432-11ea-895d-ddf1d673693f.png">

 installée. 
J'arrive bien sur l'interface de connexion, cependant, quand j'essaie de m'y connecter avec l'utilisateur créé au cours de l'installation, j'obtiens un message d'erreur 👍 (voir copie d'écran ci-jointe)

Que se passe-t-il ?

cordialement

Alain C. 
Observatoire de Paris

*

**Comment by wouldsmina** [comment]
Bonjour,
Je pense que la configuration du virtualhost dans apache n'est pas bonne, compare ta configuration avec la documentation.

**Comment by alainco75** [comment]
Bonjour,
Merci, ça fonctionne. Je n'avais pas vu qu'il y avait une configuration du virtualhost différente par rapport aux versions précédentes dans les prérequis.

cordialement
Alain C.
Observatoire de Paris
