### ISSUE TITLE
Calendrier dans 1.13: pas d'affichage des demandes en cours

### ISSUE THREAD

**Issue by thomas64400** [libertempo/web#899]
bonjour, 

les demandes de conges non validées par le responsable n'apparaissent pas dans le calendrier des utilisateurs. 
est ce normal? 
du coup les utilisateurs ne peuvent pas savoir qui a déposé une demande et a quel moment. 
cette fonctionnalité existait dans les versions antérieures à kantra il me semble. 
Dans les optionsn °13, l'option est à true

 

// AFFICHAGE DES DEMANDES DE CONGÉS DES UTILISATEURS DANS LE CALENDRIER : 
//--------------------------------------------------------------------------------------------
// si à FALSE : les demandes de congés de tous les utilisateurs n'apparaissent pas sur le calendrier des congés. (seules les demandes de l'utilisateur connecté apparaissent) (FALSE est la valeur par défaut)
// si à TRUE : les demandes de congés de tous les utilisateurs apparaissent sur le calendrier des congés.
affiche_demandes_dans_calendrier = TRUE

avez vous une idée ou une solution? 
merci !!

**Comment by wouldsmina** [comment]
Bonjour,
Seul le responsable peut consulter les demandes en cours.
Cordialement.
