### ISSUE TITLE
Connexion impossible après installation

### ISSUE THREAD

**Issue by Urba34** [libertempo/web#904]
Bonjour,

Je ne parviens pas à me connecter avec les identifiants admin/responsable suite à l'installation de libertempo 1.13 Nooma.
Je joins une capture de l'erreur que j'obtiens lorsque je saisie les identifiants.

![Erreur connexion LT 1 13](https://user-images.githubusercontent.com/65649690/82424711-dc906580-9a85-11ea-8bc7-62e24eaaf931.png)

Le cas semble donc similaire au [#898](https://github.com/libertempo/web/issues/898) . J'ai donc vérifié la configuration de mon virtualhost par rapport aux prérequis et tout me semble en ordre :
<VirtualHost *:80>
    ServerName libertempo
    DocumentRoot /var/www/libertempo
<Directory /var/www/libertempo>
        Options None
        AllowOverride None
        Require all granted
</Directory>
    RewriteEngine On
    # Forbidden resources
    RewriteRule ^(/dump/|/backup/|/vendor/libertempo/api/configuration.json$) - [F]
    # API redirection
    RewriteRule ^/api(/|$) /vendor/libertempo/api/Public/index.php [PT]
    # Main redirection
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ /Public/index.php [NS,PT]
</VirtualHost>

Le retour du RESTED Client semble aussi OK :
![Rested client](https://user-images.githubusercontent.com/65649690/82426197-d7ccb100-9a87-11ea-80eb-68fb3ba09f74.png)

Avez-vous une idée de ce qui peut empêcher cette connexion ?
Merci d'avance.

 - Système [i.e. iOS8.1] : Debian 9
 - Version de Libertempo : 1.13
 - Version MySQL et PHP : MySQL 10.1.44-MariaDB / PHP 7.3

**Comment by wouldsmina** [comment]
Bonjour,
Je ne vois pas la balise </Directory>

Rested doit te retourner une réponse semblable à celle ci : http://libertempo.tuxfamily.org/connexion-impossible/
D'ailleurs, il manque /api/ dans l'URL de ta requête.
A+

**Comment by Urba34** [comment]
Bonjour,

Je n'ai pas exactement la même réponse que dans la doc'.

![Rested Client](https://user-images.githubusercontent.com/65649690/82802820-cc122d80-9e7f-11ea-865c-54f44877c61e.png)

Et voici le résultat suite au make check

![Make check](https://user-images.githubusercontent.com/65649690/82802871-e815cf00-9e7f-11ea-9d03-4e3f5ef64e1c.png)

Le problème pourrait être lié au fichier var/www/libertempo/api/index.php ?

Merci pour votre aide.

**Comment by Urba34** [comment]
Pour le vhost je me suis basé sur l'exemple présent en "prérequis" puis je l'ai adapté.
Le précédent screen du vhost n'étant pas très parlant (des lignes sont manquantes dans la capture ...), je le reposte ici :

![Vhost](https://user-images.githubusercontent.com/65649690/82829511-bae31400-9eb3-11ea-87d7-76bdb7e63d05.png)

Je dois passer à côté de quelque chose.

**Comment by antyamok** [comment]
Bonjour,

Je me permets de relancer ce sujet. Je me retrouve avec la même erreur dans le **Make Check** soit
`make: *** [Makefile:15: check] Error 1`
Pourtant mon fichier VirtualHost semble être bon.
Si quelqu'un a une réponse à apporter, je suis preneur.

**Comment by antyamok** [comment]
Bonjour,

j'ai du mettre Libertempo entre parenthèse durant tout ce temps mais je me permets de relancer le sujet. J'ai regardé de nouveau pour voir si j'étais passer à côté de quelque chose mais je ne vois rien... Dommage !
Pourriez-vous m'aider à résoudre ce problème s'il vous plait.

**Comment by wouldsmina** [comment]
Bonjour,
d'après #944 vous n'avez plus le même message d'erreur qu'avant. Pourriez vous refaire une requete versl'api avec rested ? http://libertempo.tuxfamily.org/connexion-impossible/
