### ISSUE TITLE
Authentification LDAP impossible 

### ISSUE THREAD

**Issue by lmidiap** [libertempo/web#910]
Bonjour,
Je viens d'installer un serveur debian buster, avec mariadb, apache2, php 73 et la dernière version de libertempo (1.13).
Toutes les dependances sont OK;
Jarrive à me connecter en mode dbconges, mais pas en mode LDAP.
ldapsearch fonctionne trés bien.
Mais j'ai l'erreur suivante:
"""
Erreur serveur : Request -> GET /api/authentification HTTP/1.1
User-Agent: GuzzleHttp/6.3.3 curl/7.64.0 PHP/7.3.11-1~deb10u1
Host: xxxxxxxxxxx.ch
Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Content-Type: application/json
Accept: application/json
 | Response <- HTTP/1.1 500 Internal Server Error
Date: Thu, 04 Jun 2020 09:37:11 GMT
Server: Apache
Content-Length: 98
Connection: close
Content-Type: application/json;charset=utf-8
{"code":500,"status":"error","message":"Internal Server Error","data":"Can't contact LDAP server"}

J'ai vérifié mon vhost, mais je ne vois nulle part ou se trouve l'erreurs.
Avez vous une idée?

**Comment by wouldsmina** [comment]
Bonjour,

Can't contact LDAP server... Arrives-tu à faire un telnet vers ton ldap ?
`Telnet adresse.ldap 389`

**Comment by lmidiap** [comment]
oui j'arrive bien à faire un telnet dessus; le ldapsearch fonctionne aussi

**Comment by lmidiap** [comment]
Autre précision si cela peut aider, j'ai activé le SSL , certificats installés et fonctionnels

**Comment by lmidiap** [comment]
Alors j'ai avancé un peu, en corrigeant le vhost, j'ai l'erreur suivante:


Erreur client : Request -> GET /api/authentification HTTP/1.1
User-Agent: GuzzleHttp/6.3.3 curl/7.64.0 PHP/7.3.11-1~deb10u1
Host: ************************.ch
Authorization: Basic ************************************************
Content-Type: application/json
Accept: application/json
 | Response <- HTTP/1.0 404 Not Found
Date: Thu, 04 Jun 2020 11:54:19 GMT
Server: Apache
Set-Cookie: PHP_SID=9855da065c1eb31dde185d73c53ce5b2; path=/; SameSite=Strict
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8


Ce qui m'intrigue un peu cependant, c'est que je ne peux pas me loguer avec le compte admin meme si le mode LDAP est configuré. Il me semblait avoir lu que le compte admin peut se loguer puisqu il est se logue via la BD!!!
Aurais je loupé qq chose , et pourtant j'ai suivi les consignes d'installation sans rien faire d'autre

**Comment by lmidiap** [comment]
hup

**Comment by wouldsmina** [comment]
Vérifie le fichier cfg/config_ldap.php et fait un make update pour mettre à jour la configuration de l'api 👍

**Comment by lmidiap** [comment]
j'ai toujours ce meme message d'erreu can't connect ....
Je pense qu'il y a un soucis au niveau config php apache2.
J essaye de trouver un trace qq part.

**Comment by wouldsmina** [comment]
Rien dans les logs apache ?

**Comment by lmidiap** [comment]
non absolument rien qui explique cette erreur 500 , d 'autant plus que de ma VM si je fais un ldapsearch -x je me connecte bien a mon serveur ldap. Donc e n est pas un soucis entre ma VM et le serveur LDAP. Je penserai plutot à un soucis de conf php ( php.ini par exemple....)

**Comment by lmidiap** [comment]
alors cotè rested il n y a aucun soucis je l avais deja fait pour voir et la connexion est faite sans pb directe sur l api
Je suis openldap

**Comment by wouldsmina** [comment]
Est ce que le nom du serveur est bien déclaré dans le fichiers /etc/hosts ? J'ai le vague souvenir d'un bug similaire et le problème venait de ce fichier.

**Comment by lmidiap** [comment]
oui oui tout st bien déclaré dans mon etc/hosts

**Comment by lmidiap** [comment]
est ce que tu peux me donner le nom du fichier php qui fait l'authentification ? Je voudrai y mettre quelques tags pour voir ce qu'il s'y passe. Merci pour ton temps et ton travail

**Comment by lmidiap** [comment]
Ce qui est peut etre source d'erreur c'est que dans le fichier config_ldap.php, on ne défini pas le port de connection sur le serveur ldap

**Comment by lmidiap** [comment]
une autre info qui vient de faire tilt. je suis en SSL et curl n'aime pas bcp ça SAUF si on change qq parametres.
J'ai vu ça ici : 
https://stackoverflow.com/questions/2453207/curl-http-post-keep-getting-500-error-has-no-idea

Je suis typiquement dans ce cas là

**Comment by wouldsmina** [comment]
C'est une bonne piste, mais tu obtiens un code 500 ou 404?

**Comment by lmidiap** [comment]
500

**Comment by wouldsmina** [comment]
Une erreur 500 sans log d'erreur... Ça m'étonne beaucoup 🤔

**Comment by lmidiap** [comment]
si dans le fichier apache2/access-LT.log 
GET /api/authentification HTTP/1.1 500 98  GuzzleHttp/6.3.3 curl/7.64.0 PHP/7.3.11-1~deb10u1

**Comment by wouldsmina** [comment]
C'est pas un message d'erreur mais c'est déjà ça... Je ne comprends pas qui répond l'erreur 500 puisque tu arrives à joindre ton api avec Rested.

**Comment by lmidiap** [comment]
je n'ai aucun message d'erreur quand je suis en dbconges, mais dès que je veux attaquer ldap ....Je vais tenter une autre installation avec une version de php et de apache non customisée entreprise et non SSL pour voir. Je te tiens au courant

**Comment by wouldsmina** [comment]
Ok, mais le ssl ne me semble pas être le problème, en tout cas avec une config standard.

**Comment by wouldsmina** [comment]
Jette un œil à la console js sur le navigateur avant de tout casser... J'avais oublié cette piste !

**Comment by lmidiap** [comment]
Alors effectivement voici une erreur 404 qui n'existe pas en mode dbconges :
[Exception... "Favicon at "https://vm-xxxx.xxx.xxx/favicon.ico"
failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)" 
location: "JS frame :: resource:///modules/FaviconLoader.jsm ::
onStopRequest :: line 236"  data: no]

**Comment by wouldsmina** [comment]
Ça me paraît trop léger pour être là source de ton souci. Désolé mais je suis à court d'idées 😅

**Comment by lmidiap** [comment]
Peux tu me donner le nom du fichier qui permet de s'authenitifier , je voudrai voir si je ne peux pas rajouter un traçage de ce qu'il tente de faire pour avoir cette erreur 500 ?

**Comment by wouldsmina** [comment]
l'authentification passe par l'API à partir d'[ici](https://github.com/libertempo/web/blob/master/index.php#L106). Le ldap est sollicité depuis [cette fonction](https://github.com/libertempo/api/blob/master/Tools/Services/LdapAuthentifierService.php#L26).
Tu peux debuguer en utilisant la fonction `dd($variablesAdebuguer);` à condition de mettre ENV_DEV [ici](https://github.com/libertempo/web/blob/master/cfg/env_new.php#L2)
++

**Comment by lmidiap** [comment]
Ok merci, mais je pense que les soucis erreur 500 sont dues à un soucis de paramétrage de apache surtour dans le virtualhost. C'est due à note haut degrés de sécurité apache chez nous. Je vais esayer de voir ceci . Merci de ton aide. AU cas ou je tiendrai au courant pour d'autres personnes si cela peut les aider

**Comment by lmidiap** [comment]
Je reviens vers toi pour savoir où je peux afficher le nom du serveur ldap qu il tente de joindre ?

**Comment by lmidiap** [comment]
Salut bon he bien j'ai trouvé d'ou venait l'erreur, simplement une erreur du nom de mon serveur ldap , ne pas mettre ldaps://<serveur_ldap>; en ce qui me concern c'etait <serveur_ldap>:636

Cependant , est ce obligé d'avoir deja l'utilisateur créé dans la bd pour qu'il puisse se loguer en LDAP. Je souhaiterai que TOUS mes utilisateurs utilisent ton produit et qu'ils se loguent avec leur credentials LDAP directement sans avoir à ce que je leur créer leur compte en local

**Comment by wouldsmina** [comment]
Salut,
Super nouvelles ! Je ne sais pas si l'usage du ldaps est très rependu, généralement dans un LAN ce n'est pas utilisé pour ne pas consommer de ressource inutilement... Si la demande se fait plus forte je me pencherai plus dessus.

La création des utilisateurs est indispensable pour la simple raison qu'il faut définir un planning, saisir les soldes de congés, etc. Sans cela l'utilisateur ne pourrait rien faire.

Enjoy ;)

**Comment by wouldsmina** [comment]
Salut,

En effet, avec l'authentification ldap le mot de passe dans la bdd n'est pas utilisé. Fait attention à assurer la cohérence des données dans la base pour ne pas avoir de mauvaises surprises.

**Comment by lmidiap** [comment]
Merci de ces infos. Est ce tu penses qu'une integration directe dans la bdd ( via insert into conges_users et un fichier csv ) peut se faire sans soucis ou faut il obligatoirement passer par l interface pour creer mes utilisateurs (Je sais que certains controles sont fait sur l interface )?

**Comment by wouldsmina** [comment]
Oui, c'est possible mais comme je te l'ai dit fait attention à la cohérence des données, il ne suffit pas d'alimenter la table conge_users, il faut maintenir les relations avec les autres tables.

**Comment by lmidiap** [comment]
OK OK , et tu n'aurais pas par hasard le schema relationnel de tes tables quelque part ;) ?

**Comment by wouldsmina** [comment]
Non, désolé

**Comment by lmidiap** [comment]
c'est bon j'ai trouvé, les deux tables concernées sont conges_solde_user et conges_users. Je viens de faire l'eesai de rajouter un utilisateur et tout fonctionne ( attention cependant de bien rajouter deux enregistrements pour le meme utilisateur dans la table conges_solde_user (valeur 1 puis valeur 2 pour le champ su_abs_id) )
Merci à toi
