### ISSUE TITLE
bouton deconnection

### ISSUE THREAD

**Issue by lmidiap** [libertempo/web#911]
**Décrivez le bug**
Lorsque je clique sur le bouton deconection en bas à gauche, ma page web affiche le nom du hostauthentification au lieu du host/authentification

**Pour reproduire**
Étapes de la reproduction du comportement :
1. Prérequis (rôle connecté, options de configuration, méthode de connexion, …) :
2. Cliquer sur : 
3. Constater l'erreur : 

**Comportement attendu**
un retour sur la page d'authentification normal
**Copies d'écran**
Si applicable, ajoutez des captures d'écran pour aider à expliquer le problème.

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] : Debian 10
 - Navigateur et version : firefox 77
 - Erreur dans la console : message d'erreur firefox disant qu'il ne trouve pas la age demandée

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : debian 10
 - Version de Libertempo : 1.13
 - Version MySQL et PHP : mariadb 10 php 7.3
 - Erreur dans le log du serveur : 

**Contexte additionnel**
Ajoutez tout ce qui vous paraît utile pour la bonne résolution du défaut.

**Comment by wouldsmina** [comment]
Bonjour,
Dans la configuration, ajoute un / à la fin de l'URL d'accueil 👍

**Comment by lmidiap** [comment]
il y ai deja ;)

**Comment by lmidiap** [comment]
<VirtualHost *:443>
    ServerAdmin root@****.ch
    ServerName https://*******.ch/
    DocumentRoot /usr/share/libertempo/
    use ssl
    <Directory "/usr/share/libertempo/">
    use AUTH_idiap
        #Options None
        Options FollowSymLinks
        AllowOverride All
        Order deny,allow
        Allow from all
        Require all granted
    </Directory>
    RewriteEngine On
    # Forbidden resources
    RewriteRule ^(/dump/|/backup/|/vendor/libertempo/api/configuration.json$) - [F]
    # API redirection
    RewriteRule ^/api(/|$) /vendor/libertempo/api/Public/index.php [PT]
    # Main redirection
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ /Public/index.php [NS,PT]
    ErrorLog ${APACHE_LOG_DIR}/libertempo-error.log
    CustomLog ${APACHE_LOG_DIR}/access-lt.log combined
</VirtualHost>

**Comment by lmidiap** [comment]
OK merci pb résolu. merci encore de ta réactivité

**Comment by lmidiap** [comment]
alors depuis que j'ai fait un make reconfigure avec le / rajouté, j'ai ça:
Erreur client : Request -> GET **/**/api/authentification HTTP/1.

**Comment by wouldsmina** [comment]
Hmmm... Bizarre ! Je vais essayer de trouver un peu de temps pour m'y pencher... Mais je suis pas super dispo en ce moment.

**Comment by lmidiap** [comment]
OK pas de soucis. Je cherche de mon coté et si je trouve une piste je ne manquerai pas de venir la glisser ici. Juste une question cependant, est obligé que la locale soit FR_fr ? je travaille à l'étranger

**Comment by lmidiap** [comment]
je considère que c'est réglé, cela fonctionne trés bien avec:
