### ISSUE TITLE
impossibilité de se connecter apres installation

### ISSUE THREAD

**Issue by indialbert** [libertempo/web#912]
**Décrivez le bug**
apres l'installation, je n'arrive pas a me connecter avec le login de gestion

**Copies d'écran**
Si applicable, ajoutez des captures d'écran pour aider à expliquer le problème.
![Capture d’écran du 2020-06-08 14-03-09](https://user-images.githubusercontent.com/66622373/84028344-d0b30780-a990-11ea-8b06-1ce00c564f77.png)

**Poste (veuillez remplir les informations suivantes):**
 - Système debian 10 :
 - Navigateur et version : firefox
 - Erreur dans la console : 
![Capture d’écran du 2020-06-08 13-20-39](https://user-images.githubusercontent.com/66622373/84028367-de688d00-a990-11ea-8594-e8808a27e048.png)

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] :debian 10
 - Version de Libertempo : 1.13
 - Version MySQL et PHP :php7.3.14-1~deb10u1;mariadb 10.3.22

**Contexte additionnel**
config Vhost
![Capture d’écran du 2020-06-08 13-21-57](https://user-images.githubusercontent.com/66622373/84028658-65b60080-a991-11ea-9477-17d5bf6641b7.png)

pouvez-vous me dire comment je peux regler mon probleme?
je vous remercie par avance cordialement.

**Comment by lmidiap** [comment]
si tu fais un make configure cela te donne quoi ?

**Comment by indialbert** [comment]
bonjour,
en etant dans le dossier Libertempo la commande "make configure" me retourne: 
App/Tools/configure  
#!/usr/bin/env php
Configuration générale de Libertempo
commande incomplète. Veuillez définir l'une des options suivantes :
OPTION                                   : VALEUR                              ; TYPE
URL_ACCUEIL_CONGES           : http://localhost/conges       ; texte
admin_change_passwd             : TRUE                                  ; boolean
admin_see_all                           : FALSE                               ; boolean
affiche_date_traitement                  : FALSE                               ; boolean
affiche_demandes_dans_calendrier         : FALSE                               ; boolean
affiche_jours_current_month_calendrier   : FALSE                               ; boolean
afficher_types_conges_calendrier         : rh                                  ; enum=rh/rh+responsable/tous
auth                                     : TRUE                                ; boolean
autorise_reliquats_exercice              : TRUE                                ; boolean
dimanche_travail                         : FALSE                               ; boolean
editions_papier                          : TRUE                                ; boolean
export_ical                              : TRUE                                ; boolean
export_ical_salt                         : Jao%iT}                             ; texte
export_users_from_ldap                   : FALSE                               ; boolean
fermeture_par_groupe                     : FALSE                               ; boolean
gestion_cas_absence_responsable          : FALSE                               ; boolean
gestion_conges_exceptionnels             : FALSE                               ; boolean
gestion_heures                           : TRUE                                ; boolean
grand_resp_ajout_conges                  : FALSE                               ; boolean
how_to_connect_user                      : dbconges                            ; enum=dbconges/ldap/cas/sso
installed_version                        : 1.13                                ; texte
interdit_modif_demande                   : FALSE                               ; boolean
interdit_saisie_periode_date_passee      : FALSE                               ; boolean
jour_mois_limite_reliquats               : 0                                   ; texte
mail_annul_conges_alerte_user            : FALSE                               ; boolean
mail_modif_demande_alerte_resp           : FALSE                               ; boolean
mail_new_demande_alerte_resp             : FALSE                               ; boolean
mail_prem_valid_conges_alerte_user       : FALSE                               ; boolean
mail_refus_conges_alerte_user            : FALSE                               ; boolean
mail_supp_demande_alerte_resp            : FALSE                               ; boolean
mail_valid_conges_alerte_user            : FALSE                               ; boolean
nb_maxi_jours_reliquats                  : 0                                   ; texte
resp_ajoute_conges                       : TRUE                                ; boolean
resp_association_planning                : FALSE                               ; boolean
resp_saisie_mission                      : FALSE                               ; boolean
samedi_travail                           : FALSE                               ; boolean
solde_toujours_positif                   : FALSE                               ; boolean
texte_bas_edition_papier                 : - édité par Libertempo -          ; texte
texte_haut_edition_papier                : - Libertempo : édition des congés - ; texte
user_ch_passwd                           : TRUE                                ; boolean
user_echange_rtt                         : FALSE                               ; boolean
user_saisie_demande                      : TRUE                                ; boolean
user_saisie_mission                      : TRUE                                ; boolean
exemple : make configure option="resp_ajoute_conges" valeur="TRUE"

**Comment by lmidiap** [comment]
As tu bien rajouter dans ton fichier /etc/hosts ton localhost enfin celui que tu as déclaré comme serveurname dans ton fichier apache?

**Comment by indialbert** [comment]
oui le serverName est bien le meme sur apache et dans le etc/hosts

**Comment by lmidiap** [comment]
c'est étrange, je suis dans les memes conditions que toi, debian 10 , mariadb , php73 .. et en plus en SSL , et je n'ai plus ce soucis depuis que j'ai viré les exceptions dans le fichier /etc/php/7.3/apache2/php.ini
Enlevé provisoirement pur chercher quelle(s) exception(s) met le basard

**Comment by indialbert** [comment]
tu as enlever quelles exceptions??

**Comment by lmidiap** [comment]
j'ai enlevé TOUTES les exceptions de façon à voir si cela venait d'ici. Cela a un effet puisque la connection locale fonctionne (mise à part le mode ldap qui ne fonctionne pas du tout (erreur 500, malgré le fait que ma VM avec ldapsearch se croche bien a mon ldap)

**Comment by indialbert** [comment]
salut,
j'ai tout retirer et depuis ça marche.
je te remercie
