### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by thebat98** [libertempo/web#915]
Bonjour,

J'ai décidé de repartir sur une installation frâiche de Libertempo.

J'ai vérifié les prérequis : http://libertempo.tuxfamily.org/documentation/prerequis/
et j'ai démarré l'installation : http://libertempo.tuxfamily.org/documentation/installation/

Voici ce que me retourne la commande `make install`
[ERREUR] /var/www/Libertempo/vendor/libertempo/api/configuration.json n'existe pas ou est inaccessible

Si je crée ce fichier directement et que je réessaye, voici ce que j'obtiens : "[ERREUR] La base de données semble vide, une réinstallation est nécessaire."

J'avance en faisant : `mysql -u libertempo -p libertempo < /var/www/Libertempo/App/Patchs/Installation/1.10.0.sql`
mais je ne suis pas certain que ce soit une bonne idée car j'ai ensuite "L'API semble inaccessible. Vérifiez la configuration d'apache."

J'ai regardé du côté de "make" mais sans plus de réussite : http://libertempo.tuxfamily.org/make/

Sauriez-vous m'aider ?

Pour info j'utilise Ubuntu 20.04 et PHP 7.3 (car 7.4 ne satisfaisait pas les dépendances)

Bonne soirée,
TheBAT

**Comment by wouldsmina** [comment]
Bonjour,

Make reinstall devrait faire le job. Le fichier configuration.json doit être accessible en écriture pour www-data.

++

**Comment by thebat98** [comment]
Exactement ! Merci beaucoup.

Par contre je n'ai pas compris ce que je n'avais pas bien fait initialement.

++
