### ISSUE TITLE
Creation d'un nouvel utilisateur

### ISSUE THREAD

**Issue by alainco75** [libertempo/web#930]
- Système [i.e. iOS8.1] : Debian
 - Version de Libertempo : Akhaten
 - Version MySQL et PHP : PHP 7.3
 - Erreur dans le log du serveur : 

Bonjour,
Notre application est configurée pour que les utilisateurs soient importés de LDAP
Lorsqu'on veut créer un nouvel utilisateur, on saisit un début de chaine dans le champ nom. Cependant la recherche se fait uniquement sur le prénom. Par ailleurs, si un des caractères de la chaîne recherchée est accentué, la recherche ne fonctionne pas, ce qui est bloquant.
Est-ce dû à un problème de configuration ?
cordialement
Alain C.
Observatoire de Paris.

**Comment by alainco75** [comment]
Bonjour,
Le problème de la recherche qui se faisait uniquement sur le prénom est résolu. Cela venait de la configuration de config_ldap.php (on avait mis $config_ldap_nomaff = "givenname" à la place de $config_ldap_nomaff = "sn")

cordialement

Alain C.
Observatoire de Paris

**Comment by wouldsmina** [comment]
D'une pierre 2 coups ;)
Bonne journée.
