### ISSUE TITLE
création de comptes d'utilisateurs hors LDAP

### ISSUE THREAD

**Issue by alainco75** [libertempo/web#931]
Système [i.e. iOS8.1] : Debian
Version de Libertempo : Akhaten
Version MySQL et PHP : PHP 7.3

Bonjour,

Est-il possible, quand on a configuré libertempo pour que les utilisateurs se connectent avec leur identifiants LDAP, de créer en parallèle des comptes d'utilisateurs qui ne sont pas dans LDAP (par exemple des utilisateurs fictifs pour réaliser des tests)  ?
cordialement

Alain C.
Observatoire de Paris

**Comment by wouldsmina** [comment]
Bonjour,

Non, ce n'est pas possible. Désolé.

Cordialement.
