### ISSUE TITLE
Non validation des demandes si le nb de congés est trop grand

### ISSUE THREAD

**Issue by nemsproxi** [libertempo/web#932]
Bonjour,

**Décrivez le bug :**
Lorsque le salarié à trop de congés ainsi que des reliquats, si le HR valide sa demande de congés:
le mail de confirmation de congés est bien envoyé
la demande n'est pas validé et reste en état "à valider"
La quantité de congés / reliquat décrémente bien

Serveur (veuillez remplir les informations suivantes):

Système [i.e. iOS8.1] : Ubuntu 18.04
Version de Libertempo : 1.13 Nooma
Version MySQL et PHP : MariaDB 10.1.44 et PHP 7.4.6
Merci d'avance !

**Comment by wouldsmina** [comment]
Bonjour,
As tu des erreurs dans les logs ? Pourrais-tu confirmer ce bug sur la demo stp?
Merci.
