### ISSUE TITLE
regénération de la configuration de LDAP

### ISSUE THREAD

**Issue by alainco75** [libertempo/web#934]
**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] :debian
 -

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] :
 - Version de Libertempo :  Libertempo 1.13
Bonjour,

nous avons changé de serveur  LDAP  ainsi que la structure de notre LDAP. J'ai donc modifié la configuration du fichier config_ldap.php qui se trouve dans le répertoire cfg. Mais apparemment cela ne suffit pas, l'appli fait appel à un fichier configuration.json sans doute généré lors de l'installation de libertempo. Comment  regénère-t-on  configuration.json afin de tenir compte de la nouvelle configuration et sans détruire la base ?

cordialement
Alain C.
Observatoire de Paris

**Comment by wouldsmina** [comment]
Bonjour,
Un make update fera le job.
++

**Comment by alainco75** [comment]
Merci pour votre réponse rapide.
néanmoins, un make update a bien regénéré le fichier configuration.json dans vendor/libertempo/api  avec la configuration du nouvel LDAP, mais quand j'essaie de me connecter, j'ai le message suivant (alors que j'arrivais à me connecter avec l'ancienne config)


Erreur serveur : Request -> GET //api/authentification HTTP/1.1\r\n
User-Agent: GuzzleHttp/6.3.3 curl/7.64.0 PHP/7.3.19-1~deb10u1\r\n
Host: conges-dgs-test.obspm.fr\r\n
Authorization: Basic YWNvdXJnZXk6QWwzNDJjcjUy\r\n
Content-Type: application/json\r\n
Accept: application/json\r\n
\r\n
 | Response <- HTTP/1.1 500 Internal Server Error\r\n
Date: Wed, 16 Dec 2020 16:42:40 GMT\r\n
Server: Apache\r\n
Content-Length: 98\r\n
Connection: close\r\n
Content-Type: application/json;charset=utf-8\r\n
\r\n
{"code":500,"status":"error","message":"Internal Server Error","data":"Can't contact LDAP server"}
*

cordialement

Alain C.

**Comment by alainco75** [comment]
Bonjour,

Désolé de vous avoir dérangé pour rien. Je pense avoir compris l'origine du problème. Notre nouvel ldap est en SSL, et c'est le même problème que celui décrit dans le ticket 910 : il ne faut pas mettre ldaps:// dans le fichier config_ldap.php, juste le temps de générer le fichier json. (une fois généré, il faut remettre ldaps:// sinon on ne voit pas les utilisateurs ni le calendrier)

cordialement

Alain C.
Observatoire de Paris
