### ISSUE TITLE
cloture d'exercice ne fonctionne pas

### ISSUE THREAD

**Issue by alainco75** [libertempo/web#935]
Bonjour,
Nous avons tenté de faire une clôture d'exercice, mais cela génère une page blanche (sans message d'erreur). Nous obtenons dans le fichier de log cela : 

[Thu Dec 17 14:56:54.485418 2020] [php7:error] [pid 52950] [client 145.238.197.254:61915] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE su_login="admin" AND su_abs_id = 16' at line 2 in /data/SitesWeb/conges-dgs-test.obspm.fr/includes/SQL.php:151\nStack trace:\n#0 /data/SitesWeb/conges-dgs-test.obspm.fr/includes/SQL.php(151): mysqli->real_query('UPDATE conges_s...')\n#1 [internal function]: includes\\Database->query('UPDATE conges_s...')\n#2 /data/SitesWeb/conges-dgs-test.obspm.fr/includes/SQL.php(114): call_user_func_array(Array, Array)\n#3 /data/SitesWeb/conges-dgs-test.obspm.fr/App/ProtoControllers/HautResponsable/ClotureExercice.php(91): includes\\SQL->__call('query', Array)\n#4 /data/SitesWeb/conges-dgs-test.obspm.fr/App/ProtoControllers/HautResponsable/ClotureExercice.php(54): App\\ProtoControllers\\HautResponsable\\ClotureExercice::setReliquatEmploye('admin', 16, NULL, Object(includes\\SQL), Object(App\\Libraries\\Configuration))\n#5 /data/SitesWeb/conges-dgs-test.obspm.fr/App/Pr in /data/SitesWeb/conges-dgs-test.obspm.fr/includes/SQL.php on line 151, referer: https://conges-dgs-test.obspm.fr/hr/cloture_exercice

cordialement

Alain C.
Observatoire de Paris

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : Debian
 - Version de Libertempo : Libertempo 1.13
 - Version MySQL et PHP :
 - Erreur dans le log du serveur :  (voir dans le message ci-dessus)

**Comment by wouldsmina** [comment]
Le compte admin ne devrait plus exister en 1.13.

**Comment by alainco75** [comment]
J'ai supprimé l'utilisateur admin, masi j'ai toujours le même message d'erreur (avec un autre utilisateur) :
[Thu Dec 17 15:35:52.938038 2020] [php7:error] [pid 52948] [client 145.238.197.254:62151] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE su_login="ccalderarifroidefond" AND su_abs_id = 16' at line 2 in /data/SitesWeb/conges-dgs-test.obspm.fr/includes/SQL.php:151\nStack trace:\n#0 /data/SitesWeb/conges-dgs-test.obspm.fr/includes/SQL.php(151): mysqli->real_query('UPDATE conges_s...')\n#1 [internal function]: includes\\Database->query('UPDATE conges_s...')\n#2 /data/SitesWeb/conges-dgs-test.obspm.fr/includes/SQL.php(114): call_user_func_array(Array, Array)\n#3 /data/SitesWeb/conges-dgs-test.obspm.fr/App/ProtoControllers/HautResponsable/ClotureExercice.php(91): includes\\SQL->__call('query', Array)\n#4 /data/SitesWeb/conges-dgs-test.obspm.fr/App/ProtoControllers/HautResponsable/ClotureExercice.php(54): App\\ProtoControllers\\HautResponsable\\ClotureExercice::setReliquatEmploye('ccalderarifroid...', 16, NULL, Object(includes\\SQL), Object(App\\Libraries\\Configuration))\n#5 /data/SitesWeb/con in /data/SitesWeb/conges-dgs-test.obspm.fr/includes/SQL.php on line 151, referer: https://conges-dgs-test.obspm.fr/hr/cloture_exercice

**Comment by wouldsmina** [comment]
Dans data/SitesWeb/conges-dgs-test.obspm.fr/App/ProtoControllers/HautResponsable/ClotureExercice.php ligne 94 pourrais tu ajouter une ligne de debug pour afficher la variable $req :
`ddd($req) ;`

Il faut être en mode debug (fichier cfg/env.php)

Merci.

**Comment by alainco75** [comment]
Merci pour le débugage.
J'obtiens cela 👍 
UPDATE conges_solde_user SET su_reliquat = 0.00 WHERE su_login="ccalderarifroidefond" AND su_abs_id = 14;
" string(123) "
UPDATE conges_solde_user SET su_reliquat = 0.00 WHERE su_login="ccalderarifroidefond" AND su_abs_id = 20;
" string(119) "
UPDATE conges_solde_user SET su_reliquat = WHERE su_login="ccalderarifroidefond" AND su_abs_id = 16;" 

L'appli ne trouve pas de soldeRestant pour le congé d'identifiant 16. C'est un congé de type exceptionnel et je me suis aperçu qu'il n'était pas dans la table conges_solde_user. Je me rappelle qu'on avait eu des problèmes lors de sa création (le libelle n'avait pas été renseigné dans la table conges_type_absence, et j'avais dû le renseigner manuellement. on a ce genre de problème dès qu'on crée un congé de type exceptionnel)
Pour ce qui est de la clôture, je viens d'ajouter dans conges_solde_user les enregistrements manquants pour les congés exceptionnels , et la clôture a cette fois presque marché : on a bien eu un message disant que la clôture était faite, mais en regardant dans les tables, il semble certains agents n'ont pas vu leur solde mis à jour.

cordialement
Alain C.
Observatoire de Paris
