### ISSUE TITLE
Problème installation : API inaccessible

### ISSUE THREAD

**Issue by jamelou** [libertempo/web#937]
Bonjour,

lors de l'installation (make install-dep && make install) , j'ai l'erreur suivante pour laquelle je ne trouve pas de solution :

[INFO] Version actuelle de Libertempo : 0
[INFO] Adresse web : http://libertempo/
[ERREUR] L'API semble inaccessible. Vérifiez la configuration d'apache.
make: *** [Makefile:15: check] Error 1

J'ai bien un fichier libertempo.conf dans /etc/apache2/conf-available que j'ai activé via la commande a2enconf, mais cela ne suffit pas apparemment.

OS : ubuntu server 20.04
Mariadb 8
PHP 7.1

**Comment by jamelou** [comment]
pb résolu en lançant la commande "make reinstall"
J'accède bien à l'appli, mais j'ai un pb d'affichage : tous les boutons affiche leur code :
- Menu de droite, le bouton calendrier affiche : "button_calendar"
- Menu de droite, le bouton deconnexion affiche : "button_deconnect"
- etc... ???

**Comment by wouldsmina** [comment]
Bonjour,

Il faut installer les pré-requis... Il doit manquer gettext.

**Comment by jamelou** [comment]
Bonjour,

J'ai bien installé tous les prérequis et notamment gettext. 
Il figure d'ailleurs bien dans le répertoire /etc/php/7.1/mods_available/gettex.ini et je l'ai activé dans le php.ini

**Comment by wouldsmina** [comment]
Il doit être activé (a2enmod)

**Comment by jamelou** [comment]
Merci pour votre intérêt !
J'ai lancé la commande "a2enmod gettext" mais j'ai une erreur :
ERROR: Module gettext does not exist!
La commande est correct ? Faut il se placer dans un répertoire en particulier ?

**Comment by wouldsmina** [comment]
Petite erreur de ma part, gettext est un module php et non apache. Normalement l'installation du paquet php-gettext devrait faire le job.

**Comment by jamelou** [comment]
Bonjour,

Ayant la version 7.1.33 de php, lorsque je lance la commande : sudo apt install php7.1-gettext, j'ai le retour suivant : 
```
Note, selecting 'php7.1-common' instead of 'php7.1-gettext'
php7.1-common is already the newest version (7.1.33-24+ubuntu20.04.1+deb.sury.org+1).
```
??

**Comment by jamelou** [comment]
Et petite question supplémentaire : quel est l'os le mieux adapté pour installer LT ?

**Comment by wouldsmina** [comment]
Bonjour, 
Il faut php7. 3 minimum. Je te conseil Debian 10.

**Comment by jamelou** [comment]
Merci pour le retour.
Je pense que le pb est ma version php.
Je vais suivre ton conseil et relancer une install sur une debian 10.
Merci encore

**Comment by jamelou** [comment]
Bonsoir,

Merci pour le conseil : l'install sur Debian 10 a fonctionnée nickel !! 
Aucun problème rencontré.
L'affichage ne présente pas d'anomalies, par contre dès l'authentification, j'arrive sur une page blanche (erreur 500) !!

**Comment by jamelou** [comment]
Je me reponds : le problème venait du virtualhost.
tout fonctionne parfaitement 👍 !!!
