### ISSUE TITLE
Demande d'information

### ISSUE THREAD

**Issue by jamelou** [libertempo/web#938]
Bonsoir,

Une question pratique : quelle est la différence entre "Demande d'heure de repos" et "Demande d'heure additionnelles " ?
Merci d'avance

 - Système  : VM XEN Debian 10
 - Version de Libertempo : 1.13
 - Version MySQL et PHP : 8 & 7.3

**Comment by wouldsmina** [comment]
Bonjour,
Désolé pour le temps de réponse. Les heures de repos sont déduit du solde alors que les additionnelles sont ajoutées
