### ISSUE TITLE
Pose de congés impossible

### ISSUE THREAD

**Issue by jamelou** [libertempo/web#940]
Bonjour,

Après avoir modifié la configuration afin d'interdire les congés en négatifs, lorsqu'un utilisateur veut poser des congés, il s'affiche cette erreur : 

Attention le nombre de jours d'absence demandé (1) est supérieur à votre solde (somme du solde (33) et des congés à valider) (0)
ERREUR ! Les valeurs saisies sont invalides ou manquantes !!!

Sachant qu'il dispose d'un solde de 33 jours et aucun congé à valider ?

Libertempo v 1.13

**Comment by wouldsmina** [comment]
Bizarre... Pas de demande en double validation ? Peux tu vérifier directement dans la bdd ?

**Comment by jamelou** [comment]
Non pas double validation car je l'ai pas activée.
Etonnant, sachant que quand je décoche l'option solde négatif, ca refonctionne nickel !

Mais après recherche, je viens de voir le patche que tu avais mis en ligne ici : [#851](https://github.com/libertempo/web/pull/851), et ben après application , ca refonctionne nickel !!
