### ISSUE TITLE
présentation de la page 'utilisateurs' de RH

### ISSUE THREAD

**Issue by alainco75** [libertempo/web#941]
Bonjour,

Notre établissement a paramétré dans l'application une vingtaine de types de congés.
Tous ces types de congé s'affichent dans le tableau des utilisateurs quand la DRH clique sur le menu 'utilisateurs', ce qui rend la page difficile à lire et à utiliser  (car les boutons d'accès à chaque utilisateur sont complètement sur la droite au bout du tableau). Est-ce qu'il est possible de masquer certains types de congé dans cette page, afin de la rendre plus digeste et plus facile à utiliser  Je ne crois pas que ce soit possible actuellement dans la configuration mais peut-être ai-je mal regardé ?

cordialement

Alain C.
Observatoire de Paris

**Comment by wouldsmina** [comment]
Bonjour,

Désolé pour le temps de réponse. Non, ce n'est en effet actuellement pas possible.
