### ISSUE TITLE
Connexion error : "Noms d'utilisateurs différents"

### ISSUE THREAD

**Issue by antyamok** [libertempo/web#944]
**Décrivez le bug**
Il m'est impossible de me connecter à libertempo (v1.13). Je n'ai rencontré aucune erreur lors de linstallation . La commande `make heck` me donne comme résultat `Vérifications effectuées avec succés`.
Avec l'extension <rested> j'ai un resultat en 200.

Cependant lorsque je me connecte, après authentification, j'ai l'écran avec juste "Nom d'utilisateurs différents".

**Comment by wouldsmina** [comment]
Doublon avec #904.
