### ISSUE TITLE
intitulés des menus interchangés

### ISSUE THREAD

**Issue by alainco75** [libertempo/web#946]
Libertempo 1.13 "Nooma" sous debian

Je ne sais pas ce qui s'est passé. Depuis quelques heures, les intitulés des menus de libertempo semblent interchangés.
Sur la page de connexion, on a "supprimer" à la place de "valider" sur le bouton.
Dans le menu, à la place de "utilisateurs" on a "attention: calcul impossible"
à la place de déconnexion, on a : édition papier etc .....

Comment corriger cela?

cordialement

Alain C.
Observatoire

**Comment by alainco75** [comment]
Bizarre, j'ai simplement redémarré apache et tout est rentré dans l'ordre (et il y a d'autres bases libertempo sur la même machine et les autres bases n'avaient pas ce problème)

cordialement

Alain C.
Observatoire de Paris

**Comment by wouldsmina** [comment]
Bonjour,
Cela arrive lorsque les fichiers de traduction sont modifié. En effet un restart d'apache permet à gettext de recharger les fichiers proprement.
